export type VerificationReason =
  | "OK"
  | "INVALID_SIGNATURE"
  | "INSUFFICIENT_SIGNATURES"
  | "INVALID_ATTESTATION"
  | "INSUFFICIENT_ATTESTATIONS"
  | "POLICY_VIOLATION"
  | "REVOKED"
  | "UNSUPPORTED_VERSION";
