ALTER TABLE users
  ADD COLUMN IF NOT EXISTS failed_login_attempts INTEGER     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS lockout_until         TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS last_failed_login_at  TIMESTAMPTZ NULL;
