-- 20261049_asset_identifiers_freshness_grant.sql
--
-- PLAT-ASSET-1 v1: make asset_identifiers freshness maintainable — and
-- nothing else.
--
-- THE LATENT DEFECT THIS RESOLVES: 20261033 shipped last_seen_at/updated_at
-- columns (lines 66-68) but granted app_request only SELECT/INSERT/DELETE —
-- "an alias is asserted or withdrawn, never edited". With no UPDATE grant,
-- NOTHING could ever maintain last_seen_at: the schema promised a freshness
-- signal it structurally could not deliver. PLAT-ASSET-1's attach path
-- ("exact strong-identity matches attach/update the existing canonical
-- asset" — operator ruling 2026-08-22) inherits the duty to fix it.
--
-- WHY A COLUMN-LEVEL GRANT (architect ruling D):
--   * DELETE+INSERT to refresh was rejected outright — it destroys
--     first_seen_at, i.e. FABRICATES history, the exact thing the no-UPDATE
--     ruling exists to prevent.
--   * A full-row UPDATE grant would let a request path edit an alias into a
--     different identity, which the 20261033 ruling forbids.
--   The column-level grant ENFORCES the ruling at the DB layer better than
--   before: scheme/value/source/asset_id remain non-updatable by grant,
--   while freshness — which was always meant to move — becomes maintainable.
--   The 20261033 header's rule stands unmodified; this narrows its
--   enforcement to exactly the columns it was about.
--
-- RLS: the existing asset_identifiers_tenant_isolation policy already
-- carries USING + WITH CHECK, so the new UPDATE capability is tenant-scoped
-- from the first statement.

GRANT UPDATE (last_seen_at, updated_at) ON asset_identifiers TO app_request;
