/**
 * reportPdfRendering.test.ts — rendered-PDF regression suite for the staging
 * report defects (REP-1 branding, REP-2 framework language, REP-3 pagination,
 * REP-4 requirement-block overlap).
 *
 * These tests parse the ACTUAL rendered PDF bytes (pdf-parse for text,
 * pdfjs-dist for glyph positions), not template strings:
 *   - REP-4: on the audit package's requirement pages, the status badge was
 *     written back at the top of the requirement block without restoring the
 *     flow cursor. pdfkit leaves doc.y below its last write, so the cursor
 *     rewound to the top of the block and the control name, assessment status,
 *     summary and evidence were stamped on top of the requirement title. We
 *     assert no two text boxes on a page overlap.
 *   - REP-3: footer stamping used to write inside pdfkit's bottom margin,
 *     which triggers an implicit page break per write — a 5-page gap report
 *     rendered as 15 pages, 10 of them footer-only. We assert every page has
 *     real content and "Page N of TOTAL" matches the true page count.
 *   - REP-2: a gap report generated for NIST CSF used to be titled/worded as
 *     SOC 2. We assert framework-derived wording and zero SOC 2 references.
 *   - REP-1: reports embed the canonical SecureLogic AI logo image (not a
 *     styled text wordmark) and keep the "Generated by SecureLogic AI"
 *     attribution.
 */

import { describe, it, expect, vi } from "vitest";
import { PassThrough } from "stream";

// The route modules pull in the DB pool and auth middleware at import time;
// these tests only exercise the exported PDF generators, so stub them out.
vi.mock("../infra/postgres.js", () => ({
  pg: { query: vi.fn() },
  withTenant: vi.fn(),
}));
vi.mock("../middleware/requireApiKey.js", () => ({
  requireApiKey: (_req: unknown, _res: unknown, next: () => void) => next(),
}));
vi.mock("../middleware/attachOrganizationContext.js", () => ({
  attachOrganizationContext: (_req: unknown, _res: unknown, next: () => void) => next(),
}));
vi.mock("../middleware/requireEntitlement.js", () => ({
  requireEntitlement: () => (_req: unknown, _res: unknown, next: () => void) => next(),
}));
import { PDFParse } from "pdf-parse";
import { generateGapReportPDF, type GapReportData } from "../routes/gapReport.js";
import { generateAuditPackagePDF, type AuditPackage } from "../routes/auditPackage.js";
import { generateExecutivePDF, type ExecReportData } from "../routes/executiveReport.js";
import { secureLogicLogo } from "../lib/reportBranding.js";

// ─── Render + parse helpers ────────────────────────────────────────────────────

async function renderToBuffer(
  generate: (out: NodeJS.WritableStream) => void
): Promise<Buffer> {
  const out = new PassThrough();
  const chunks: Buffer[] = [];
  out.on("data", (c) => chunks.push(c as Buffer));
  const done = new Promise<void>((resolve, reject) => {
    out.on("end", resolve);
    out.on("error", reject);
  });
  generate(out);
  await done;
  return Buffer.concat(chunks);
}

type ParsedPdf = {
  total: number;
  pages: Array<{ num: number; text: string }>;
  fullText: string;
};

async function parsePdf(buf: Buffer): Promise<ParsedPdf> {
  // pdf-parse v2 throws on `instanceof Buffer`, and pdf.js detaches the
  // ArrayBuffer it is given — hand it a copied plain Uint8Array so `buf`
  // stays readable after parsing.
  const parser = new PDFParse(new Uint8Array(buf));
  const result = await parser.getText();
  return { total: result.total, pages: result.pages, fullText: result.text };
}

type TextBox = {
  page: number;
  text: string;
  x0: number; x1: number;
  y0: number; y1: number;
};

/**
 * Every rendered glyph run with its box, in PDF user space (y grows upward).
 * pdf-parse only exposes text, so go to pdfjs directly for the geometry.
 */
async function extractBoxes(buf: Buffer): Promise<TextBox[]> {
  const pdfjs: any = await import("pdfjs-dist/legacy/build/pdf.mjs");
  const doc = await pdfjs.getDocument({
    data: new Uint8Array(buf),
    useSystemFonts: true,
  }).promise;

  const boxes: TextBox[] = [];
  for (let p = 1; p <= doc.numPages; p++) {
    const page = await doc.getPage(p);
    const content = await page.getTextContent();
    for (const item of content.items as any[]) {
      if (!item.str || !item.str.trim()) continue;
      const x = item.transform[4];
      const baseline = item.transform[5];
      boxes.push({
        page: p,
        text: item.str,
        x0: x,
        x1: x + item.width,
        y0: baseline,
        y1: baseline + item.height,
      });
    }
  }
  return boxes;
}

/**
 * No two text boxes on a page may share ink. Tolerance absorbs the sub-point
 * slop between pdfjs' reported glyph box and the real inked extent (descenders,
 * side bearings) — a real collision is many points deep, not fractions.
 */
function expectNoOverlappingText(boxes: TextBox[]): void {
  const TOL = 1.5;
  const byPage = new Map<number, TextBox[]>();
  for (const b of boxes) byPage.set(b.page, [...(byPage.get(b.page) ?? []), b]);

  for (const [page, items] of byPage) {
    for (let i = 0; i < items.length; i++) {
      for (let j = i + 1; j < items.length; j++) {
        const a = items[i]!;
        const b = items[j]!;
        const xOverlap = Math.min(a.x1, b.x1) - Math.max(a.x0, b.x0);
        const yOverlap = Math.min(a.y1, b.y1) - Math.max(a.y0, b.y0);
        expect(
          xOverlap > TOL && yOverlap > TOL,
          `page ${page}: ${JSON.stringify(a.text)} overlaps ${JSON.stringify(b.text)} ` +
            `by ${xOverlap.toFixed(1)}x${yOverlap.toFixed(1)}pt`
        ).toBe(false);
      }
    }
  }
}

/** Page text with footer/header chrome removed — what's left must be content. */
function stripChrome(pageText: string): string {
  return pageText
    .replace(/SecureLogic AI\s*[—–-]\s*Confidential/g, "")
    .replace(/Page \d+ of \d+/g, "")
    .replace(/CONFIDENTIAL/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function expectNoArtifactPages(parsed: ParsedPdf): void {
  for (const page of parsed.pages) {
    const content = stripChrome(page.text);
    expect(
      content.length,
      `page ${page.num} of ${parsed.total} is blank or footer-only: ${JSON.stringify(page.text)}`
    ).toBeGreaterThan(20);
  }
}

function expectConsistentPageNumbers(parsed: ParsedPdf): void {
  const labels = [...parsed.fullText.matchAll(/Page (\d+) of (\d+)/g)];
  // A footer on every page…
  expect(labels.length).toBe(parsed.total);
  // …each declaring the true total…
  for (const m of labels) {
    expect(Number(m[2])).toBe(parsed.total);
  }
  // …and covering every page number exactly once.
  const numbers = labels.map((m) => Number(m[1])).sort((a, b) => a - b);
  expect(numbers).toEqual(Array.from({ length: parsed.total }, (_, i) => i + 1));
}

// ─── Fixtures ──────────────────────────────────────────────────────────────────

const NIST_CATEGORIES = ["GV.OC", "GV.RM", "ID.AM", "ID.RA", "PR.AA", "PR.DS", "DE.CM", "RS.MA", "RC.RP"];

function makeGapReport(overrides: Partial<GapReportData> = {}): GapReportData {
  const requirements: GapReportData["requirements"] = [];
  for (let i = 0; i < 54; i++) {
    const cat = NIST_CATEGORIES[i % NIST_CATEGORIES.length]!;
    const status = i % 3 === 0 ? "satisfied" : i % 3 === 1 ? "partial" : "unmapped";
    requirements.push({
      id: `00000000-0000-4000-8000-${String(i).padStart(12, "0")}`,
      reference_id: `${cat}-${String(i + 1).padStart(2, "0")}`,
      title: `Requirement ${i + 1}: establish and maintain documented processes for area ${i + 1}`,
      status,
      controls:
        status === "unmapped"
          ? []
          : [
              {
                control_id: `10000000-0000-4000-8000-${String(i).padStart(12, "0")}`,
                control_name: `Control ${i + 1}`,
                latest_assessment_status: status === "satisfied" ? "passed" : i % 2 === 0 ? "failed" : null,
                is_overdue: false,
              },
            ],
      gap_reason: status === "partial" ? (i % 2 === 0 ? "failing" : "unassessed") : null,
    });
  }
  const satisfied = requirements.filter((r) => r.status === "satisfied").length;
  const partial = requirements.filter((r) => r.status === "partial").length;
  const unmapped = requirements.filter((r) => r.status === "unmapped").length;

  return {
    generated_at: "2026-07-16T12:00:00.000Z",
    org_name: "Acme Health Systems",
    framework: { id: "20000000-0000-4000-8000-000000000000", name: "NIST CSF", version: "2.0" },
    readiness_score: Math.round((satisfied / requirements.length) * 100),
    total_requirements: requirements.length,
    satisfied,
    partial,
    unmapped,
    total_mapped_controls: satisfied + partial,
    requirements,
    findings_by_severity: [
      { severity: "Critical", count: 2 },
      { severity: "High", count: 5 },
      { severity: "Moderate", count: 9 },
      { severity: "Low", count: 3 },
    ],
    ...overrides,
  };
}

function makeAuditPackage(overrides: Partial<AuditPackage> = {}): AuditPackage {
  const requirements: AuditPackage["requirements"] = [];
  for (let i = 0; i < 32; i++) {
    const cat = NIST_CATEGORIES[i % NIST_CATEGORIES.length]!;
    const status = i % 3 === 0 ? "satisfied" : i % 3 === 1 ? "partial" : "unmapped";
    requirements.push({
      id: `00000000-0000-4000-8000-${String(i).padStart(12, "0")}`,
      reference_id: `${cat}-${String(i + 1).padStart(2, "0")}`,
      title: `Requirement ${i + 1}: maintain documented and operated processes for area ${i + 1}`,
      status,
      controls:
        status === "unmapped"
          ? []
          : [
              {
                control_id: `10000000-0000-4000-8000-${String(i).padStart(12, "0")}`,
                control_name: `Control ${i + 1} — quarterly review`,
                assessment_id: status === "satisfied" ? `30000000-0000-4000-8000-${String(i).padStart(12, "0")}` : null,
                assessment_status: status === "satisfied" ? "passed" : null,
                overall_severity: null,
                assessment_summary: status === "satisfied" ? "Operating effectively during the review period." : null,
                performed_at: status === "satisfied" ? "2026-06-01T00:00:00.000Z" : null,
                evidence:
                  status === "satisfied"
                    ? [
                        {
                          id: `40000000-0000-4000-8000-${String(i).padStart(12, "0")}`,
                          title: `Evidence artifact ${i + 1}`,
                          evidence_type: "document",
                          description: null,
                          collected_at: "2026-06-01T00:00:00.000Z",
                          collected_by: "Auditor",
                          external_ref: null,
                        },
                      ]
                    : [],
              },
            ],
    });
  }
  const satisfied = requirements.filter((r) => r.status === "satisfied").length;
  const partial = requirements.filter((r) => r.status === "partial").length;
  const unmapped = requirements.filter((r) => r.status === "unmapped").length;

  return {
    generated_at: "2026-07-16T12:00:00.000Z",
    organization: { name: "Acme Health Systems" },
    framework: { id: "20000000-0000-4000-8000-000000000000", name: "NIST CSF", version: "2.0" },
    readiness_summary: {
      readiness_score: Math.round((satisfied / requirements.length) * 100),
      total_requirements: requirements.length,
      satisfied,
      partial,
      unmapped,
    },
    requirements,
    ...overrides,
  };
}

/**
 * The realistic shape of a NIST CSF package: long titles that wrap to several
 * lines, several controls per requirement, and multi-item evidence. This is the
 * fixture that reproduced REP-4 — short titles happen to leave enough slack to
 * hide a cursor rewind.
 */
function makeVerboseAuditPackage(): AuditPackage {
  const requirements: AuditPackage["requirements"] = [];
  for (let i = 0; i < 18; i++) {
    const cat = NIST_CATEGORIES[i % NIST_CATEGORIES.length]!;
    const status = i % 3 === 0 ? "satisfied" : i % 3 === 1 ? "partial" : "unmapped";
    const controlCount = status === "unmapped" ? 0 : (i % 2) + 2;
    requirements.push({
      id: `00000000-0000-4000-8000-${String(i).padStart(12, "0")}`,
      reference_id: `${cat}-${String(i + 1).padStart(2, "0")}`,
      title:
        `Requirement ${i + 1}: the organization establishes, documents, communicates and ` +
        `maintains policies, processes and procedures governing area ${i + 1}, and reviews ` +
        `them at planned intervals and whenever a significant change occurs`,
      status,
      controls: Array.from({ length: controlCount }, (_, k) => ({
        control_id: `1000000${k}-0000-4000-8000-${String(i).padStart(12, "0")}`,
        control_name:
          `Control ${i + 1}.${k + 1} — quarterly access review with documented approver ` +
          `sign-off and retained exception handling records`,
        assessment_id:
          status === "satisfied" ? `3000000${k}-0000-4000-8000-${String(i).padStart(12, "0")}` : null,
        assessment_status: status === "satisfied" ? "passed" : k % 2 === 0 ? "failed" : null,
        overall_severity: status === "satisfied" ? null : "Moderate",
        assessment_summary:
          `Testing covered the full review period. The control operated as designed for ` +
          `sampled populations, with exceptions tracked to closure and evidence retained ` +
          `in the governance repository for area ${i + 1}.`,
        performed_at: "2026-06-01T00:00:00.000Z",
        evidence: Array.from({ length: (i % 3) + 1 }, (_, e) => ({
          id: `4000000${e}-0000-4000-8000-${String(i).padStart(12, "0")}`,
          title: `Evidence artifact ${i + 1}.${k + 1}.${e + 1} — signed quarterly review export`,
          evidence_type: "document",
          description: null,
          collected_at: "2026-06-01T00:00:00.000Z",
          collected_by: "Internal Audit",
          external_ref: `GRC-${i + 1}-${k + 1}-${e + 1}`,
        })),
      })),
    });
  }
  const satisfied = requirements.filter((r) => r.status === "satisfied").length;
  const partial = requirements.filter((r) => r.status === "partial").length;
  const unmapped = requirements.filter((r) => r.status === "unmapped").length;

  return {
    generated_at: "2026-07-16T12:00:00.000Z",
    organization: { name: "Acme Health Systems" },
    framework: { id: "20000000-0000-4000-8000-000000000000", name: "NIST CSF", version: "2.0" },
    readiness_summary: {
      readiness_score: Math.round((satisfied / requirements.length) * 100),
      total_requirements: requirements.length,
      satisfied,
      partial,
      unmapped,
    },
    requirements,
  };
}

function makeExecReport(): ExecReportData {
  return {
    generated_at: "2026-07-16T12:00:00.000Z",
    org_name: "Acme Health Systems",
    posture: { overall_score: 62, overall_severity: "Moderate", snapshot_date: "2026-07-15" },
    posture_prior: { overall_score: 48, overall_severity: "High", snapshot_date: "2026-04-15" },
    // Reconciled primary-domain rollup (#683): 2 + 23 + 1 = 26 → Total Active Findings.
    posture_domains: [
      { domain: "Access Control", score: 40, severity: "High", finding_count: 2 },
      { domain: "Data Protection", score: 8, severity: "Critical", finding_count: 23 },
      { domain: "Vendor Risk", score: 72, severity: "Low", finding_count: 1 },
    ],
    posture_finding_total: 26,
    open_actions_count: 7,
    risks_by_rating: [
      { rating: "High", count: 3 },
      { rating: "Moderate", count: 6 },
    ],
    risks_by_inherent_rating: [
      { rating: "Critical", count: 2 },
      { rating: "High", count: 7 },
    ],
    frameworks: [
      { name: "NIST CSF", version: "2.0", total: 54, satisfied: 18, partial: 18, unmapped: 18 },
    ],
    findings_by_severity: [
      { severity: "Critical", count: 2 },
      { severity: "High", count: 5 },
    ],
    recent_findings: [
      { title: "MFA not enforced for admins", severity: "High", status: "open", created_at: "2026-07-01T00:00:00.000Z" },
    ],
    period: {
      days: 90,
      findings_closed: 4,
      findings_risk_accepted: 1,
      findings_reopened: 0,
      findings_remediated: 3,
      findings_new: 6,
      risks_closed: 2,
      risk_approvals: 1,
    },
  };
}

// ─── Gap report ────────────────────────────────────────────────────────────────

describe("gap report PDF", () => {
  it("REP-3: renders no blank/footer-only pages and page numbers match the real count", async () => {
    const buf = await renderToBuffer((out) => generateGapReportPDF(makeGapReport(), out));
    expect(buf.subarray(0, 5).toString("ascii")).toBe("%PDF-");

    const parsed = await parsePdf(buf);
    // Multi-page report (cover + summary + table + gaps + findings).
    expect(parsed.total).toBeGreaterThanOrEqual(4);
    expectNoArtifactPages(parsed);
    expectConsistentPageNumbers(parsed);
    // REP-4 guard: the gap report draws its own right-aligned priority badges.
    expectNoOverlappingText(await extractBoxes(buf));
  });

  it("REP-2: a NIST CSF report carries NIST CSF title/version and zero SOC 2 references", async () => {
    const buf = await renderToBuffer((out) => generateGapReportPDF(makeGapReport(), out));
    const parsed = await parsePdf(buf);

    expect(parsed.pages[0]!.text).toContain("NIST CSF 2.0 Gap Analysis");
    expect(parsed.fullText).toContain("NIST CSF");
    expect(parsed.fullText).not.toContain("SOC 2");
    expect(parsed.fullText).not.toContain("SOC2");
  });

  it("REP-2: a SOC 2 report still carries SOC 2 language", async () => {
    const soc2 = makeGapReport({
      framework: { id: "20000000-0000-4000-8000-000000000001", name: "SOC 2", version: "2017 TSC" },
    });
    const buf = await renderToBuffer((out) => generateGapReportPDF(soc2, out));
    const parsed = await parsePdf(buf);

    expect(parsed.pages[0]!.text).toContain("SOC 2 2017 TSC Gap Analysis");
    expect(parsed.fullText).toContain("SOC 2");
    expect(parsed.fullText).not.toContain("NIST CSF");
  });

  it("REP-2: gap report source has no hard-coded SOC 2 wording or soc2 filename", async () => {
    const { readFileSync } = await import("fs");
    const { resolve } = await import("path");
    const source = readFileSync(resolve(__dirname, "../routes/gapReport.ts"), "utf8");
    // Framework wording must come from data.framework — no SOC 2 string
    // literals in titles, filenames, or narrative (comments excluded).
    const codeLines = source
      .split("\n")
      .filter((l) => !l.trim().startsWith("//") && !l.trim().startsWith("*"));
    expect(codeLines.join("\n")).not.toMatch(/SOC ?2/i);
    expect(source).toContain("safeFilename(data.framework.name)}-gap-report-");
  });

  it("REP-1: embeds the SecureLogic AI logo image and keeps the attribution", async () => {
    // The canonical logo asset ships with the engine.
    expect(secureLogicLogo()).not.toBeNull();

    const buf = await renderToBuffer((out) => generateGapReportPDF(makeGapReport(), out));
    const raw = buf.toString("latin1");
    // pdfkit embeds the PNG as an image XObject.
    expect(raw).toMatch(/\/Subtype\s*\/Image/);

    const parsed = await parsePdf(buf);
    expect(parsed.pages[0]!.text).toContain("Generated by");
    expect(parsed.pages[0]!.text).toContain("SecureLogic AI");
  });
});

// ─── Audit package ─────────────────────────────────────────────────────────────

describe("audit package PDF", () => {
  it("REP-3: no CONFIDENTIAL-only, page-number-only, or blank pages; numbering matches count", async () => {
    const buf = await renderToBuffer((out) => generateAuditPackagePDF(makeAuditPackage(), out));
    expect(buf.subarray(0, 5).toString("ascii")).toBe("%PDF-");

    const parsed = await parsePdf(buf);
    expect(parsed.total).toBeGreaterThanOrEqual(3);
    expectNoArtifactPages(parsed);
    expectConsistentPageNumbers(parsed);
  });

  it("REP-2: uses the selected framework's name and version consistently", async () => {
    const buf = await renderToBuffer((out) => generateAuditPackagePDF(makeAuditPackage(), out));
    const parsed = await parsePdf(buf);

    expect(parsed.pages[0]!.text).toContain("NIST CSF");
    expect(parsed.pages[0]!.text).toContain("Version 2.0");
    expect(parsed.fullText).not.toContain("SOC 2");
  });

  it("REP-1: embeds the logo image and the Generated by SecureLogic AI attribution", async () => {
    const buf = await renderToBuffer((out) => generateAuditPackagePDF(makeAuditPackage(), out));
    expect(buf.toString("latin1")).toMatch(/\/Subtype\s*\/Image/);

    const parsed = await parsePdf(buf);
    expect(parsed.pages[0]!.text).toContain("Generated by SecureLogic AI");
  });

  // ── REP-4: requirement blocks must not overlap ──────────────────────────────

  it("REP-4: no text overlaps any other text on any page", async () => {
    const buf = await renderToBuffer((out) => generateAuditPackagePDF(makeAuditPackage(), out));
    expectNoOverlappingText(await extractBoxes(buf));
  });

  it("REP-4: still no overlap when titles wrap and controls carry evidence", async () => {
    const buf = await renderToBuffer((out) =>
      generateAuditPackagePDF(makeVerboseAuditPackage(), out)
    );
    expectNoOverlappingText(await extractBoxes(buf));
  });

  it("REP-4: a wrapped requirement title never runs under the status badge", async () => {
    const buf = await renderToBuffer((out) =>
      generateAuditPackagePDF(makeVerboseAuditPackage(), out)
    );
    const boxes = await extractBoxes(buf);

    const badges = boxes.filter((b) => /^(SATISFIED|PARTIAL|UNMAPPED)$/.test(b.text.trim()));
    expect(badges.length).toBeGreaterThan(0);

    // Requirement titles start with "Requirement N:" in the fixture.
    const titles = boxes.filter((b) => b.text.trim().startsWith("Requirement "));
    expect(titles.length).toBeGreaterThan(0);

    for (const badge of badges) {
      for (const title of titles.filter((t) => t.page === badge.page)) {
        expect(
          title.x1 <= badge.x0,
          `title ${JSON.stringify(title.text)} extends to x=${title.x1.toFixed(1)}, ` +
            `into the badge column starting at x=${badge.x0.toFixed(1)}`
        ).toBe(true);
      }
    }
  });

  it("REP-4: every requirement renders exactly once", async () => {
    const pkg = makeVerboseAuditPackage();
    const buf = await renderToBuffer((out) => generateAuditPackagePDF(pkg, out));
    const parsed = await parsePdf(buf);

    for (const req of pkg.requirements) {
      const hits = parsed.fullText.split(req.reference_id).length - 1;
      expect(hits, `${req.reference_id} rendered ${hits} times, expected once`).toBe(1);
    }
  });

  it("REP-4: no requirement content is written into the footer zone", async () => {
    const buf = await renderToBuffer((out) =>
      generateAuditPackagePDF(makeVerboseAuditPackage(), out)
    );
    const boxes = await extractBoxes(buf);
    // stampFooters draws its rule 36pt from the bottom of the page. In PDF user
    // space (y grows upward) that is y=36, and the only ink allowed below it is
    // the footer text itself. Page 1 is the cover, which deliberately carries a
    // centred CONFIDENTIAL line down in the footer band.
    const FOOTER_TOP = 36;
    for (const b of boxes) {
      if (b.page === 1) continue;
      const isFooter =
        b.text.includes("SecureLogic AI") || /^Page \d+ of \d+$/.test(b.text.trim());
      if (isFooter) continue;
      expect(
        b.y0,
        `page ${b.page}: ${JSON.stringify(b.text)} sits in the footer zone`
      ).toBeGreaterThan(FOOTER_TOP);
    }
  });
});

// ─── Executive report ──────────────────────────────────────────────────────────

describe("executive report PDF", () => {
  it("REP-3/REP-1/REP-4: no artifact pages, no overlap, consistent numbering, embedded logo", async () => {
    const buf = await renderToBuffer((out) => generateExecutivePDF(makeExecReport(), out));
    const parsed = await parsePdf(buf);

    expectNoArtifactPages(parsed);
    expectConsistentPageNumbers(parsed);
    expectNoOverlappingText(await extractBoxes(buf));
    expect(buf.toString("latin1")).toMatch(/\/Subtype\s*\/Image/);
    expect(parsed.pages[0]!.text).toContain("Generated by");
  });

  // ── ESR-1: posture trend wording is deterministic and well-encoded ──────────
  it("ESR-1: an improved posture reads 'increased by N points' with no malformed glyphs", async () => {
    const buf = await renderToBuffer((out) => generateExecutivePDF(makeExecReport(), out));
    const parsed = await parsePdf(buf);

    // 62 vs 48 (health-style, higher = better) → +14.
    expect(parsed.fullText).toContain("increased by 14 points");
    expect(parsed.fullText).toContain("higher = better");
    // The old malformed label and its raw glyphs must be gone.
    expect(parsed.fullText).not.toContain("unchanged points");
    for (const glyph of ["▲", "▼", "◆", "�", "Æ"]) {
      expect(parsed.fullText.includes(glyph), `PDF text contains malformed char ${JSON.stringify(glyph)}`).toBe(false);
    }
  });

  it("ESR-1: a declined posture reads 'decreased by N points'", async () => {
    const declined = makeExecReport();
    declined.posture = { overall_score: 40, overall_severity: "High", snapshot_date: "2026-07-15" };
    declined.posture_prior = { overall_score: 55, overall_severity: "Moderate", snapshot_date: "2026-04-15" };
    const buf = await renderToBuffer((out) => generateExecutivePDF(declined, out));
    const parsed = await parsePdf(buf);

    expect(parsed.fullText).toContain("decreased by 15 points");
    expect(parsed.fullText).not.toContain("-15 points");
  });

  it("ESR-1: an unchanged posture reads 'no change' (never a malformed percentage)", async () => {
    const flat = makeExecReport();
    flat.posture = { overall_score: 50, overall_severity: "Moderate", snapshot_date: "2026-07-15" };
    flat.posture_prior = { overall_score: 50, overall_severity: "Moderate", snapshot_date: "2026-04-15" };
    const buf = await renderToBuffer((out) => generateExecutivePDF(flat, out));
    const parsed = await parsePdf(buf);

    expect(parsed.fullText).toContain("no change");
    expect(parsed.fullText).not.toMatch(/%[^\s]/); // no stray "%X" style artifacts
    for (const glyph of ["▲", "▼", "◆", "�"]) {
      expect(parsed.fullText.includes(glyph)).toBe(false);
    }
  });

  // ── ESR-2: reconciled domain breakdown renders and sums to the total ────────
  it("ESR-2: domain breakdown shows each domain and its counts sum to Total Active Findings", async () => {
    const buf = await renderToBuffer((out) => generateExecutivePDF(makeExecReport(), out));
    const parsed = await parsePdf(buf);

    expect(parsed.fullText).toContain("Posture Domain Breakdown");
    for (const domain of ["Access Control", "Data Protection", "Vendor Risk"]) {
      expect(parsed.fullText).toContain(domain);
    }
    // Health-style values (higher = better) match what /posture would show.
    expect(parsed.fullText).toContain("40/100");
    expect(parsed.fullText).toContain("8/100");
    expect(parsed.fullText).toContain("72/100");
    // Reconciliation: 2 + 23 + 1 = 26 Total Active Findings.
    expect(parsed.fullText).toContain("TOTAL ACTIVE FINDINGS");
    const fixture = makeExecReport();
    const sum = fixture.posture_domains.reduce((s, d) => s + d.finding_count, 0);
    expect(sum).toBe(26);
    expect(sum).toBe(fixture.posture_finding_total);
  });

  it("ESR-2: with no snapshot, the domain section degrades to a clear message (no crash)", async () => {
    const empty = makeExecReport();
    empty.posture = null;
    empty.posture_prior = null;
    empty.posture_domains = [];
    empty.posture_finding_total = null;
    const buf = await renderToBuffer((out) => generateExecutivePDF(empty, out));
    const parsed = await parsePdf(buf);

    expect(parsed.pages[0]!.text.length).toBeGreaterThan(0);
    expect(parsed.fullText).toContain("Posture Domain Breakdown");
    expect(parsed.fullText).toContain("No posture snapshot exists yet");
    expectNoArtifactPages(parsed);
    expectConsistentPageNumbers(parsed);
    expectNoOverlappingText(await extractBoxes(buf));
  });
});
