/**
 * vendorAssuranceDocuments.test.ts — handler-level behavioral tests with
 * mocked pg, mocked vendorAssuranceStorage, mocked auditLog, and mocked
 * extraction runner. The middleware chain (feature flag, requireApiKey,
 * attachOrganizationContext, requireEntitlement) is intentionally not under
 * test here — those are independently verified upstream and in their own
 * test files.
 *
 * What we DO assert:
 *   - org-scoped reads/writes
 *   - cross-org returns 404
 *   - upload happy path: blob put, audit, schedule extraction, 202
 *   - upload failure-mode codes: missing vendor, no file, oversized, non-PDF,
 *     blob put failure
 *   - review-decisions handler INSERTs new rows (no UPSERT) and rejects
 *     unknown field_name; second decision on same field appends
 *   - finalize 409 paths and 200 happy path; idempotent re-call returns 409
 *   - PDF URL endpoint scopes by org and audits issuance
 *   - GET extraction returns the DISTINCT ON read projection
 */

import { describe, it, expect, vi, beforeEach } from "vitest";
import { MATERIAL_FIELD_NAMES } from "../lib/socExtractionPrompt.js";

const {
  pgQuerySpy,
  pgConnectClientQuerySpy,
  pgConnectClientReleaseSpy,
  refreshCuecMappingsForDocumentSpy
} = vi.hoisted(() => ({
  pgQuerySpy: vi.fn(),
  pgConnectClientQuerySpy: vi.fn(),
  pgConnectClientReleaseSpy: vi.fn(),
  refreshCuecMappingsForDocumentSpy: vi.fn()
}));

vi.mock("../infra/postgres.js", () => ({
  pg: {
    query: pgQuerySpy,
    connect: vi.fn().mockResolvedValue({
      query: pgConnectClientQuerySpy,
      release: pgConnectClientReleaseSpy
    })
  }
}));

vi.mock("../lib/auditLog.js", () => ({
  writeAuditEvent: vi.fn()
}));

vi.mock("../lib/vendorAssuranceCuecMatcher.js", () => ({
  refreshCuecMappingsForDocument: refreshCuecMappingsForDocumentSpy,
  MATCH_SCORE_MIN_THRESHOLD: 60,
  MATCH_SCORE_HIGH_CONFIDENCE: 85
}));

const putVendorAssurancePdfSpy = vi.fn();
const getVendorAssurancePdfSignedUrlSpy = vi.fn();

vi.mock("../lib/vendorAssuranceStorage.js", () => ({
  putVendorAssurancePdf: (...args: unknown[]) => putVendorAssurancePdfSpy(...args),
  getVendorAssurancePdfStream: vi.fn(),
  getVendorAssurancePdfSignedUrl: (...args: unknown[]) => getVendorAssurancePdfSignedUrlSpy(...args),
  vendorAssuranceObjectKey: (orgId: string, docId: string) => `org/${orgId}/vendor-assurance/${docId}/original.pdf`
}));

const scheduleExtractionSpy = vi.fn();
vi.mock("../lib/vendorAssuranceExtractionRunner.js", () => ({
  scheduleExtraction: (...args: unknown[]) => scheduleExtractionSpy(...args)
}));

// Export builders: keep vendorAssuranceExportData.js mostly real (loadCuecsWithMappings
// is used by the CUEC route handlers under test), but stub buildExportBundle; fully stub
// the two exporters so the export-route tests assert plumbing, not generated bytes.
const buildExportBundleSpy = vi.fn();
const buildWorkbookBufferSpy = vi.fn();
const buildPdfSpy = vi.fn();
vi.mock("../lib/vendorAssuranceExportData.js", async (importOriginal) => {
  const actual = (await importOriginal()) as Record<string, unknown>;
  return { ...actual, buildExportBundle: (...args: unknown[]) => buildExportBundleSpy(...args) };
});
vi.mock("../lib/vendorAssuranceExcelExporter.js", () => ({
  buildVendorAssuranceWorkbook: vi.fn(),
  buildVendorAssuranceWorkbookBuffer: (...args: unknown[]) => buildWorkbookBufferSpy(...args),
  workbookDownloadFilename: () => "acme-cloud-2025-09-30-soc-review.xlsx"
}));
vi.mock("../lib/vendorAssurancePdfExporter.js", () => ({
  buildVendorAssurancePdf: (...args: unknown[]) => buildPdfSpy(...args),
  pdfDownloadFilename: () => "acme-cloud-2025-09-30-soc-review.pdf"
}));

import { MAX_ORG_STORAGE_BYTES } from "../lib/vendorAssuranceValidation.js";
import {
  uploadVendorAssuranceDocument,
  listVendorAssuranceDocuments,
  getVendorAssuranceDocument,
  getVendorAssuranceExtraction,
  getVendorAssurancePdfRedirect,
  recordVendorAssuranceReviewDecisions,
  finalizeVendorAssuranceDocument,
  recordVendorAssuranceFieldOverride,
  approveVendorAssuranceDocument,
  requestVendorAssuranceManualReview,
  rejectVendorAssuranceDocument,
  getVendorAssuranceCuecs,
  rematchVendorAssuranceCuecs,
  createVendorAssuranceCuecMapping,
  updateVendorAssuranceCuecMapping,
  updateVendorAssuranceCuecReviewStatus,
  exportVendorAssuranceDocumentXlsx,
  exportVendorAssuranceDocumentPdf
} from "../routes/vendorAssuranceDocuments.js";
import { writeAuditEvent } from "../lib/auditLog.js";

const ORG_A = "11111111-1111-4111-8111-111111111111";
const ORG_B = "22222222-2222-4222-8222-222222222222";
const VENDOR_ID = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
const DOC_ID = "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb";
const EXTRACTION_ID = "cccccccc-cccc-4ccc-8ccc-cccccccccccc";
const USER_ID = "dddddddd-dddd-4ddd-8ddd-dddddddddddd";

function buildReq(overrides: Partial<Record<string, unknown>> = {}): Record<string, unknown> {
  return {
    organizationContext: { organizationId: ORG_A },
    apiKey: { id: "k1" },
    userId: USER_ID,
    ip: "127.0.0.1",
    body: {},
    params: {},
    query: {},
    ...overrides
  };
}

function buildRes(): {
  res: Record<string, unknown>;
  status: ReturnType<typeof vi.fn>;
  json: ReturnType<typeof vi.fn>;
  redirect: ReturnType<typeof vi.fn>;
  send: ReturnType<typeof vi.fn>;
  setHeader: ReturnType<typeof vi.fn>;
} {
  const json = vi.fn();
  const send = vi.fn();
  const redirect = vi.fn();
  const setHeader = vi.fn();
  const status = vi.fn().mockReturnValue({ json, send });
  const res = { status, json, send, redirect, setHeader, headersSent: false };
  return { res, status, json, redirect, send, setHeader };
}

beforeEach(() => {
  pgQuerySpy.mockReset();
  pgConnectClientQuerySpy.mockReset();
  pgConnectClientReleaseSpy.mockReset();
  putVendorAssurancePdfSpy.mockReset();
  getVendorAssurancePdfSignedUrlSpy.mockReset();
  scheduleExtractionSpy.mockReset();
  refreshCuecMappingsForDocumentSpy.mockReset();
  refreshCuecMappingsForDocumentSpy.mockResolvedValue({
    matched: true, cuecCount: 2, controlCount: 5, suggestionsConsidered: 2, suggestionsWritten: 2
  });
  (writeAuditEvent as unknown as ReturnType<typeof vi.fn>).mockReset();
});

// Helper: cuec/mapping row shapes used by the CUEC route tests.
function cuecRow(overrides: Partial<Record<string, unknown>> = {}): Record<string, unknown> {
  return {
    id: "cuec-0", ordinal: 0, cuec_text: "Restrict physical access",
    review_status: "pending", review_status_reason: null,
    review_status_updated_by_user_id: null, review_status_updated_at: null,
    created_at: "2026-05-12T00:00:00Z", updated_at: "2026-05-12T00:00:00Z",
    ...overrides
  };
}
function mappingRow(overrides: Partial<Record<string, unknown>> = {}): Record<string, unknown> {
  return {
    id: "map-1", cuec_id: "cuec-0", control_id: "ctl-a",
    mapping_status: "suggested", mapping_score: 82, mapping_source: "auto",
    reason: null, created_by_user_id: null, updated_by_user_id: null,
    created_at: "2026-05-12T00:00:00Z", updated_at: "2026-05-12T00:00:00Z",
    control_name: "Physical Access Control", control_description: "Badges + visitor logs", control_status: "active",
    ...overrides
  };
}

const CUEC_ID = "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee";
const MAPPING_ID = "ffffffff-ffff-4fff-8fff-ffffffffffff";
const CONTROL_ID = "99999999-9999-4999-8999-999999999999";

// ---------------------------------------------------------------------------
// upload
// ---------------------------------------------------------------------------

describe("uploadVendorAssuranceDocument", () => {
  it("403 when organization context is missing", async () => {
    const req = buildReq({ organizationContext: undefined });
    const { res, status, json } = buildRes();
    await uploadVendorAssuranceDocument(req as never, res as never);
    expect(status).toHaveBeenCalledWith(403);
    expect(json).toHaveBeenCalledWith({ error: "organization_context_missing" });
  });

  it("400 when no file is uploaded", async () => {
    const req = buildReq({ body: { vendor_id: VENDOR_ID } });
    const { res, status, json } = buildRes();
    await uploadVendorAssuranceDocument(req as never, res as never);
    expect(status).toHaveBeenCalledWith(400);
    expect(json).toHaveBeenCalledWith({ error: "no_file_uploaded" });
  });

  it("400 when uploaded file is not a real PDF (magic-byte mismatch)", async () => {
    const req = buildReq({
      body: { vendor_id: VENDOR_ID },
      file: { buffer: Buffer.from("PK\x03\x04"), originalname: "fake.pdf", size: 4, mimetype: "application/pdf" }
    });
    const { res, status, json } = buildRes();
    await uploadVendorAssuranceDocument(req as never, res as never);
    expect(status).toHaveBeenCalledWith(400);
    expect(json).toHaveBeenCalledWith({ error: "invalid_pdf_content" });
    expect(putVendorAssurancePdfSpy).not.toHaveBeenCalled();
  });

  it("400 when vendor_id is missing", async () => {
    const req = buildReq({
      body: {},
      file: { buffer: Buffer.from("%PDF"), originalname: "r.pdf", size: 4, mimetype: "application/pdf" }
    });
    const { res, status } = buildRes();
    await uploadVendorAssuranceDocument(req as never, res as never);
    expect(status).toHaveBeenCalledWith(400);
  });

  it("404 when vendor belongs to another org", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 0, rows: [] }); // vendor pre-flight
    const req = buildReq({
      body: { vendor_id: VENDOR_ID },
      file: { buffer: Buffer.from("%PDF"), originalname: "r.pdf", size: 4, mimetype: "application/pdf" }
    });
    const { res, status, json } = buildRes();
    await uploadVendorAssuranceDocument(req as never, res as never);
    expect(status).toHaveBeenCalledWith(404);
    expect(json).toHaveBeenCalledWith({ error: "vendor_not_found" });
    expect(putVendorAssurancePdfSpy).not.toHaveBeenCalled();
  });

  it("happy path returns 202, writes blob with org-prefixed key, audits, and schedules extraction", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ "?column?": 1 }] }) // vendor pre-flight
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ total_bytes: "0", document_count: "0" }] }) // A05-G2 quota SUM
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, created_at: "2026-05-08T00:00:00Z" }] }) // INSERT
      .mockResolvedValueOnce({ rowCount: 1, rows: [{}] }) // UPDATE storage_key
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "pending" }] }); // SELECT for response

    putVendorAssurancePdfSpy.mockResolvedValueOnce({
      key: `org/${ORG_A}/vendor-assurance/${DOC_ID}/original.pdf`,
      byteSize: 3
    });

    const req = buildReq({
      body: { vendor_id: VENDOR_ID, document_type_hint: "soc2_type2" },
      file: { buffer: Buffer.from("%PDF"), originalname: "report.pdf", size: 4, mimetype: "application/pdf" }
    });
    const { res, status, json } = buildRes();
    await uploadVendorAssuranceDocument(req as never, res as never);

    expect(status).toHaveBeenCalledWith(202);
    expect(putVendorAssurancePdfSpy).toHaveBeenCalledWith({
      organizationId: ORG_A,
      documentId: DOC_ID,
      bytes: expect.any(Buffer)
    });
    expect(scheduleExtractionSpy).toHaveBeenCalledWith({
      documentId: DOC_ID,
      organizationId: ORG_A,
      documentTypeHint: "soc2_type2"
    });
    const auditCalls = (writeAuditEvent as unknown as ReturnType<typeof vi.fn>).mock.calls;
    expect(auditCalls.some((c) => c[0]?.eventType === "vendor_assurance.document.uploaded")).toBe(true);
    expect(json).toHaveBeenCalled();
  });

  it("500 when blob put fails; document marked extraction_failed", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ "?column?": 1 }] }) // vendor pre-flight
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ total_bytes: "0", document_count: "0" }] }) // A05-G2 quota SUM
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, created_at: "x" }] }) // INSERT
      .mockResolvedValueOnce({ rowCount: 1, rows: [{}] }); // UPDATE failed-status
    putVendorAssurancePdfSpy.mockRejectedValueOnce(new Error("R2 unreachable"));

    const req = buildReq({
      body: { vendor_id: VENDOR_ID },
      file: { buffer: Buffer.from("%PDF"), originalname: "r.pdf", size: 4, mimetype: "application/pdf" }
    });
    const { res, status, json } = buildRes();
    await uploadVendorAssuranceDocument(req as never, res as never);
    expect(status).toHaveBeenCalledWith(500);
    expect(json).toHaveBeenCalledWith({ error: "blob_put_failed" });
    expect(scheduleExtractionSpy).not.toHaveBeenCalled();
  });

  // --- A05-G2: per-org cumulative storage quota -----------------------------
  // The file in every quota test is 4 bytes (Buffer.from("%PDF")).

  it("A05-G2: 202 accepts when the upload exactly fills the org storage quota (just under)", async () => {
    // existing usage = limit - 4; + a 4-byte file == limit exactly → not > limit → accept.
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ "?column?": 1 }] }) // vendor pre-flight
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ total_bytes: String(MAX_ORG_STORAGE_BYTES - 4), document_count: "118" }] }) // quota SUM
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, created_at: "x" }] }) // INSERT
      .mockResolvedValueOnce({ rowCount: 1, rows: [{}] }) // UPDATE storage_key
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "pending" }] }); // SELECT
    putVendorAssurancePdfSpy.mockResolvedValueOnce({
      key: `org/${ORG_A}/vendor-assurance/${DOC_ID}/original.pdf`,
      byteSize: 4
    });

    const req = buildReq({
      body: { vendor_id: VENDOR_ID },
      file: { buffer: Buffer.from("%PDF"), originalname: "r.pdf", size: 4, mimetype: "application/pdf" }
    });
    const { res, status } = buildRes();
    await uploadVendorAssuranceDocument(req as never, res as never);

    expect(status).toHaveBeenCalledWith(202);
    expect(putVendorAssurancePdfSpy).toHaveBeenCalled();
    const auditCalls = (writeAuditEvent as unknown as ReturnType<typeof vi.fn>).mock.calls;
    expect(auditCalls.some((c) => c[0]?.eventType === "vendor_assurance.document.upload_quota_rejected")).toBe(false);
  });

  it("A05-G2: 409 org_storage_quota_exceeded when the upload would cross the quota (just over)", async () => {
    // existing usage = limit - 3; + a 4-byte file == limit + 1 → > limit → reject.
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ "?column?": 1 }] }) // vendor pre-flight
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ total_bytes: String(MAX_ORG_STORAGE_BYTES - 3), document_count: "118" }] }); // quota SUM

    const req = buildReq({
      body: { vendor_id: VENDOR_ID },
      file: { buffer: Buffer.from("%PDF"), originalname: "r.pdf", size: 4, mimetype: "application/pdf" }
    });
    const { res, status, json } = buildRes();
    await uploadVendorAssuranceDocument(req as never, res as never);

    expect(status).toHaveBeenCalledWith(409);
    expect(json).toHaveBeenCalledWith({
      error: "org_storage_quota_exceeded",
      used_bytes: MAX_ORG_STORAGE_BYTES - 3,
      limit_bytes: MAX_ORG_STORAGE_BYTES,
      document_count: 118
    });
    // No row created, no blob put, no extraction scheduled.
    expect(pgQuerySpy).toHaveBeenCalledTimes(2); // vendor pre-flight + quota SUM only
    expect(putVendorAssurancePdfSpy).not.toHaveBeenCalled();
    expect(scheduleExtractionSpy).not.toHaveBeenCalled();
  });

  it("A05-G2: quota SUM filters on storage_key LIKE 'org/%' — R2-put-failed rows (storage_key='pending') are excluded", async () => {
    // The SUM itself runs in Postgres; with mocked pg the correctness guarantee
    // is the WHERE clause. A row keeps the literal 'pending' placeholder as its
    // storage_key iff the R2 put never succeeded, so LIKE 'org/%' excludes
    // exactly those rows (bytes never landed in R2).
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ "?column?": 1 }] }) // vendor pre-flight
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ total_bytes: String(MAX_ORG_STORAGE_BYTES), document_count: "1" }] }); // quota SUM
    const req = buildReq({
      body: { vendor_id: VENDOR_ID },
      file: { buffer: Buffer.from("%PDF"), originalname: "r.pdf", size: 4, mimetype: "application/pdf" }
    });
    const { res } = buildRes();
    await uploadVendorAssuranceDocument(req as never, res as never);

    const quotaSql = pgQuerySpy.mock.calls[1]?.[0] as string;
    expect(quotaSql).toMatch(/FROM vendor_assurance_documents/);
    expect(quotaSql).toMatch(/organization_id = \$1/);
    expect(quotaSql).toMatch(/storage_key LIKE 'org\/%'/);
  });

  it("A05-G2: quota SUM does NOT filter on processing_status — runner-failed extraction_failed rows (real org/ key) are included", async () => {
    // 'extraction_failed' is written both by the R2-put-failure path (no bytes
    // in R2) and by the extraction runner (bytes ARE in R2). The quota query
    // must therefore NOT discriminate on processing_status — only on
    // storage_key — so runner-stage failures still count against the quota.
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ "?column?": 1 }] }) // vendor pre-flight
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ total_bytes: String(MAX_ORG_STORAGE_BYTES), document_count: "1" }] }); // quota SUM
    const req = buildReq({
      body: { vendor_id: VENDOR_ID },
      file: { buffer: Buffer.from("%PDF"), originalname: "r.pdf", size: 4, mimetype: "application/pdf" }
    });
    const { res } = buildRes();
    await uploadVendorAssuranceDocument(req as never, res as never);

    const quotaSql = pgQuerySpy.mock.calls[1]?.[0] as string;
    expect(quotaSql).toMatch(/SUM\(byte_size\)/);
    expect(quotaSql).not.toMatch(/processing_status/);
  });

  it("A05-G2: a quota rejection emits the vendor_assurance.document.upload_quota_rejected audit event", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ "?column?": 1 }] }) // vendor pre-flight
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ total_bytes: String(MAX_ORG_STORAGE_BYTES), document_count: "120" }] }); // quota SUM
    const req = buildReq({
      body: { vendor_id: VENDOR_ID },
      file: { buffer: Buffer.from("%PDF"), originalname: "r.pdf", size: 4, mimetype: "application/pdf" }
    });
    const { res, status } = buildRes();
    await uploadVendorAssuranceDocument(req as never, res as never);

    expect(status).toHaveBeenCalledWith(409);
    const auditCalls = (writeAuditEvent as unknown as ReturnType<typeof vi.fn>).mock.calls;
    const ev = auditCalls.find((c) => c[0]?.eventType === "vendor_assurance.document.upload_quota_rejected");
    expect(ev).toBeDefined();
    expect(ev?.[0]).toMatchObject({
      organizationId: ORG_A,
      resourceType: "vendor_assurance_document",
      resourceId: null,
      payload: {
        used_bytes: MAX_ORG_STORAGE_BYTES,
        limit_bytes: MAX_ORG_STORAGE_BYTES,
        document_count: 120
      }
    });
  });
});

// ---------------------------------------------------------------------------
// list / get document
// ---------------------------------------------------------------------------

describe("listVendorAssuranceDocuments", () => {
  it("403 without org context", async () => {
    const req = buildReq({ organizationContext: undefined });
    const { res, status } = buildRes();
    await listVendorAssuranceDocuments(req as never, res as never);
    expect(status).toHaveBeenCalledWith(403);
  });

  it("scopes WHERE by organization_id", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 0, rows: [] });
    const req = buildReq();
    const { res } = buildRes();
    await listVendorAssuranceDocuments(req as never, res as never);
    const sql = String(pgQuerySpy.mock.calls[0]?.[0] ?? "");
    const params = pgQuerySpy.mock.calls[0]?.[1] as unknown[];
    expect(sql).toMatch(/organization_id = \$1/);
    expect(params?.[0]).toBe(ORG_A);
  });

  it("rejects bad status filter", async () => {
    const req = buildReq({ query: { status: "lol" } });
    const { res, status } = buildRes();
    await listVendorAssuranceDocuments(req as never, res as never);
    expect(status).toHaveBeenCalledWith(400);
  });
});

describe("getVendorAssuranceDocument", () => {
  it("404 cross-org", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 0, rows: [] });
    const req = buildReq({ params: { id: DOC_ID } });
    const { res, status, json } = buildRes();
    await getVendorAssuranceDocument(req as never, res as never);
    expect(status).toHaveBeenCalledWith(404);
    expect(json).toHaveBeenCalledWith({ error: "vendor_assurance_document_not_found" });
  });

  it("rejects non-UUID document id", async () => {
    const req = buildReq({ params: { id: "x" } });
    const { res, status } = buildRes();
    await getVendorAssuranceDocument(req as never, res as never);
    expect(status).toHaveBeenCalledWith(400);
  });
});

// ---------------------------------------------------------------------------
// PDF URL
// ---------------------------------------------------------------------------

describe("getVendorAssurancePdfRedirect", () => {
  it("404 when document is cross-org; never issues a URL", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 0, rows: [] });
    const req = buildReq({ params: { id: DOC_ID }, organizationContext: { organizationId: ORG_B } });
    const { res, status, redirect } = buildRes();
    await getVendorAssurancePdfRedirect(req as never, res as never);
    expect(status).toHaveBeenCalledWith(404);
    expect(redirect).not.toHaveBeenCalled();
    expect(getVendorAssurancePdfSignedUrlSpy).not.toHaveBeenCalled();
    const auditCalls = (writeAuditEvent as unknown as ReturnType<typeof vi.fn>).mock.calls;
    expect(auditCalls.some((c) => c[0]?.eventType === "vendor_assurance.document.pdf_url_issued")).toBe(false);
  });

  it("redirects 302 and audits issuance on success", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 1, rows: [{ "?column?": 1 }] });
    getVendorAssurancePdfSignedUrlSpy.mockResolvedValueOnce({
      url: "https://signed.example/abc",
      ttlSeconds: 60,
      expiresAt: new Date()
    });
    const req = buildReq({ params: { id: DOC_ID } });
    const { res, redirect } = buildRes();
    await getVendorAssurancePdfRedirect(req as never, res as never);
    expect(redirect).toHaveBeenCalledWith(302, "https://signed.example/abc");
    const auditCalls = (writeAuditEvent as unknown as ReturnType<typeof vi.fn>).mock.calls;
    expect(auditCalls.some((c) => c[0]?.eventType === "vendor_assurance.document.pdf_url_issued")).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// extraction read (DISTINCT ON projection)
// ---------------------------------------------------------------------------

describe("getVendorAssuranceExtraction", () => {
  it("404 when document is cross-org", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 0, rows: [] });
    const req = buildReq({ params: { id: DOC_ID } });
    const { res, status } = buildRes();
    await getVendorAssuranceExtraction(req as never, res as never);
    expect(status).toHaveBeenCalledWith(404);
  });

  it("returns null extraction (with empty overrides) when none exists yet", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ "?column?": 1 }] }) // doc check
      .mockResolvedValueOnce({ rowCount: 0, rows: [] }) // extraction lookup
      .mockResolvedValueOnce({ rowCount: 0, rows: [] }); // field overrides
    const req = buildReq({ params: { id: DOC_ID } });
    const { res, status, json } = buildRes();
    await getVendorAssuranceExtraction(req as never, res as never);
    expect(status).toHaveBeenCalledWith(200);
    const body = json.mock.calls[0]?.[0] as Record<string, unknown>;
    expect(body["extraction"]).toBeNull();
    expect(body["spans"]).toEqual([]);
    expect(body["current_decisions"]).toEqual({});
    expect(body["field_overrides"]).toEqual([]);
  });

  it("uses the DISTINCT ON read projections for current_decisions and field_overrides", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ "?column?": 1 }] }) // doc check
      .mockResolvedValueOnce({
        rowCount: 1,
        rows: [{ id: EXTRACTION_ID, organization_id: ORG_A, document_id: DOC_ID,
                 model_id: "m", prompt_version: "v", raw_response_excerpt: null,
                 fields: {}, created_at: "x" }]
      })
      .mockResolvedValueOnce({ // field overrides
        rowCount: 1,
        rows: [{
          field_name: "auditor_name", original_value: "Old LLP", override_value: "New LLP",
          reason: "Corrected per cover page", overridden_by_user_id: USER_ID, overridden_at: "2026-05-12T00:00:00Z"
        }]
      })
      .mockResolvedValueOnce({ rowCount: 0, rows: [] }) // spans
      .mockResolvedValueOnce({
        rowCount: 1,
        rows: [{
          field_name: "vendor_name", decision: "accept", reviewed_value: null,
          reviewer_note: null, decided_by_user_id: USER_ID,
          decided_at: "2026-05-08T00:00:00Z", id: "x"
        }]
      });
    const req = buildReq({ params: { id: DOC_ID } });
    const { res, json } = buildRes();
    await getVendorAssuranceExtraction(req as never, res as never);

    const overridesCall = pgQuerySpy.mock.calls[2]?.[0] as string;
    expect(overridesCall).toMatch(/FROM vendor_assurance_field_overrides/);
    expect(overridesCall).toMatch(/DISTINCT ON \(field_name\)/);
    expect(overridesCall).toMatch(/ORDER BY field_name, overridden_at DESC, id DESC/);

    const projectionCall = pgQuerySpy.mock.calls[4]?.[0] as string;
    expect(projectionCall).toMatch(/DISTINCT ON \(field_name\)/);
    expect(projectionCall).toMatch(/ORDER BY field_name, decided_at DESC, id DESC/);

    const body = json.mock.calls[0]?.[0] as Record<string, unknown>;
    expect(body["current_decisions"]).toMatchObject({ vendor_name: { decision: "accept" } });
    expect(body["field_overrides"]).toEqual([
      expect.objectContaining({ field_name: "auditor_name", override_value: "New LLP" })
    ]);
  });
});

// ---------------------------------------------------------------------------
// review-decisions: append-only INSERT
// ---------------------------------------------------------------------------

describe("recordVendorAssuranceReviewDecisions", () => {
  it("rejects unknown field_name", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 1, rows: [{ document_id: DOC_ID }] });
    const req = buildReq({
      params: { id: EXTRACTION_ID },
      body: { decisions: [{ field_name: "not_a_field", decision: "accept" }] }
    });
    const { res, status } = buildRes();
    await recordVendorAssuranceReviewDecisions(req as never, res as never);
    expect(status).toHaveBeenCalledWith(400);
  });

  it("404 when extraction is cross-org", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 0, rows: [] });
    const req = buildReq({
      params: { id: EXTRACTION_ID },
      body: { decisions: [{ field_name: "vendor_name", decision: "accept" }] }
    });
    const { res, status } = buildRes();
    await recordVendorAssuranceReviewDecisions(req as never, res as never);
    expect(status).toHaveBeenCalledWith(404);
  });

  it("INSERTs a new row (no UPSERT) and audits each decision", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ document_id: DOC_ID }] }) // extraction lookup
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ processing_status: "extracted" }] }); // doc status
    pgConnectClientQuerySpy
      .mockResolvedValueOnce({}) // BEGIN
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: "new-1" }] }) // INSERT
      .mockResolvedValueOnce({}); // COMMIT
    pgQuerySpy.mockResolvedValueOnce({
      rowCount: 1,
      rows: [{
        field_name: "vendor_name", decision: "accept", reviewed_value: null,
        reviewer_note: null, decided_by_user_id: USER_ID, decided_at: "x"
      }]
    });

    const req = buildReq({
      params: { id: EXTRACTION_ID },
      body: { decisions: [{ field_name: "vendor_name", decision: "accept" }] }
    });
    const { res, status, json } = buildRes();
    await recordVendorAssuranceReviewDecisions(req as never, res as never);

    expect(status).toHaveBeenCalledWith(200);
    // The decision write must be INSERT, not UPSERT — confirm no ON CONFLICT clause.
    const insertCall = pgConnectClientQuerySpy.mock.calls[1]?.[0] as string;
    expect(insertCall).toMatch(/INSERT INTO vendor_assurance_review_decisions/);
    expect(insertCall).not.toMatch(/ON CONFLICT/i);
    expect(insertCall).not.toMatch(/UPDATE/i);

    const body = json.mock.calls[0]?.[0] as Record<string, unknown>;
    expect(body["inserted_ids"]).toEqual(["new-1"]);

    const auditCalls = (writeAuditEvent as unknown as ReturnType<typeof vi.fn>).mock.calls;
    expect(auditCalls.some((c) => c[0]?.eventType === "vendor_assurance.review_decision.recorded")).toBe(true);
  });

  it("appends a second row when re-deciding the same field", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ document_id: DOC_ID }] })
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ processing_status: "extracted" }] });
    pgConnectClientQuerySpy
      .mockResolvedValueOnce({}) // BEGIN
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: "new-2" }] }) // INSERT
      .mockResolvedValueOnce({}); // COMMIT
    pgQuerySpy.mockResolvedValueOnce({
      rowCount: 1,
      rows: [{
        field_name: "vendor_name", decision: "edit",
        reviewed_value: { value: "Acme" },
        reviewer_note: null, decided_by_user_id: USER_ID, decided_at: "x"
      }]
    });
    const req = buildReq({
      params: { id: EXTRACTION_ID },
      body: { decisions: [{ field_name: "vendor_name", decision: "edit", reviewed_value: { value: "Acme" } }] }
    });
    const { res, status } = buildRes();
    await recordVendorAssuranceReviewDecisions(req as never, res as never);
    expect(status).toHaveBeenCalledWith(200);
    // Only one INSERT call inside the transaction.
    const insertCalls = pgConnectClientQuerySpy.mock.calls.filter(
      (c) => typeof c[0] === "string" && (c[0] as string).match(/INSERT INTO vendor_assurance_review_decisions/)
    );
    expect(insertCalls).toHaveLength(1);
  });

  it("409 when document is finalized", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ document_id: DOC_ID }] })
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ processing_status: "finalized" }] });
    const req = buildReq({
      params: { id: EXTRACTION_ID },
      body: { decisions: [{ field_name: "vendor_name", decision: "accept" }] }
    });
    const { res, status, json } = buildRes();
    await recordVendorAssuranceReviewDecisions(req as never, res as never);
    expect(status).toHaveBeenCalledWith(409);
    expect(json).toHaveBeenCalledWith({ error: "vendor_assurance_document_finalized" });
  });
});

// ---------------------------------------------------------------------------
// finalize
// ---------------------------------------------------------------------------

describe("finalizeVendorAssuranceDocument", () => {
  it("404 cross-org", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 0, rows: [] });
    const req = buildReq({ params: { id: DOC_ID } });
    const { res, status } = buildRes();
    await finalizeVendorAssuranceDocument(req as never, res as never);
    expect(status).toHaveBeenCalledWith(404);
  });

  it("409 when already finalized", async () => {
    pgQuerySpy.mockResolvedValueOnce({
      rowCount: 1,
      rows: [{ id: DOC_ID, processing_status: "finalized" }]
    });
    const req = buildReq({ params: { id: DOC_ID } });
    const { res, status, json } = buildRes();
    await finalizeVendorAssuranceDocument(req as never, res as never);
    expect(status).toHaveBeenCalledWith(409);
    expect(json).toHaveBeenCalledWith({ error: "vendor_assurance_document_already_finalized" });
  });

  it("409 when status is not 'extracted'", async () => {
    pgQuerySpy.mockResolvedValueOnce({
      rowCount: 1,
      rows: [{ id: DOC_ID, processing_status: "extracting" }]
    });
    const req = buildReq({ params: { id: DOC_ID } });
    const { res, status } = buildRes();
    await finalizeVendorAssuranceDocument(req as never, res as never);
    expect(status).toHaveBeenCalledWith(409);
  });

  it("409 when material fields lack a current decision", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "extracted" }] }) // doc
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: EXTRACTION_ID }] }) // extraction
      .mockResolvedValueOnce({ rowCount: 0, rows: [] }); // projection: nothing decided
    const req = buildReq({ params: { id: DOC_ID } });
    const { res, status, json } = buildRes();
    await finalizeVendorAssuranceDocument(req as never, res as never);
    expect(status).toHaveBeenCalledWith(409);
    const body = json.mock.calls[0]?.[0] as { error: string; missing_field_names: string[] };
    expect(body.error).toBe("vendor_assurance_finalize_blocked");
    expect(body.missing_field_names.length).toBe(MATERIAL_FIELD_NAMES.length);
  });

  it("200 when all material fields decided; audits + sets finalized state", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "extracted" }] })
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: EXTRACTION_ID }] })
      .mockResolvedValueOnce({
        rowCount: MATERIAL_FIELD_NAMES.length,
        rows: MATERIAL_FIELD_NAMES.map((n) => ({ field_name: n, decision: "accept" }))
      })
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "finalized" }] }); // UPDATE

    const req = buildReq({ params: { id: DOC_ID } });
    const { res, status } = buildRes();
    await finalizeVendorAssuranceDocument(req as never, res as never);
    expect(status).toHaveBeenCalledWith(200);
    const auditCalls = (writeAuditEvent as unknown as ReturnType<typeof vi.fn>).mock.calls;
    expect(auditCalls.some((c) => c[0]?.eventType === "vendor_assurance.document.finalized")).toBe(true);
  });

  it("409 idempotent re-call (UPDATE returns 0 rows due to the WHERE precondition)", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "extracted" }] })
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: EXTRACTION_ID }] })
      .mockResolvedValueOnce({
        rowCount: MATERIAL_FIELD_NAMES.length,
        rows: MATERIAL_FIELD_NAMES.map((n) => ({ field_name: n, decision: "accept" }))
      })
      .mockResolvedValueOnce({ rowCount: 0, rows: [] }); // UPDATE lost race
    const req = buildReq({ params: { id: DOC_ID } });
    const { res, status, json } = buildRes();
    await finalizeVendorAssuranceDocument(req as never, res as never);
    expect(status).toHaveBeenCalledWith(409);
    expect(json).toHaveBeenCalledWith({ error: "vendor_assurance_document_already_finalized" });
  });
});

// ---------------------------------------------------------------------------
// document-presentation package: field overrides
// ---------------------------------------------------------------------------

describe("recordVendorAssuranceFieldOverride", () => {
  it("403 without org context", async () => {
    const req = buildReq({ organizationContext: undefined, params: { id: DOC_ID } });
    const { res, status } = buildRes();
    await recordVendorAssuranceFieldOverride(req as never, res as never);
    expect(status).toHaveBeenCalledWith(403);
  });

  it("400 on unknown field_name (validator) — no DB access", async () => {
    const req = buildReq({
      params: { id: DOC_ID },
      body: { field_name: "not_a_field", override_value: "x", reason: "r" }
    });
    const { res, status, json } = buildRes();
    await recordVendorAssuranceFieldOverride(req as never, res as never);
    expect(status).toHaveBeenCalledWith(400);
    expect(json.mock.calls[0]?.[0]).toMatchObject({ error: "unknown_field_name" });
    expect(pgQuerySpy).not.toHaveBeenCalled();
  });

  it("400 when reason is blank", async () => {
    const req = buildReq({
      params: { id: DOC_ID },
      body: { field_name: "vendor_name", override_value: "Acme", reason: "   " }
    });
    const { res, status, json } = buildRes();
    await recordVendorAssuranceFieldOverride(req as never, res as never);
    expect(status).toHaveBeenCalledWith(400);
    expect(json.mock.calls[0]?.[0]).toMatchObject({ error: "reason_required" });
  });

  it("400 when reason is null", async () => {
    const req = buildReq({
      params: { id: DOC_ID },
      body: { field_name: "vendor_name", override_value: "Acme", reason: null }
    });
    const { res, status, json } = buildRes();
    await recordVendorAssuranceFieldOverride(req as never, res as never);
    expect(status).toHaveBeenCalledWith(400);
    expect(json.mock.calls[0]?.[0]).toMatchObject({ error: "reason_required" });
  });

  it("400 when override_value key is absent", async () => {
    const req = buildReq({
      params: { id: DOC_ID },
      body: { field_name: "vendor_name", reason: "r" }
    });
    const { res, status, json } = buildRes();
    await recordVendorAssuranceFieldOverride(req as never, res as never);
    expect(status).toHaveBeenCalledWith(400);
    expect(json.mock.calls[0]?.[0]).toMatchObject({ error: "override_value_required" });
  });

  it("404 when document is cross-org; never inserts", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 0, rows: [] }); // doc lookup
    const req = buildReq({
      params: { id: DOC_ID },
      organizationContext: { organizationId: ORG_B },
      body: { field_name: "vendor_name", override_value: "Acme", reason: "r" }
    });
    const { res, status, json } = buildRes();
    await recordVendorAssuranceFieldOverride(req as never, res as never);
    expect(status).toHaveBeenCalledWith(404);
    expect(json).toHaveBeenCalledWith({ error: "vendor_assurance_document_not_found" });
    // only the doc lookup ran; no extraction read, no INSERT
    expect(pgQuerySpy).toHaveBeenCalledTimes(1);
    const auditCalls = (writeAuditEvent as unknown as ReturnType<typeof vi.fn>).mock.calls;
    expect(auditCalls.some((c) => c[0]?.eventType === "vendor_assurance.field.overridden")).toBe(false);
  });

  it("409 when document is rejected", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "rejected" }] });
    const req = buildReq({
      params: { id: DOC_ID },
      body: { field_name: "vendor_name", override_value: "Acme", reason: "r" }
    });
    const { res, status, json } = buildRes();
    await recordVendorAssuranceFieldOverride(req as never, res as never);
    expect(status).toHaveBeenCalledWith(409);
    expect(json.mock.calls[0]?.[0]).toMatchObject({ error: "vendor_assurance_document_not_overridable", status: "rejected" });
  });

  it("409 when document is approved (locked — version of record)", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "approved" }] });
    const req = buildReq({
      params: { id: DOC_ID },
      body: { field_name: "vendor_name", override_value: "Acme", reason: "r" }
    });
    const { res, status, json } = buildRes();
    await recordVendorAssuranceFieldOverride(req as never, res as never);
    expect(status).toHaveBeenCalledWith(409);
    expect(json.mock.calls[0]?.[0]).toMatchObject({ error: "vendor_assurance_document_not_overridable", status: "approved" });
    expect(pgQuerySpy).toHaveBeenCalledTimes(1); // refused before any prior-override / extraction read
  });

  it("409 when document is finalized (legacy state)", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "finalized" }] });
    const req = buildReq({
      params: { id: DOC_ID },
      body: { field_name: "vendor_name", override_value: "Acme", reason: "r" }
    });
    const { res, status } = buildRes();
    await recordVendorAssuranceFieldOverride(req as never, res as never);
    expect(status).toHaveBeenCalledWith(409);
  });

  it("allows overrides while in manual_review_requested state", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "manual_review_requested" }] }) // doc
      .mockResolvedValueOnce({ rowCount: 0, rows: [] }) // no prior override
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ fields: { vendor_name: { value: "Old", confidence: 0.9, status: "extracted" } } }] }) // extraction
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: "ov-mr", overridden_at: "2026-05-12T00:00:00Z" }] }); // INSERT
    const req = buildReq({
      params: { id: DOC_ID },
      body: { field_name: "vendor_name", override_value: "New", reason: "human reviewer correction" }
    });
    const { res, status } = buildRes();
    await recordVendorAssuranceFieldOverride(req as never, res as never);
    expect(status).toHaveBeenCalledWith(201);
  });

  it("409 when no extraction exists and there is no prior override", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "extracted" }] }) // doc
      .mockResolvedValueOnce({ rowCount: 0, rows: [] }) // no prior override
      .mockResolvedValueOnce({ rowCount: 0, rows: [] }); // extraction missing
    const req = buildReq({
      params: { id: DOC_ID },
      body: { field_name: "vendor_name", override_value: "Acme", reason: "r" }
    });
    const { res, status, json } = buildRes();
    await recordVendorAssuranceFieldOverride(req as never, res as never);
    expect(status).toHaveBeenCalledWith(409);
    expect(json.mock.calls[0]?.[0]).toMatchObject({ error: "vendor_assurance_extraction_missing" });
  });

  it("happy path: captures original_value from the extraction (no prior override), INSERTs (no UPSERT), audits, returns 201", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "extracted" }] }) // doc
      .mockResolvedValueOnce({ rowCount: 0, rows: [] }) // no prior override
      .mockResolvedValueOnce({
        rowCount: 1,
        rows: [{ fields: { vendor_name: { value: "Old Corp", confidence: 0.9, status: "extracted" } } }]
      }) // extraction
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: "ov-1", overridden_at: "2026-05-12T00:00:00Z" }] }); // INSERT

    const req = buildReq({
      params: { id: DOC_ID },
      body: { field_name: "vendor_name", override_value: "New Corp Inc", reason: "Legal name on cover page" }
    });
    const { res, status, json } = buildRes();
    await recordVendorAssuranceFieldOverride(req as never, res as never);

    expect(status).toHaveBeenCalledWith(201);

    const insertCall = pgQuerySpy.mock.calls[3];
    const insertSql = insertCall?.[0] as string;
    const insertParams = insertCall?.[1] as unknown[];
    expect(insertSql).toMatch(/INSERT INTO vendor_assurance_field_overrides/);
    expect(insertSql).not.toMatch(/ON CONFLICT/i);
    expect(insertParams[0]).toBe(ORG_A);
    expect(insertParams[1]).toBe(DOC_ID);
    expect(insertParams[2]).toBe("vendor_name");
    expect(insertParams[3]).toBe(JSON.stringify("Old Corp"));     // original_value, captured from the extraction
    expect(insertParams[4]).toBe(JSON.stringify("New Corp Inc")); // override_value
    expect(insertParams[5]).toBe("Legal name on cover page");     // reason

    const auditCalls = (writeAuditEvent as unknown as ReturnType<typeof vi.fn>).mock.calls;
    const overrideAudit = auditCalls.find((c) => c[0]?.eventType === "vendor_assurance.field.overridden");
    expect(overrideAudit).toBeDefined();
    expect(overrideAudit?.[0]?.resourceId).toBe(DOC_ID);
    expect(overrideAudit?.[0]?.payload).toMatchObject({
      field_name: "vendor_name",
      original_value: "Old Corp",
      override_value: "New Corp Inc",
      reason: "Legal name on cover page"
    });

    const body = json.mock.calls[0]?.[0] as { override: Record<string, unknown> };
    expect(body.override).toMatchObject({ id: "ov-1", field_name: "vendor_name", original_value: "Old Corp" });
  });

  it("captures original_value from the prior override on a second override of the same field", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "extracted" }] }) // doc
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ override_value: "First Override Value" }] }) // PRIOR override exists
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: "ov-2", overridden_at: "2026-05-12T01:00:00Z" }] }); // INSERT

    const req = buildReq({
      params: { id: DOC_ID },
      body: { field_name: "vendor_name", override_value: "Second Override Value", reason: "second correction" }
    });
    const { res, status } = buildRes();
    await recordVendorAssuranceFieldOverride(req as never, res as never);

    expect(status).toHaveBeenCalledWith(201);
    // The extraction is NOT read when a prior override exists: doc + prior-override + INSERT only.
    expect(pgQuerySpy).toHaveBeenCalledTimes(3);

    const insertParams = pgQuerySpy.mock.calls[2]?.[1] as unknown[];
    expect(insertParams[3]).toBe(JSON.stringify("First Override Value"));  // original_value = prior override value, NOT the extraction value
    expect(insertParams[4]).toBe(JSON.stringify("Second Override Value")); // override_value = the new value

    const auditCalls = (writeAuditEvent as unknown as ReturnType<typeof vi.fn>).mock.calls;
    const overrideAudit = auditCalls.find((c) => c[0]?.eventType === "vendor_assurance.field.overridden");
    expect(overrideAudit?.[0]?.payload).toMatchObject({
      field_name: "vendor_name",
      original_value: "First Override Value",
      override_value: "Second Override Value"
    });
  });

  it("happy path: original_value is null when the field was not extracted and there is no prior override", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "extracted" }] }) // doc
      .mockResolvedValueOnce({ rowCount: 0, rows: [] }) // no prior override
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ fields: {} }] }) // extraction, no such field
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: "ov-3", overridden_at: "2026-05-12T00:00:00Z" }] }); // INSERT
    const req = buildReq({
      params: { id: DOC_ID },
      body: { field_name: "auditor_name", override_value: "Some LLP", reason: "Model missed it" }
    });
    const { res, status } = buildRes();
    await recordVendorAssuranceFieldOverride(req as never, res as never);
    expect(status).toHaveBeenCalledWith(201);
    const insertParams = pgQuerySpy.mock.calls[3]?.[1] as unknown[];
    expect(insertParams[3]).toBeNull(); // original_value bound as SQL NULL
  });
});

// ---------------------------------------------------------------------------
// document-presentation package: document-level transitions
// ---------------------------------------------------------------------------

describe("approveVendorAssuranceDocument", () => {
  it("404 cross-org", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 0, rows: [] });
    const req = buildReq({ params: { id: DOC_ID } });
    const { res, status } = buildRes();
    await approveVendorAssuranceDocument(req as never, res as never);
    expect(status).toHaveBeenCalledWith(404);
  });

  it("400 on non-UUID document id", async () => {
    const req = buildReq({ params: { id: "nope" } });
    const { res, status } = buildRes();
    await approveVendorAssuranceDocument(req as never, res as never);
    expect(status).toHaveBeenCalledWith(400);
  });

  it("409 when document is not in 'extracted' state", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "pending" }] });
    const req = buildReq({ params: { id: DOC_ID } });
    const { res, status, json } = buildRes();
    await approveVendorAssuranceDocument(req as never, res as never);
    expect(status).toHaveBeenCalledWith(409);
    expect(json.mock.calls[0]?.[0]).toMatchObject({ error: "vendor_assurance_document_not_extracted", status: "pending" });
  });

  it("409 on lost race (UPDATE matches 0 rows)", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "extracted" }] })
      .mockResolvedValueOnce({ rowCount: 0, rows: [] });
    const req = buildReq({ params: { id: DOC_ID } });
    const { res, status } = buildRes();
    await approveVendorAssuranceDocument(req as never, res as never);
    expect(status).toHaveBeenCalledWith(409);
  });

  it("200 happy path: sets approved + approved_at, audits vendor_assurance.document.approved", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "extracted" }] })
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "approved" }] }); // UPDATE
    const req = buildReq({ params: { id: DOC_ID } });
    const { res, status, json } = buildRes();
    await approveVendorAssuranceDocument(req as never, res as never);
    expect(status).toHaveBeenCalledWith(200);
    const updateSql = pgQuerySpy.mock.calls[1]?.[0] as string;
    expect(updateSql).toMatch(/processing_status = \$3/);
    expect(updateSql).toMatch(/approved_at = NOW\(\)/);
    expect(updateSql).toMatch(/AND processing_status = 'extracted'/);
    expect((pgQuerySpy.mock.calls[1]?.[1] as unknown[])[2]).toBe("approved");
    const auditCalls = (writeAuditEvent as unknown as ReturnType<typeof vi.fn>).mock.calls;
    expect(auditCalls.some((c) => c[0]?.eventType === "vendor_assurance.document.approved")).toBe(true);
    const body = json.mock.calls[0]?.[0] as { document: { processing_status: string } };
    expect(body.document.processing_status).toBe("approved");
  });
});

describe("requestVendorAssuranceManualReview", () => {
  it("400 when comment is not a string", async () => {
    const req = buildReq({ params: { id: DOC_ID }, body: { comment: 123 } });
    const { res, status, json } = buildRes();
    await requestVendorAssuranceManualReview(req as never, res as never);
    expect(status).toHaveBeenCalledWith(400);
    expect(json.mock.calls[0]?.[0]).toMatchObject({ error: "comment_must_be_string" });
    expect(pgQuerySpy).not.toHaveBeenCalled();
  });

  it("404 cross-org", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 0, rows: [] });
    const req = buildReq({ params: { id: DOC_ID }, body: {} });
    const { res, status } = buildRes();
    await requestVendorAssuranceManualReview(req as never, res as never);
    expect(status).toHaveBeenCalledWith(404);
  });

  it("409 when not in 'extracted' state", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "approved" }] });
    const req = buildReq({ params: { id: DOC_ID }, body: {} });
    const { res, status } = buildRes();
    await requestVendorAssuranceManualReview(req as never, res as never);
    expect(status).toHaveBeenCalledWith(409);
  });

  it("200 happy path: sets manual_review_requested, does NOT touch approved_at, audits with comment", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "extracted" }] })
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "manual_review_requested" }] });
    const req = buildReq({ params: { id: DOC_ID }, body: { comment: "Needs a human pass on the exceptions table" } });
    const { res, status } = buildRes();
    await requestVendorAssuranceManualReview(req as never, res as never);
    expect(status).toHaveBeenCalledWith(200);
    const updateSql = pgQuerySpy.mock.calls[1]?.[0] as string;
    // The non-approve transitions must not write approved_at in the SET clause
    // (approved_at still appears in the RETURNING DOC_SELECT column list).
    expect(updateSql).not.toMatch(/approved_at = NOW\(\)/);
    expect((pgQuerySpy.mock.calls[1]?.[1] as unknown[])[2]).toBe("manual_review_requested");
    const auditCalls = (writeAuditEvent as unknown as ReturnType<typeof vi.fn>).mock.calls;
    const ev = auditCalls.find((c) => c[0]?.eventType === "vendor_assurance.document.manual_review_requested");
    expect(ev).toBeDefined();
    expect(ev?.[0]?.payload).toMatchObject({ comment: "Needs a human pass on the exceptions table" });
  });
});

describe("rejectVendorAssuranceDocument", () => {
  it("400 when reason is empty", async () => {
    const req = buildReq({ params: { id: DOC_ID }, body: { reason: "" } });
    const { res, status, json } = buildRes();
    await rejectVendorAssuranceDocument(req as never, res as never);
    expect(status).toHaveBeenCalledWith(400);
    expect(json.mock.calls[0]?.[0]).toMatchObject({ error: "reason_required" });
    expect(pgQuerySpy).not.toHaveBeenCalled();
  });

  it("400 when reason is missing", async () => {
    const req = buildReq({ params: { id: DOC_ID }, body: {} });
    const { res, status } = buildRes();
    await rejectVendorAssuranceDocument(req as never, res as never);
    expect(status).toHaveBeenCalledWith(400);
  });

  it("404 cross-org", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 0, rows: [] });
    const req = buildReq({ params: { id: DOC_ID }, body: { reason: "low quality" } });
    const { res, status } = buildRes();
    await rejectVendorAssuranceDocument(req as never, res as never);
    expect(status).toHaveBeenCalledWith(404);
  });

  it("409 when not in 'extracted' state", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "rejected" }] });
    const req = buildReq({ params: { id: DOC_ID }, body: { reason: "low quality" } });
    const { res, status } = buildRes();
    await rejectVendorAssuranceDocument(req as never, res as never);
    expect(status).toHaveBeenCalledWith(409);
  });

  it("200 happy path: sets rejected, audits with reason", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "extracted" }] })
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "rejected" }] });
    const req = buildReq({ params: { id: DOC_ID }, body: { reason: "extraction quality too low to rely on" } });
    const { res, status } = buildRes();
    await rejectVendorAssuranceDocument(req as never, res as never);
    expect(status).toHaveBeenCalledWith(200);
    expect((pgQuerySpy.mock.calls[1]?.[1] as unknown[])[2]).toBe("rejected");
    const auditCalls = (writeAuditEvent as unknown as ReturnType<typeof vi.fn>).mock.calls;
    const ev = auditCalls.find((c) => c[0]?.eventType === "vendor_assurance.document.rejected");
    expect(ev).toBeDefined();
    expect(ev?.[0]?.payload).toMatchObject({ reason: "extraction quality too low to rely on" });
  });
});

// ---------------------------------------------------------------------------
// CUEC matcher package: GET .../cuecs
// ---------------------------------------------------------------------------

describe("getVendorAssuranceCuecs", () => {
  it("403 without org context", async () => {
    const req = buildReq({ organizationContext: undefined, params: { id: DOC_ID } });
    const { res, status } = buildRes();
    await getVendorAssuranceCuecs(req as never, res as never);
    expect(status).toHaveBeenCalledWith(403);
  });

  it("400 on non-UUID document id", async () => {
    const req = buildReq({ params: { id: "nope" } });
    const { res, status } = buildRes();
    await getVendorAssuranceCuecs(req as never, res as never);
    expect(status).toHaveBeenCalledWith(400);
  });

  it("404 when document is cross-org", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 0, rows: [] }); // doc check
    const req = buildReq({ params: { id: DOC_ID }, organizationContext: { organizationId: ORG_B } });
    const { res, status, json } = buildRes();
    await getVendorAssuranceCuecs(req as never, res as never);
    expect(status).toHaveBeenCalledWith(404);
    expect(json).toHaveBeenCalledWith({ error: "vendor_assurance_document_not_found" });
  });

  it("200 returns cuecs with mappings joined to control name + the score-band constants", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ "?column?": 1 }] }) // doc check
      .mockResolvedValueOnce({ rows: [cuecRow()] }) // cuecs
      .mockResolvedValueOnce({ rows: [mappingRow()] }); // mappings
    const req = buildReq({ params: { id: DOC_ID } });
    const { res, status, json } = buildRes();
    await getVendorAssuranceCuecs(req as never, res as never);
    expect(status).toHaveBeenCalledWith(200);
    const body = json.mock.calls[0]?.[0] as Record<string, unknown>;
    expect(body["document_id"]).toBe(DOC_ID);
    expect(body["match_score_min_threshold"]).toBe(60);
    expect(body["match_score_high_confidence"]).toBe(85);
    const cuecs = body["cuecs"] as Array<Record<string, unknown>>;
    expect(cuecs).toHaveLength(1);
    const mappings = cuecs[0]?.["mappings"] as Array<Record<string, unknown>>;
    expect(mappings).toHaveLength(1);
    expect(mappings[0]?.["control_name"]).toBe("Physical Access Control");
  });
});

// ---------------------------------------------------------------------------
// CUEC matcher package: POST .../rematch-cuecs
// ---------------------------------------------------------------------------

describe("rematchVendorAssuranceCuecs", () => {
  it("404 cross-org", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 0, rows: [] });
    const req = buildReq({ params: { id: DOC_ID } });
    const { res, status } = buildRes();
    await rematchVendorAssuranceCuecs(req as never, res as never);
    expect(status).toHaveBeenCalledWith(404);
    expect(refreshCuecMappingsForDocumentSpy).not.toHaveBeenCalled();
  });

  it("200 happy path: re-runs the matcher WITHOUT resync when cuec rows already exist, audits, returns the new cuecs", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ "?column?": 1 }] }) // doc check
      .mockResolvedValueOnce({ rows: [{ n: "3" }] }) // cuec row count
      .mockResolvedValueOnce({ rows: [cuecRow()] }) // load cuecs
      .mockResolvedValueOnce({ rows: [mappingRow({ mapping_status: "suggested" })] }); // load mappings
    const req = buildReq({ params: { id: DOC_ID } });
    const { res, status, json } = buildRes();
    await rematchVendorAssuranceCuecs(req as never, res as never);
    expect(status).toHaveBeenCalledWith(200);
    expect(refreshCuecMappingsForDocumentSpy).toHaveBeenCalledWith(DOC_ID, ORG_A, { resyncRows: false });
    const auditCalls = (writeAuditEvent as unknown as ReturnType<typeof vi.fn>).mock.calls;
    expect(auditCalls.some((c) => c[0]?.eventType === "vendor_assurance.cuecs.rematched")).toBe(true);
    const body = json.mock.calls[0]?.[0] as Record<string, unknown>;
    expect(body["result"]).toMatchObject({ matched: true });
    expect((body["cuecs"] as unknown[]).length).toBe(1);
  });

  it("200 bootstrap: re-syncs cuec rows from the extraction when none exist yet", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ "?column?": 1 }] }) // doc check
      .mockResolvedValueOnce({ rows: [{ n: "0" }] }) // cuec row count = 0
      .mockResolvedValueOnce({ rows: [] }) // load cuecs (after refresh — mocked, returns []) 
      ; // (no mappings query because no cuec rows in the loadCuecsWithMappings result)
    const req = buildReq({ params: { id: DOC_ID } });
    const { res, status } = buildRes();
    await rematchVendorAssuranceCuecs(req as never, res as never);
    expect(status).toHaveBeenCalledWith(200);
    expect(refreshCuecMappingsForDocumentSpy).toHaveBeenCalledWith(DOC_ID, ORG_A, { resyncRows: true });
  });

  it("500 when the matcher throws", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ "?column?": 1 }] }) // doc check
      .mockResolvedValueOnce({ rows: [{ n: "0" }] }); // cuec row count
    refreshCuecMappingsForDocumentSpy.mockRejectedValueOnce(new Error("boom"));
    const req = buildReq({ params: { id: DOC_ID } });
    const { res, status, json } = buildRes();
    await rematchVendorAssuranceCuecs(req as never, res as never);
    expect(status).toHaveBeenCalledWith(500);
    expect(json).toHaveBeenCalledWith({ error: "cuec_rematch_failed" });
  });
});

// ---------------------------------------------------------------------------
// CUEC matcher package: POST /cuecs/:id/mappings (manual create)
// ---------------------------------------------------------------------------

describe("createVendorAssuranceCuecMapping", () => {
  it("400 on bad body (no control_id)", async () => {
    const req = buildReq({ params: { cuecId: CUEC_ID }, body: {} });
    const { res, status, json } = buildRes();
    await createVendorAssuranceCuecMapping(req as never, res as never);
    expect(status).toHaveBeenCalledWith(400);
    expect(json.mock.calls[0]?.[0]).toMatchObject({ error: "control_id_must_be_uuid" });
    expect(pgQuerySpy).not.toHaveBeenCalled();
  });

  it("404 when the cuec is cross-org", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 0, rows: [] }); // cuec check
    const req = buildReq({ params: { cuecId: CUEC_ID }, body: { control_id: CONTROL_ID } });
    const { res, status, json } = buildRes();
    await createVendorAssuranceCuecMapping(req as never, res as never);
    expect(status).toHaveBeenCalledWith(404);
    expect(json.mock.calls[0]?.[0]).toMatchObject({ error: "vendor_assurance_cuec_not_found" });
  });

  it("404 when the control does not belong to the org", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ document_id: DOC_ID }] }) // cuec check
      .mockResolvedValueOnce({ rowCount: 0, rows: [] }); // control check
    const req = buildReq({ params: { cuecId: CUEC_ID }, body: { control_id: CONTROL_ID } });
    const { res, status, json } = buildRes();
    await createVendorAssuranceCuecMapping(req as never, res as never);
    expect(status).toHaveBeenCalledWith(404);
    expect(json.mock.calls[0]?.[0]).toMatchObject({ error: "control_not_found" });
  });

  it("201 creates a manual accepted mapping, audits vendor_assurance.cuec_mapping.created", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ document_id: DOC_ID }] }) // cuec check
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ "?column?": 1 }] }) // control check
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: "map-new" }] }) // INSERT ... ON CONFLICT
      .mockResolvedValueOnce({ rows: [mappingRow({ id: "map-new", mapping_status: "accepted", mapping_source: "manual", mapping_score: null })] }); // fetch joined
    const req = buildReq({ params: { cuecId: CUEC_ID }, body: { control_id: CONTROL_ID, reason: "we operate this directly" } });
    const { res, status, json } = buildRes();
    await createVendorAssuranceCuecMapping(req as never, res as never);
    expect(status).toHaveBeenCalledWith(201);
    const insertSql = pgQuerySpy.mock.calls[2]?.[0] as string;
    expect(insertSql).toMatch(/INSERT INTO vendor_assurance_cuec_control_mappings/);
    expect(insertSql).toMatch(/'accepted', NULL, 'manual'/);
    expect(insertSql).toMatch(/ON CONFLICT \(cuec_id, control_id\) DO UPDATE/);
    const auditCalls = (writeAuditEvent as unknown as ReturnType<typeof vi.fn>).mock.calls;
    expect(auditCalls.some((c) => c[0]?.eventType === "vendor_assurance.cuec_mapping.created")).toBe(true);
    const body = json.mock.calls[0]?.[0] as { mapping: Record<string, unknown> };
    expect(body.mapping.mapping_status).toBe("accepted");
  });

  it("409 when the (cuec, control) pair was previously dismissed (ON CONFLICT update matched 0 rows)", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ document_id: DOC_ID }] }) // cuec check
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ "?column?": 1 }] }) // control check
      .mockResolvedValueOnce({ rowCount: 0, rows: [] }); // INSERT ... ON CONFLICT DO UPDATE WHERE != dismissed → 0 rows
    const req = buildReq({ params: { cuecId: CUEC_ID }, body: { control_id: CONTROL_ID } });
    const { res, status, json } = buildRes();
    await createVendorAssuranceCuecMapping(req as never, res as never);
    expect(status).toHaveBeenCalledWith(409);
    expect(json.mock.calls[0]?.[0]).toMatchObject({ error: "vendor_assurance_cuec_mapping_dismissed" });
  });
});

// ---------------------------------------------------------------------------
// CUEC matcher package: PATCH /cuec-mappings/:id (accept / dismiss)
// ---------------------------------------------------------------------------

describe("updateVendorAssuranceCuecMapping", () => {
  it("400 on a non-target mapping_status (e.g. 'suggested')", async () => {
    const req = buildReq({ params: { mappingId: MAPPING_ID }, body: { mapping_status: "suggested" } });
    const { res, status, json } = buildRes();
    await updateVendorAssuranceCuecMapping(req as never, res as never);
    expect(status).toHaveBeenCalledWith(400);
    expect(json.mock.calls[0]?.[0]).toMatchObject({ error: "invalid_mapping_status" });
  });

  it("400 when dismissing without a reason", async () => {
    const req = buildReq({ params: { mappingId: MAPPING_ID }, body: { mapping_status: "dismissed" } });
    const { res, status, json } = buildRes();
    await updateVendorAssuranceCuecMapping(req as never, res as never);
    expect(status).toHaveBeenCalledWith(400);
    expect(json.mock.calls[0]?.[0]).toMatchObject({ error: "reason_required_for_dismissed" });
  });

  it("404 when the mapping is cross-org", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 0, rows: [] }); // cur lookup
    const req = buildReq({ params: { mappingId: MAPPING_ID }, body: { mapping_status: "accepted" } });
    const { res, status } = buildRes();
    await updateVendorAssuranceCuecMapping(req as never, res as never);
    expect(status).toHaveBeenCalledWith(404);
  });

  it("200 idempotent self-transition (accepted → accepted) makes no UPDATE, no audit", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ cuec_id: "cuec-0", control_id: "ctl-a", mapping_status: "accepted", document_id: DOC_ID }] }) // cur
      .mockResolvedValueOnce({ rows: [mappingRow({ mapping_status: "accepted" })] }); // fetch joined
    const req = buildReq({ params: { mappingId: MAPPING_ID }, body: { mapping_status: "accepted" } });
    const { res, status } = buildRes();
    await updateVendorAssuranceCuecMapping(req as never, res as never);
    expect(status).toHaveBeenCalledWith(200);
    // only cur + fetch — no UPDATE in between
    expect(pgQuerySpy).toHaveBeenCalledTimes(2);
    const auditCalls = (writeAuditEvent as unknown as ReturnType<typeof vi.fn>).mock.calls;
    expect(auditCalls.some((c) => c[0]?.eventType === "vendor_assurance.cuec_mapping.updated")).toBe(false);
  });

  it("409 on an illegal transition (dismissed → accepted)", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 1, rows: [{ cuec_id: "cuec-0", control_id: "ctl-a", mapping_status: "dismissed", document_id: DOC_ID }] }); // cur
    const req = buildReq({ params: { mappingId: MAPPING_ID }, body: { mapping_status: "accepted" } });
    const { res, status, json } = buildRes();
    await updateVendorAssuranceCuecMapping(req as never, res as never);
    expect(status).toHaveBeenCalledWith(409);
    expect(json.mock.calls[0]?.[0]).toMatchObject({ error: "invalid_cuec_mapping_transition", from: "dismissed", to: "accepted" });
  });

  it("200 accept a suggested mapping, audits with from/to", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ cuec_id: "cuec-0", control_id: "ctl-a", mapping_status: "suggested", document_id: DOC_ID }] }) // cur
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: "map-1" }] }) // UPDATE
      .mockResolvedValueOnce({ rows: [mappingRow({ mapping_status: "accepted" })] }); // fetch joined
    const req = buildReq({ params: { mappingId: MAPPING_ID }, body: { mapping_status: "accepted" } });
    const { res, status } = buildRes();
    await updateVendorAssuranceCuecMapping(req as never, res as never);
    expect(status).toHaveBeenCalledWith(200);
    const updParams = pgQuerySpy.mock.calls[1]?.[1] as unknown[];
    expect(updParams[2]).toBe("accepted"); // new status
    expect(updParams[3]).toBeNull(); // reason cleared on accept
    expect(updParams[5]).toBe("suggested"); // observed status re-asserted
    const auditCalls = (writeAuditEvent as unknown as ReturnType<typeof vi.fn>).mock.calls;
    const ev = auditCalls.find((c) => c[0]?.eventType === "vendor_assurance.cuec_mapping.updated");
    expect(ev?.[0]?.payload).toMatchObject({ from: "suggested", to: "accepted" });
  });

  it("200 dismiss an accepted mapping with a reason; reason persisted", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ cuec_id: "cuec-0", control_id: "ctl-a", mapping_status: "accepted", document_id: DOC_ID }] }) // cur
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: "map-1" }] }) // UPDATE
      .mockResolvedValueOnce({ rows: [mappingRow({ mapping_status: "dismissed", reason: "control doesn't actually cover this" })] }); // fetch joined
    const req = buildReq({ params: { mappingId: MAPPING_ID }, body: { mapping_status: "dismissed", reason: "control doesn't actually cover this" } });
    const { res, status } = buildRes();
    await updateVendorAssuranceCuecMapping(req as never, res as never);
    expect(status).toHaveBeenCalledWith(200);
    const updParams = pgQuerySpy.mock.calls[1]?.[1] as unknown[];
    expect(updParams[2]).toBe("dismissed");
    expect(updParams[3]).toBe("control doesn't actually cover this");
  });

  it("409 on a lost race (UPDATE matched 0 rows)", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ cuec_id: "cuec-0", control_id: "ctl-a", mapping_status: "suggested", document_id: DOC_ID }] }) // cur
      .mockResolvedValueOnce({ rowCount: 0, rows: [] }); // UPDATE — status changed under us
    const req = buildReq({ params: { mappingId: MAPPING_ID }, body: { mapping_status: "accepted" } });
    const { res, status } = buildRes();
    await updateVendorAssuranceCuecMapping(req as never, res as never);
    expect(status).toHaveBeenCalledWith(409);
  });
});

// ---------------------------------------------------------------------------
// CUEC matcher package: POST /cuecs/:id/review-status
// ---------------------------------------------------------------------------

describe("updateVendorAssuranceCuecReviewStatus", () => {
  it("400 on a bad review_status", async () => {
    const req = buildReq({ params: { cuecId: CUEC_ID }, body: { review_status: "bogus" } });
    const { res, status, json } = buildRes();
    await updateVendorAssuranceCuecReviewStatus(req as never, res as never);
    expect(status).toHaveBeenCalledWith(400);
    expect(json.mock.calls[0]?.[0]).toMatchObject({ error: "invalid_review_status" });
  });

  it("404 when the cuec is cross-org", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 0, rows: [] }); // cur lookup
    const req = buildReq({ params: { cuecId: CUEC_ID }, body: { review_status: "reviewed_no_match" } });
    const { res, status } = buildRes();
    await updateVendorAssuranceCuecReviewStatus(req as never, res as never);
    expect(status).toHaveBeenCalledWith(404);
  });

  it("200 set reviewed_no_match (with reason); audits vendor_assurance.cuec.review_status_updated", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ document_id: DOC_ID }] }) // cur
      .mockResolvedValueOnce({ rowCount: 1, rows: [cuecRow({ review_status: "reviewed_no_match", review_status_reason: "we outsource this", review_status_updated_by_user_id: USER_ID, review_status_updated_at: "2026-05-12T01:00:00Z" })] }); // UPDATE
    const req = buildReq({ params: { cuecId: CUEC_ID }, body: { review_status: "reviewed_no_match", reason: "we outsource this" } });
    const { res, status, json } = buildRes();
    await updateVendorAssuranceCuecReviewStatus(req as never, res as never);
    expect(status).toHaveBeenCalledWith(200);
    const updSql = pgQuerySpy.mock.calls[1]?.[0] as string;
    expect(updSql).toMatch(/review_status = 'reviewed_no_match'/);
    expect(pgQuerySpy.mock.calls[1]?.[1]).toEqual([CUEC_ID, ORG_A, "we outsource this", USER_ID]);
    const auditCalls = (writeAuditEvent as unknown as ReturnType<typeof vi.fn>).mock.calls;
    const ev = auditCalls.find((c) => c[0]?.eventType === "vendor_assurance.cuec.review_status_updated");
    expect(ev?.[0]?.payload).toMatchObject({ review_status: "reviewed_no_match" });
    const body = json.mock.calls[0]?.[0] as { cuec: Record<string, unknown> };
    expect(body.cuec.review_status).toBe("reviewed_no_match");
  });

  it("200 clear back to pending (drops reason/by/at; params are [cuecId, org] only)", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ document_id: DOC_ID }] }) // cur
      .mockResolvedValueOnce({ rowCount: 1, rows: [cuecRow({ review_status: "pending" })] }); // UPDATE
    const req = buildReq({ params: { cuecId: CUEC_ID }, body: { review_status: "pending", reason: "ignored" } });
    const { res, status } = buildRes();
    await updateVendorAssuranceCuecReviewStatus(req as never, res as never);
    expect(status).toHaveBeenCalledWith(200);
    const updSql = pgQuerySpy.mock.calls[1]?.[0] as string;
    expect(updSql).toMatch(/review_status = 'pending'/);
    expect(pgQuerySpy.mock.calls[1]?.[1]).toEqual([CUEC_ID, ORG_A]);
  });
});

// ---------------------------------------------------------------------------
// CUEC matcher package: cuecs field-override re-trigger
// ---------------------------------------------------------------------------

describe("recordVendorAssuranceFieldOverride — cuecs re-match trigger", () => {
  it("schedules a CUEC re-match (resyncRows: true) when field_name === 'cuecs'", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "extracted" }] }) // doc
      .mockResolvedValueOnce({ rowCount: 0, rows: [] }) // no prior override
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ fields: { cuecs: { value: ["a", "b"] } } }] }) // extraction
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: "ov-1", overridden_at: "2026-05-12T00:00:00Z" }] }); // INSERT
    const req = buildReq({ params: { id: DOC_ID }, body: { field_name: "cuecs", override_value: ["x", "y"], reason: "corrected CUEC list" } });
    const { res, status } = buildRes();
    await recordVendorAssuranceFieldOverride(req as never, res as never);
    expect(status).toHaveBeenCalledWith(201);
    // let the setImmediate fire
    await new Promise<void>((r) => setImmediate(r));
    expect(refreshCuecMappingsForDocumentSpy).toHaveBeenCalledWith(DOC_ID, ORG_A, { resyncRows: true });
  });

  it("does NOT schedule a CUEC re-match for a non-cuecs field override", async () => {
    pgQuerySpy
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: DOC_ID, processing_status: "extracted" }] }) // doc
      .mockResolvedValueOnce({ rowCount: 0, rows: [] }) // no prior override
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ fields: { vendor_name: { value: "Old" } } }] }) // extraction
      .mockResolvedValueOnce({ rowCount: 1, rows: [{ id: "ov-2", overridden_at: "2026-05-12T00:00:00Z" }] }); // INSERT
    const req = buildReq({ params: { id: DOC_ID }, body: { field_name: "vendor_name", override_value: "New", reason: "fix" } });
    const { res, status } = buildRes();
    await recordVendorAssuranceFieldOverride(req as never, res as never);
    expect(status).toHaveBeenCalledWith(201);
    await new Promise<void>((r) => setImmediate(r));
    expect(refreshCuecMappingsForDocumentSpy).not.toHaveBeenCalled();
  });
});

// ---------------------------------------------------------------------------
// export routes — POST .../:id/export.xlsx and .../:id/export.pdf
// ---------------------------------------------------------------------------

describe("exportVendorAssuranceDocument (xlsx / pdf)", () => {
  const EXPORTABLE_STATUSES = ["extracted", "manual_review_requested", "approved", "rejected", "finalized"];
  const NON_EXPORTABLE_STATUSES = ["pending", "extracting", "extraction_failed"];

  beforeEach(() => {
    buildExportBundleSpy.mockReset();
    buildWorkbookBufferSpy.mockReset();
    buildPdfSpy.mockReset();
    // A truthy bundle is enough — the route only forwards it to the (mocked) builders / filename helpers.
    buildExportBundleSpy.mockResolvedValue({ report: { vendorName: "Acme Cloud", reportPeriodEnd: "2025-09-30", reportIssuedDate: null } });
    buildWorkbookBufferSpy.mockResolvedValue(Buffer.from("XLSX-BYTES"));
    buildPdfSpy.mockResolvedValue(Buffer.from("%PDF-1.7\n%fake"));
  });

  it("403 when organization context is missing (xlsx)", async () => {
    const req = buildReq({ organizationContext: undefined, params: { id: DOC_ID } });
    const { res, status, json } = buildRes();
    await exportVendorAssuranceDocumentXlsx(req as never, res as never);
    expect(status).toHaveBeenCalledWith(403);
    expect(json).toHaveBeenCalledWith({ error: "organization_context_missing" });
  });

  it("400 when the document id is not a uuid (pdf)", async () => {
    const req = buildReq({ params: { id: "not-a-uuid" } });
    const { res, status, json } = buildRes();
    await exportVendorAssuranceDocumentPdf(req as never, res as never);
    expect(status).toHaveBeenCalledWith(400);
    expect(json).toHaveBeenCalledWith({ error: "document_id_must_be_uuid" });
  });

  it("404 when the document belongs to another org (xlsx) — no bundle build, no audit", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 0, rows: [] }); // gate query: not found in this org
    const req = buildReq({ params: { id: DOC_ID } });
    const { res, status, json } = buildRes();
    await exportVendorAssuranceDocumentXlsx(req as never, res as never);
    expect(status).toHaveBeenCalledWith(404);
    expect(json).toHaveBeenCalledWith({ error: "vendor_assurance_document_not_found" });
    expect(buildExportBundleSpy).not.toHaveBeenCalled();
    expect(writeAuditEvent).not.toHaveBeenCalled();
  });

  it.each(NON_EXPORTABLE_STATUSES)("409 vendor_assurance_document_not_exportable when status=%s (pdf)", async (st) => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 1, rows: [{ processing_status: st }] });
    const req = buildReq({ params: { id: DOC_ID } });
    const { res, status, json } = buildRes();
    await exportVendorAssuranceDocumentPdf(req as never, res as never);
    expect(status).toHaveBeenCalledWith(409);
    expect(json).toHaveBeenCalledWith({ error: "vendor_assurance_document_not_exportable", status: st });
    expect(buildExportBundleSpy).not.toHaveBeenCalled();
    expect(writeAuditEvent).not.toHaveBeenCalled();
  });

  it.each(EXPORTABLE_STATUSES)("xlsx happy path when status=%s: streams the workbook + headers + audit { format: 'xlsx' }", async (st) => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 1, rows: [{ processing_status: st }] });
    const req = buildReq({ params: { id: DOC_ID } });
    const { res, status, send, setHeader } = buildRes();
    await exportVendorAssuranceDocumentXlsx(req as never, res as never);
    expect(buildExportBundleSpy).toHaveBeenCalledWith(DOC_ID, ORG_A, { exportedByUserId: USER_ID });
    expect(setHeader).toHaveBeenCalledWith("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
    expect(setHeader).toHaveBeenCalledWith("Content-Disposition", expect.stringMatching(/^attachment; filename="[^"]+\.xlsx"$/));
    expect(setHeader).toHaveBeenCalledWith("Cache-Control", "private, no-store, max-age=0");
    expect(status).toHaveBeenCalledWith(200);
    const sentArg = send.mock.calls[0]?.[0];
    expect(Buffer.isBuffer(sentArg)).toBe(true);
    expect(writeAuditEvent).toHaveBeenCalledWith(expect.objectContaining({
      organizationId: ORG_A,
      eventType: "vendor_assurance.document.exported",
      resourceType: "vendor_assurance_document",
      resourceId: DOC_ID,
      payload: { format: "xlsx" }
    }));
  });

  it("pdf happy path (approved): streams the PDF bytes + headers + audit { format: 'pdf' }", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 1, rows: [{ processing_status: "approved" }] });
    const req = buildReq({ params: { id: DOC_ID } });
    const { res, status, send, setHeader } = buildRes();
    await exportVendorAssuranceDocumentPdf(req as never, res as never);
    expect(buildPdfSpy).toHaveBeenCalled();
    expect(setHeader).toHaveBeenCalledWith("Content-Type", "application/pdf");
    expect(setHeader).toHaveBeenCalledWith("Content-Disposition", expect.stringMatching(/^attachment; filename="[^"]+\.pdf"$/));
    expect(status).toHaveBeenCalledWith(200);
    const sentArg = send.mock.calls[0]?.[0] as Buffer;
    expect(Buffer.isBuffer(sentArg)).toBe(true);
    expect(sentArg.subarray(0, 5).toString("ascii")).toBe("%PDF-");
    expect(writeAuditEvent).toHaveBeenCalledWith(expect.objectContaining({
      eventType: "vendor_assurance.document.exported",
      payload: { format: "pdf" }
    }));
  });

  it("500 export_failed and no audit when the bundle build throws (pdf)", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 1, rows: [{ processing_status: "approved" }] });
    buildExportBundleSpy.mockRejectedValueOnce(new Error("boom"));
    const req = buildReq({ params: { id: DOC_ID } });
    const { res, status, json } = buildRes();
    await exportVendorAssuranceDocumentPdf(req as never, res as never);
    expect(status).toHaveBeenCalledWith(500);
    expect(json).toHaveBeenCalledWith({ error: "export_failed" });
    expect(writeAuditEvent).not.toHaveBeenCalled();
  });

  it("404 when the document vanished between the gate query and the bundle load (xlsx)", async () => {
    pgQuerySpy.mockResolvedValueOnce({ rowCount: 1, rows: [{ processing_status: "approved" }] });
    buildExportBundleSpy.mockResolvedValueOnce(null);
    const req = buildReq({ params: { id: DOC_ID } });
    const { res, status, json } = buildRes();
    await exportVendorAssuranceDocumentXlsx(req as never, res as never);
    expect(status).toHaveBeenCalledWith(404);
    expect(json).toHaveBeenCalledWith({ error: "vendor_assurance_document_not_found" });
    expect(writeAuditEvent).not.toHaveBeenCalled();
  });
});
