import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";

export function generateAuditSprintPdf(reportId: string, data: any): string {
  const outputDir = path.join(process.cwd(), "reports");
  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir);

  const filePath = path.join(outputDir, `${reportId}.pdf`);
  const doc = new PDFDocument({ margin: 50 });
  doc.pipe(fs.createWriteStream(filePath));

  const footer = () => {
    doc.fontSize(8)
      .fillColor("gray")
      .text(
        "Confidential — Generated by SecureLogic AI (Enterprise Edition)",
        50,
        doc.page.height - 40,
        { align: "center" }
      )
      .fillColor("black");
  };

  // ---- COVER ----
  doc.fontSize(22).text("SecureLogic AI", { align: "center" });
  doc.moveDown();
  doc.fontSize(16).text("Enterprise AI Risk Assessment", { align: "center" });
  doc.moveDown(2);
  doc.fontSize(10).text(`Report ID: ${reportId}`, { align: "center" });
  doc.text(`Generated: ${new Date().toISOString()}`, { align: "center" });
  footer();
  doc.addPage();

  // ---- EXEC SUMMARY ----
  doc.fontSize(16).text("Executive Summary");
  doc.moveDown();
  doc.fontSize(12).text(`Overall Risk: ${data.executiveSummary.overallRisk}`);
  if (data.executiveSummary.enterpriseRiskScore !== null) {
    doc.text(`Enterprise Risk Score: ${data.executiveSummary.enterpriseRiskScore}`);
  }
  doc.moveDown();
  doc.text(data.executiveSummary.narrative);
  footer();
  doc.addPage();

  // ---- ENTERPRISE OVERVIEW ----
  if (data.enterpriseOverview) {
    doc.fontSize(16).text("Enterprise Risk Overview");
    doc.moveDown();
    doc.text(`Severity: ${data.enterpriseOverview.severity}`);
    doc.moveDown();

    data.enterpriseOverview.topRiskDrivers?.forEach((r: string) =>
      doc.text(`• ${r}`)
    );

    doc.moveDown();
    data.enterpriseOverview.severityRationale?.forEach((r: string) =>
      doc.text(`• ${r}`)
    );

    footer();
    doc.addPage();
  }

  // ---- MATERIAL RISKS ----
  if (data.materialRisks?.length) {
    doc.fontSize(16).text("Material Risks");
    doc.moveDown();

    data.materialRisks.forEach((risk: any) => {
      doc.fontSize(12).text(`${risk.title} (${risk.severity})`);
      doc.fontSize(10).text(risk.whyItMatters);
      doc.moveDown();
    });

    footer();
    doc.addPage();
  }

  // ---- DISCLAIMERS ----
  doc.fontSize(10).text("Disclaimers");
  doc.moveDown();
  data.disclaimers?.forEach((d: string) => doc.text(`• ${d}`));
  footer();

  doc.end();
  return filePath;
}