"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateAuditSprintPdf = generateAuditSprintPdf;
var pdfkit_1 = require("pdfkit");
var fs_1 = require("fs");
var path_1 = require("path");
function generateAuditSprintPdf(reportId, data) {
    var _a, _b, _c, _d;
    var outputDir = path_1.default.join(process.cwd(), "reports");
    if (!fs_1.default.existsSync(outputDir))
        fs_1.default.mkdirSync(outputDir);
    var filePath = path_1.default.join(outputDir, "".concat(reportId, ".pdf"));
    var doc = new pdfkit_1.default({ margin: 50 });
    doc.pipe(fs_1.default.createWriteStream(filePath));
    var footer = function () {
        doc.fontSize(8)
            .fillColor("gray")
            .text("Confidential — Generated by SecureLogic AI (Enterprise Edition)", 50, doc.page.height - 40, { align: "center" })
            .fillColor("black");
    };
    // ---- COVER ----
    doc.fontSize(22).text("SecureLogic AI", { align: "center" });
    doc.moveDown();
    doc.fontSize(16).text("Enterprise AI Risk Assessment", { align: "center" });
    doc.moveDown(2);
    doc.fontSize(10).text("Report ID: ".concat(reportId), { align: "center" });
    doc.text("Generated: ".concat(new Date().toISOString()), { align: "center" });
    footer();
    doc.addPage();
    // ---- EXEC SUMMARY ----
    doc.fontSize(16).text("Executive Summary");
    doc.moveDown();
    doc.fontSize(12).text("Overall Risk: ".concat(data.executiveSummary.overallRisk));
    if (data.executiveSummary.enterpriseRiskScore !== null) {
        doc.text("Enterprise Risk Score: ".concat(data.executiveSummary.enterpriseRiskScore));
    }
    doc.moveDown();
    doc.text(data.executiveSummary.narrative);
    footer();
    doc.addPage();
    // ---- ENTERPRISE OVERVIEW ----
    if (data.enterpriseOverview) {
        doc.fontSize(16).text("Enterprise Risk Overview");
        doc.moveDown();
        doc.text("Severity: ".concat(data.enterpriseOverview.severity));
        doc.moveDown();
        (_a = data.enterpriseOverview.topRiskDrivers) === null || _a === void 0 ? void 0 : _a.forEach(function (r) {
            return doc.text("\u2022 ".concat(r));
        });
        doc.moveDown();
        (_b = data.enterpriseOverview.severityRationale) === null || _b === void 0 ? void 0 : _b.forEach(function (r) {
            return doc.text("\u2022 ".concat(r));
        });
        footer();
        doc.addPage();
    }
    // ---- MATERIAL RISKS ----
    if ((_c = data.materialRisks) === null || _c === void 0 ? void 0 : _c.length) {
        doc.fontSize(16).text("Material Risks");
        doc.moveDown();
        data.materialRisks.forEach(function (risk) {
            doc.fontSize(12).text("".concat(risk.title, " (").concat(risk.severity, ")"));
            doc.fontSize(10).text(risk.whyItMatters);
            doc.moveDown();
        });
        footer();
        doc.addPage();
    }
    // ---- DISCLAIMERS ----
    doc.fontSize(10).text("Disclaimers");
    doc.moveDown();
    (_d = data.disclaimers) === null || _d === void 0 ? void 0 : _d.forEach(function (d) { return doc.text("\u2022 ".concat(d)); });
    footer();
    doc.end();
    return filePath;
}
