export enum EnginePhase {
  LOAD_BUNDLE = "LOAD_BUNDLE",
  VALIDATE_BUNDLE = "VALIDATE_BUNDLE",
  EXECUTE_POLICIES = "EXECUTE_POLICIES",
  AGGREGATE_RESULTS = "AGGREGATE_RESULTS",
  FINALIZE_DECISION = "FINALIZE_DECISION"
}