/**
 * dataClassification.ts — runtime constants for the GDPR/CCPA Data Subject
 * Rights workstream (GDPR Arts. 15 / 17 / 20 + CCPA equivalents).
 *
 * SOURCE OF TRUTH: docs/DATA_CLASSIFICATION.md. This file is the machine-
 * readable mirror of that document so future PRs (the export engine — PR #2,
 * and the deletion reaper — PR #6) can reference the classification
 * programmatically instead of re-parsing markdown. Keep the two in sync; the
 * test src/api/__tests__/dataClassification.test.ts asserts this file stays
 * complete against the live migration schema.
 *
 * REFERENCE-ONLY IN PR #1: nothing in the current codebase imports this module.
 * It exists to be reviewed now and consumed by later PRs.
 *
 * Category definitions (see DATA_CLASSIFICATION.md §"Category definitions"):
 *   A — User PII root (the user record itself).
 *   B — User-scoped data (lives and dies with the user; ON DELETE CASCADE).
 *   C — Org content authored by a user (anonymize the actor reference on delete).
 *   D — Org data not tied to a specific user (leave alone on user delete).
 *   E — System-wide / operational (leave alone).
 *   F — Billing / financial (special legal-retention handling).
 *
 * rlsStatus reflects A04-G1 (the mid-flight Postgres RLS rollout), so the
 * reaper / export engine know which tables already enforce row-level security
 * (and therefore need the elevated/owner channel for legitimate cross-org work):
 *   'enabled' — ENABLE ROW LEVEL SECURITY + tenant policy is live in the DB now.
 *   'pending' — Tier A customer-data table that WILL get a policy in A04-G1 but
 *               does not have one yet.
 *   'none'    — system-wide / Tier B/C/D table; no per-org RLS policy planned.
 */

export type DataCategory = "A" | "B" | "C" | "D" | "E" | "F";
export type PiiRisk = "high" | "medium" | "low" | "none";
export type RlsStatus = "enabled" | "pending" | "none";

export interface TableClassification {
  category: DataCategory;
  /** Columns that reference a specific user (FK to users.id or user-id text). */
  userRefColumns?: string[];
  piiRisk: PiiRisk;
  rlsStatus: RlsStatus;
  /**
   * Email-keyed export inclusion (Decision Q6). A handful of Category-E tables
   * key personal data by EMAIL ADDRESS rather than a users.id FK
   * (`subscribers`, `intelligence_brief_subscribers`, `newsletter_deliveries`).
   * They are STILL category 'E' for deletion (leave alone — a subscriber is an
   * email, not necessarily a platform user), but a user's Art. 15 self-export
   * MUST include the rows matching the requester's CURRENT email. This flag
   * marks that "delete=leave, export=include-by-email" distinction so the export
   * engine includes them and the reaper still skips them.
   *
   * NOT set on `email_suppressions`: that table is excluded from both delete and
   * export (Decision O-8 — removing/exposing a suppression risks re-enabling mail
   * to a bounced/complained address).
   *
   * Historical email matching is NOT supported (no email history is tracked) —
   * only the subject's current `users.email` is matched. Mirrored in the
   * DATA_CLASSIFICATION.md export-format section.
   */
  exportByEmailOnly?: boolean;
  /**
   * Columns that physically exist on the table but MUST NOT appear in a data
   * export — credentials, capability tokens, and their expiry companions. The
   * export engine projects an explicit column allowlist (every column EXCEPT
   * these) instead of `SELECT *` for any table that sets this; a missing column
   * list for such a table is a hard error (it refuses to fall back to `SELECT *`).
   *
   * This is the EXPORT-side mirror of `TOMBSTONE_USER_PATCH`, but a SEPARATE
   * field on purpose: deletion and export concerns differ. Tombstone scrubs a
   * column's VALUE in place on delete (Art. 17) while keeping the column; export
   * OMITS the column entirely from the Art. 15 copy. A column can need one,
   * the other, or both — e.g. `users.email` is tombstone-scrubbed but MUST be
   * exported (it is the subject's own data), whereas `users.password_hash` is
   * both scrubbed on delete AND excluded from export. Keeping the lists distinct
   * prevents one concern silently dictating the other.
   *
   * NOT a substitute for the free-text PII manual-review process (O-7).
   */
  exportExcludedColumns?: string[];
  /** Notes that the reaper / export engine must respect for this table. */
  specialHandling?: string;
}

/**
 * Per-table classification. Every table created by a file in db/migrations/
 * MUST have an entry here — enforced by dataClassification.test.ts.
 *
 * Mirror of docs/DATA_CLASSIFICATION.md §"Per-table classification".
 */
export const TABLE_CLASSIFICATION: Record<string, TableClassification> = {
  // ── A — User PII root ──────────────────────────────────────────────────────
  users: {
    category: "A",
    piiRisk: "high",
    rlsStatus: "pending",
    // Credentials + live capability tokens (+ their expiry companions) are
    // omitted from the Art. 15 export. password_hash is a hash, but totp_secret
    // and the *_token columns are live plaintext secrets. See exportExcludedColumns.
    exportExcludedColumns: [
      "password_hash",
      "totp_secret",
      "totp_backup_codes",
      "email_verification_token",
      "email_verification_expires_at",
      "password_reset_token",
      "password_reset_expires_at",
    ],
    specialHandling:
      "TOMBSTONE on delete (O-3): never DELETE this row. Scrub PII in place via TOMBSTONE_USER_PATCH, preserve the UUID. RLS pending — users is a pre-context-auth structural prerequisite for the A04-G1 flip.",
  },

  // ── B — User-scoped data (CASCADE; dies with the user) ─────────────────────
  password_history: { category: "B", userRefColumns: ["user_id"], piiRisk: "high", rlsStatus: "pending", specialHandling: "Password hashes. CASCADE. Exclude from data export." },
  user_alert_preferences: { category: "B", userRefColumns: ["user_id"], piiRisk: "low", rlsStatus: "pending" },
  alert_sends: { category: "B", userRefColumns: ["user_id"], piiRisk: "low", rlsStatus: "pending" },
  dashboard_preferences: { category: "B", userRefColumns: ["user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "preference_type='org_default' rows have user_id NULL and are effectively category D — leave those. RLS: org_default rows still carry organization_id, so the org-scoped policy covers them." },
  briefing_layouts: { category: "B", userRefColumns: ["user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "Per-user Briefing layout envelope (Briefing Initiative B2). Whitelisted module ids only — no PII, no domain data. Reaper deletes explicitly (the users row is tombstoned, so CASCADE never fires). Excluded from the data-rights export like all preference objects." },
  legal_consents: { category: "B", userRefColumns: ["user_id"], piiRisk: "high", rlsStatus: "pending", specialHandling: "Holds ip_address + user_agent. CASCADE. NO RLS today (NOT a template — canonical RLS pattern is the findings pilot)." },
  org_invites: { category: "B", userRefColumns: ["invited_by_user_id"], piiRisk: "medium", rlsStatus: "pending", exportExcludedColumns: ["token"], specialHandling: "invited_by_user_id is ON DELETE CASCADE — under tombstone the user row is never deleted, so pending invites this user sent are preserved. `token` is a live invite-acceptance capability (UNIQUE, 7-day TTL) — excluded from export." },

  // ── C — Org content authored by a user (anonymize actor) ───────────────────
  risks: { category: "C", userRefColumns: ["owner_user_id"], piiRisk: "high", rlsStatus: "enabled" },
  risk_treatments: { category: "C", userRefColumns: ["reviewer_uuid", "owner_user_id", "reviewer_id"], piiRisk: "high", rlsStatus: "enabled", specialHandling: "Deprecated TEXT reviewer_id may hold a raw email/name — anonymize too." },
  risk_control_links: { category: "C", userRefColumns: ["created_by_user_id"], piiRisk: "low", rlsStatus: "enabled" },
  risk_obligation_links: { category: "C", userRefColumns: ["created_by_user_id"], piiRisk: "low", rlsStatus: "enabled" },
  risk_scoring_weights: { category: "C", userRefColumns: ["updated_by_user_id"], piiRisk: "none", rlsStatus: "enabled" },
  risk_settings: { category: "C", userRefColumns: ["updated_by_user_id"], piiRisk: "none", rlsStatus: "enabled" },
  controls: { category: "C", userRefColumns: ["owner_user_id"], piiRisk: "high", rlsStatus: "pending" },
  control_assessments: { category: "C", userRefColumns: ["reviewer_id"], piiRisk: "high", rlsStatus: "pending" },
  requirement_responses: { category: "C", userRefColumns: ["assessed_by"], piiRisk: "high", rlsStatus: "enabled" },
  obligations: { category: "C", userRefColumns: ["owner_user_id"], piiRisk: "high", rlsStatus: "pending" },
  obligation_assessments: { category: "C", userRefColumns: ["reviewer_uuid", "reviewer_id"], piiRisk: "high", rlsStatus: "pending", specialHandling: "Deprecated TEXT reviewer_id may hold a raw email/name." },
  asset_assessments: { category: "C", userRefColumns: ["reviewer_uuid"], piiRisk: "high", rlsStatus: "enabled" },
  vendors: { category: "C", userRefColumns: ["owner_user_id"], piiRisk: "high", rlsStatus: "enabled" },
  ask_conversations: { category: "C", userRefColumns: ["user_id"], piiRisk: "high", rlsStatus: "enabled", specialHandling: "Ask threads. USER-scoped for read, not merely org-scoped: a thread may contain data filtered to that user's seat scope and is phrased for them, so a colleague in the same org must not read it. Routes scope by user_id; RLS is the backstop. Included in the GDPR export. NOT deleted by the Art.17 self-deletion reaper: as Category C it is org content, the users row is TOMBSTONED rather than deleted so the ON DELETE CASCADE never fires, and the table is deliberately absent from CATEGORY_B_DELETE_TABLES — the earlier wording here said 'included in erasure' and promised a deletion that does not happen. RULED 2026-08-16: this is CORRECT and intended — an Ask conversation is an organization-governed record that outlives its author, preserved under the org's TDG retention policy, with the user de-identified in place by the tombstone. 20261016 replaced this table's user FK CASCADE with SET NULL so a hard delete cannot contradict that. Governed by TDG as data class 'ask_conversation' (retention, owner/administrator deletion, legal hold)." },
  ask_messages: { category: "C", userRefColumns: ["user_id"], piiRisk: "high", rlsStatus: "enabled", specialHandling: "Question and answer text plus structured claim blocks. Free text authored by a user and by the model over that user's authorized risk data — treat as customer content, never log. user_id is denormalised from the conversation so both the per-user read scope and the self-export can use a DIRECT predicate; the export query builder cannot follow a join." },
  ask_tool_invocations: { category: "E", piiRisk: "medium", rlsStatus: "enabled", specialHandling: "APPEND-ONLY audit ledger AND provenance substrate: every Ask citation points at a row here. It NOW survives the deletion of the content it describes (20261014 made message_id nullable with ON DELETE SET NULL — before that a cascade destroyed it, contradicting this very note), and expires under its own TDG class 'ask_tool_invocation' only once orphaned. Category E alongside audit_log / security_audit_log — it records what the SYSTEM did, not content the user authored, and it must survive an erasure that removes the conversation it describes (same retention-vs-erasure tension, same lawful basis). output_digest stores SHAPE (counts, ids, cited aggregates), never full tool payloads — copying those would double the blast radius of a leak for no investigative gain. Records DENIALS as well as successes." },
  ask_provenance_contexts: { category: "C", piiRisk: "high", rlsStatus: "enabled", specialHandling: "TRANSIENT hold of FULL authorized tool payloads for a deferred provenance job — the one place full tool output is ever written. ask_tool_invocations deliberately stores only a SHAPE precisely to avoid this, so the trade is made explicit and made temporary: tool_payloads is NULLED and purged_at stamped in the same transaction that attaches the claims, on every terminal path including failure. Steady state is an empty table; a populated row means work in flight, never a record. It exists so the background worker needs NO canonical read of its own — the payloads already passed the ASK-A gate for the asking user, so the worker inherits that authorization instead of re-deriving it under a broader identity. Cascades with the message on erasure." },
  retention_policies: { category: "E", userRefColumns: ["set_by_user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "NEW (TDG / E-1, 20261013). APPEND-ONLY, VERSIONED per-(org, data class) retention override. Governance configuration, not customer content: it records WHAT the organization chose to retain and for how long, never any of the retained data. No row means the platform default declared in the class registry — the default is deliberately not storable, so the table is empty at birth and needs no backfill for every org to be governed. UPDATE/DELETE/TRUNCATE blocked by trigger regardless of role (a policy history that can be rewritten cannot explain a past deletion); app_request granted SELECT,INSERT only. set_by_user_id ON DELETE SET NULL — never fires under the D-1 tombstone; durable attribution lives in the immutable security_audit_log event. RLS enabled from creation (NOT FORCE). DARK until SECURELOGIC_TENANT_DATA_GOVERNANCE_ENABLED." },
  legal_holds: { category: "E", userRefColumns: ["subject_user_id", "placed_by_user_id", "released_by_user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "NEW (TDG / E-1, 20261013). The control that OUTRANKS every deletion path — automated expiry, administrator deletion and the owner's own deletion alike. APPEND-PLUS-RELEASE at the database level: DELETE/TRUNCATE always raise, the only permitted UPDATE is active -> released, and a release may not alter the hold it releases. Separation of duties is a DB CHECK as well as a route rule: a hold can never be released by whoever placed it. Actor and subject FKs are ON DELETE SET NULL rather than NOT NULL/RESTRICT, deliberately, so this table does NOT join the D-12 cascade web that makes tenant erasure impossible. `reason` is operator-authored governance text, never customer content. RLS enabled from creation (NOT FORCE). DARK until SECURELOGIC_TENANT_DATA_GOVERNANCE_ENABLED." },
  erasure_certificates: { category: "E", piiRisk: "low", rlsStatus: "none", specialHandling: "NEW (E-2 Increment 2, 20261018). The durable proof that a governed TENANT ERASURE was authorized and performed — retained SEVEN YEARS by operator ruling. Deliberately minimal: it must prove the erasure happened without preserving any of what was erased, so it holds a bare organization UUID, a SHA-256 DIGEST of the organization name (never the name), actor UUIDs, operator-authored governance text, and row COUNTS by table. There is no column that can hold a conversation, a finding, an email or a name, and a test asserts that. Carries NO FOREIGN KEY to organizations or users — an FK would cascade the certificate away with the very subject it certifies, so the identifiers are intentionally unenforced. RLS is deliberately ABSENT rather than pending: the row must remain readable after its organization no longer exists, at which point no tenant context can be established; access control is the operator/elevated channel plus the narrow grants. Two-person authorization is a DB CHECK (approver <> requester). Append-plus-advance: DELETE and TRUNCATE raise via the shared WORM guard, and the only permitted UPDATE advances the lifecycle with the subject frozen. Excluded from the GDPR export (it is not the subject's data — it is the record that the subject's data is gone)." },
  ask_proposed_actions: { category: "C", userRefColumns: ["user_id"], piiRisk: "medium", rlsStatus: "enabled", specialHandling: "Stop Gate ASK-B proposal ledger: the model's proposed mutations, frozen tool_input and all, awaiting the USER's confirmation. tool_input/summary can embed user-directed content (an action title the user dictated), so category C with the conversation it belongs to — cascades on user erasure. token_hash is SHA-256 of a 256-bit confirmation token; the raw token exists only in the HTTP response to the proposing user's client, is minted AFTER the model loop ends, and must never be persisted, logged, or placed in model context. Confirm-path lookup is BY hash under the caller's own tenant scope (unlike the elevated-channel export tokens — org context exists before the lookup here, and must match)." },
  vendor_engagement_scope_items: { category: "C", userRefColumns: ["accepted_by_user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "The FROZEN questionnaire scope. Written once at `issued` and never rewritten — a vendor's answers are only meaningful against the questions they were actually asked. `reasons` holds a by-value rule trace that is RENDERED TO THE EXTERNAL VENDOR as 'why we're asking', so anything added to it must be safe to show a third party. ai_suggested rows are invisible to the vendor until accepted_at is set. `domain` (VA-Q2 P2, 20261062) is the closed assessment domain the item was asked under — computed by the resolver at scope-rule 1.1.0+, NULL and never backfilled on pre-Q2 rows; it is outside the question_set_hash, so the freeze is unaffected." },
  assessment_facts: { category: "C", userRefColumns: ["created_by", "accepted_by_user_id"], piiRisk: "medium", rlsStatus: "enabled", specialHandling: "THE canonical polymorphic fact store (VA-Q2 P3, 20261063, D1 Option B). A fact about a canonical subject (subject_type CLOSED allowlist — Q2: vendor_engagement; subject_id has NO FK: integrity = tenant-scoped resolver + subject-existence trigger + RLS). `value` may describe data subjects / categories / jurisdictions in the aggregate (never a person) and MUST NEVER appear in logs, audit payloads or vendor-visible text (T-13) — keys only. `source` (trust class) + `origin` (mechanism) are provenance and stay distinguishable on every read; vendor_response rows are never authoritative, ai_extraction rows are born `proposed` and reach `accepted` only through the human-accept boundary. Values are IMMUTABLE history (supersedes_id chain; no DELETE grant, no delete trigger)." },
  engagement_applicability: { category: "E", piiRisk: "low", rlsStatus: "enabled", specialHandling: "WHAT APPLIED and WHY, recorded at resolve time and IMMUTABLE (no UPDATE/DELETE grant plus the SHARED worm_guard_mutation — never a private copy, because the certified-erasure exception lives in that one function). Category E (system/security record) rather than C: it is a determination the resolver made, not authored content — there is no route that writes it and no user reference on it. `basis` holds the triggering fact VALUES and obligation titles as they were, deliberately NOT pointers, because facts supersede and obligations deactivate; those values describe the org's own posture in the aggregate, never a person. Its whole purpose (VA-926, 20261065) is that questionnaire truncation cannot erase applicability, so it must NOT be pruned, backfilled or rewritten — including by us. requirement_id is ON DELETE RESTRICT for the same reason. It records only what APPLIED: excluded/non-applicable requirements are deliberately absent (owner ruling), and whether a question represented it, whether it was truncated and whether assurance covers it are DERIVED from current state, never frozen here." },
  requirement_response_revisions: { category: "C", userRefColumns: ["answered_by_user_id"], piiRisk: "medium", rlsStatus: "enabled", specialHandling: "APPEND-ONLY answer history. Exists because the previous destructive upsert could not answer 'what did they say before they changed it', which is an audit question. Rows may be authored by an EXTERNAL vendor (responder_type='vendor', answered_via_invite_id set) rather than a platform user." },
  vendor_engagement_invites: { category: "C", userRefColumns: ["created_by_user_id", "revoked_by_user_id"], piiRisk: "high", rlsStatus: "enabled", specialHandling: "EXTERNAL TRUST BOUNDARY. Holds contact_email/contact_name for a third party who is NOT a platform user — a data subject we hold PII for without an account, so erasure requests can arrive from someone with no login. invite_token_hash is SHA-256 of a 256-bit token; the raw value exists only in the invitation email and must never be persisted or logged. Resolved on the ELEVATED channel (lookup precedes org context, like data_export_files.download_token_hash)." },
  vendor_portal_sessions: { category: "E", piiRisk: "medium", rlsStatus: "enabled", specialHandling: "Session records for an EXTERNAL, non-user principal. Category E (system/security record) rather than C: it is authentication state, not authored content, and is the audit trail for external access. Holds created_ip/last_seen_ip and a HASHED user agent — the raw UA is deliberately not stored. Resolved on the elevated channel before org context exists; everything after resolution runs inside withTenant." },
  vendor_engagement_comments: { category: "C", userRefColumns: ["author_user_id"], piiRisk: "high", rlsStatus: "enabled", specialHandling: "Two-sided thread across the EXTERNAL trust boundary. `visibility` is a confidentiality control: 'internal' rows are reviewer-only and must never be returned to a portal session — the portal read filters in SQL, and a vendor-authored row cannot be marked internal (CHECK). Vendor-authored rows have NO author_user_id; attribution is authored_via_invite_id, so the author may be a data subject with no account. Bodies are third-party free text stored VERBATIM (not escaped, not stripped) and are fed to the analysis layer, making this a prompt-injection ingress point." },
  vendor_engagements: { category: "C", userRefColumns: ["created_by_user_id", "decided_by_user_id"], piiRisk: "high", rlsStatus: "enabled", specialHandling: "The Vendor Assurance workflow spine. Holds the org's inherent/residual ratings, the frozen questionnaire scope and the governance decision — a cross-tenant read here exposes a customer's whole third-party risk posture, not one record. Scores are 0-100 HIGHER = WORSE (risk-register polarity) and must never be copied into vendors.current_risk_score, which is inverted. Reachable from an EXTERNAL vendor-portal session once Phase 3 lands, so its RLS is load-bearing rather than defence-in-depth." },
  vendor_assessments: { category: "C", userRefColumns: ["reviewer_id"], piiRisk: "high", rlsStatus: "enabled" },
  vendor_reviews: { category: "C", userRefColumns: ["reviewer_uuid", "reviewer_id"], piiRisk: "high", rlsStatus: "enabled", specialHandling: "Deprecated TEXT reviewer_id may hold a raw email/name." },
  vendor_assurance_documents: { category: "C", userRefColumns: ["uploaded_by_user_id", "finalized_by_user_id", "approved_by_user_id"], piiRisk: "medium", rlsStatus: "pending", specialHandling: "Original PDFs live in R2 under org/{orgId}/vendor-assurance/ — org-owned, included in org export, not user export." },
  vendor_assurance_cuecs: { category: "C", userRefColumns: ["review_status_updated_by_user_id"], piiRisk: "high", rlsStatus: "enabled" },
  vendor_assurance_cuec_control_mappings: { category: "C", userRefColumns: ["created_by_user_id", "updated_by_user_id"], piiRisk: "none", rlsStatus: "enabled" },
  vendor_assurance_review_decisions: { category: "C", userRefColumns: ["decided_by_user_id"], piiRisk: "high", rlsStatus: "enabled" },
  vendor_assurance_field_overrides: { category: "C", userRefColumns: ["overridden_by_user_id"], piiRisk: "high", rlsStatus: "enabled" },
  ai_systems: { category: "C", userRefColumns: ["owner_user_id"], piiRisk: "high", rlsStatus: "pending" },
  ai_governance_assessments: { category: "C", userRefColumns: ["reviewer_uuid", "reviewer_id"], piiRisk: "high", rlsStatus: "pending", specialHandling: "Deprecated TEXT reviewer_id may hold a raw email/name." },
  governance_reviews: { category: "C", userRefColumns: ["reviewer_id"], piiRisk: "high", rlsStatus: "pending" },
  ai_system_vendor_dependencies: { category: "C", userRefColumns: ["created_by_user_id"], piiRisk: "high", rlsStatus: "enabled" },
  dependency_assessments: { category: "C", userRefColumns: ["reviewer_uuid", "reviewer_id"], piiRisk: "high", rlsStatus: "enabled", specialHandling: "Deprecated TEXT reviewer_id may hold a raw email/name." },
  assessments: { category: "C", userRefColumns: ["created_by"], piiRisk: "high", rlsStatus: "enabled" },
  findings: { category: "C", userRefColumns: ["owner_user_id"], piiRisk: "high", rlsStatus: "enabled" },
  finding_review_marks: { category: "C", userRefColumns: ["user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "Per-user 'last reviewed' marker for the Decision Workspace What's-Changed zone (ERIP P3.2a). CASCADE on finding + user delete." },
  finding_saved_views: { category: "B", userRefColumns: ["user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "Per-user named filter presets for the Findings decision queue (ERIP §1 saved views). filters is a JSONB of whitelisted list-filter strings — no PII, no domain data. RECLASSIFIED C→B with the B2 GDPR rider: a purely user-scoped preference dies with the user, and the users-row CASCADE never fires (tombstone) — the reaper deletes explicitly." },
  finding_lifecycle_events: { category: "E", userRefColumns: ["actor_user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "NEW (finding-lifecycle C6). APPEND-ONLY per-finding two-axis lifecycle event stream (immutability triggers, 20260901), mirroring risk_lifecycle_events. Org-scoped (organization_id NOT NULL); RLS enabled from creation (NOT FORCE, inert until app_request flip). actor_user_id ON DELETE SET NULL. Written in-tenant-tx by findingLifecycle.ts (operational recompute + guarded decision transitions). Tier B (SELECT+INSERT)." },
  finding_risk_acceptances: { category: "E", userRefColumns: ["owner_user_id", "requested_by_user_id", "approver_user_id", "withdrawn_by_user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "NEW (finding risk-acceptance, 20260907). APPEND-ONLY durable record of a Finding risk-acceptance decision: owner, rationale, approver, approved_at, expiry. WORM — DELETE/TRUNCATE forbidden by trigger; decision content immutable once the row leaves 'proposed'; state may only advance along legal transitions. Org-scoped, RLS enabled; user refs ON DELETE SET NULL. finding_id is ON DELETE RESTRICT (not CASCADE) — a governance artifact must outlive an attempt to delete its finding. promoted_risk_id is the unused forward hook to the Risk Register. Enforcement DARK until SECURELOGIC_RISK_ACCEPTANCE_ENABLED; the table and its backfilled legacy_unverified rows exist regardless." },
  actions: { category: "C", userRefColumns: ["owner_user_id"], piiRisk: "high", rlsStatus: "pending" },
  signal_match_suggestions: { category: "C", userRefColumns: ["accepted_by_user_id", "dismissed_by_user_id"], piiRisk: "medium", rlsStatus: "enabled", specialHandling: "assessment_id (nullable, 20260730) links a suggestion to the WORM applicability_assessments decision that produced it (ECL R2 dispatcher); matcher-written rows leave it NULL. No user data in the new column. first_surfaced_at / last_surfaced_at / surface_count / last_surfaced_surface (20261025) record that the suggestion was returned to a user-facing product surface, for the Candidate C funnel — product-event metadata only: NO user id, NO session id, NO suggestion/control/vulnerability content. userRefColumns is unchanged, so these columns add no individual GDPR export or erasure obligation; they inherit this table's category C retention and its organization CASCADE for tenant erasure." },
  signal_vendor_links: { category: "C", userRefColumns: ["created_by_user_id"], piiRisk: "low", rlsStatus: "enabled" },
  signal_ai_system_links: { category: "C", userRefColumns: ["created_by_user_id"], piiRisk: "low", rlsStatus: "enabled" },
  signal_control_links: { category: "C", userRefColumns: ["created_by_user_id"], piiRisk: "low", rlsStatus: "enabled" },
  signal_obligation_links: { category: "C", userRefColumns: ["created_by_user_id"], piiRisk: "low", rlsStatus: "enabled" },
  enterprise_entities: { category: "C", userRefColumns: ["owner_user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "NEW (ECL Slice 1, Priority 5). Enterprise Context header — org-context inventory (asset/app/service/data-store names). owner_user_id ON DELETE SET NULL (never fires under tombstone O-3). Behind SECURELOGIC_ENTERPRISE_CONTEXT_ENABLED. RLS enabled from creation (NOT FORCE, inert until app_request flip). Low PII." },
  enterprise_relationships: { category: "C", userRefColumns: ["created_by_user_id"], piiRisk: "none", rlsStatus: "enabled", specialHandling: "NEW (ECL Slice 2). Generic intra-org context edge (polymorphic endpoints, no FK; soft-delete via deleted_at). created_by_user_id ON DELETE SET NULL (never fires under tombstone O-3). Behind SECURELOGIC_ENTERPRISE_CONTEXT_ENABLED. RLS enabled from creation (NOT FORCE). No PII." },
  applicability_assessments: { category: "D", piiRisk: "none", rlsStatus: "enabled", specialHandling: "NEW (ECL Slice 4b). WORM/append-only header of the applicability decision record (AD-16: by-value, hash-chained, reproducible). No user ref — signal→org decision + reasoning_steps (JSONB narration trace) + content_hash/prev_hash chain. UPDATE/DELETE/TRUNCATE blocked by trigger regardless of role; app_request granted SELECT,INSERT only. Behind SECURELOGIC_ENTERPRISE_CONTEXT_ENABLED. RLS enabled from creation (NOT FORCE). Empty until Slice 4c writer." },
  applicability_evidence: { category: "D", piiRisk: "none", rlsStatus: "enabled", specialHandling: "NEW (ECL Slice 4b). WORM by-value evidence snapshots of an applicability decision (captured_value = value at decision time; ref_id no FK). No user ref. Append-only trigger; app_request SELECT,INSERT only. Behind SECURELOGIC_ENTERPRISE_CONTEXT_ENABLED. RLS NOT FORCE. Empty until Slice 4c." },
  applicability_affected_entities: { category: "D", piiRisk: "none", rlsStatus: "enabled", specialHandling: "NEW (ECL Slice 4b). WORM normalized blast radius of an applicability decision (node_type/node_id, no FK — polymorphic). No user ref. Append-only trigger; app_request SELECT,INSERT only. Behind SECURELOGIC_ENTERPRISE_CONTEXT_ENABLED. RLS NOT FORCE. Empty until Slice 4c." },

  // ── D — Org data not tied to a specific user (leave alone on user delete) ──
  organizations: { category: "D", piiRisk: "low", rlsStatus: "none", exportExcludedColumns: ["stripe_customer_id", "stripe_subscription_id", "stripe_subscription_tier", "stripe_subscription_status", "payment_failed_at", "stripe_billing_event_at", "stripe_billing_event_id", "promo_code"], specialHandling: "ROOT-TENANT. Carries Stripe F-fields (stripe_customer_id, stripe_subscription_*, payment_failed_at, stripe_billing_event_* — the SL-BILL-1 PR-D ordering watermark, provider bookkeeping with no subject value) + promo_code with legal-retention — OMITTED from the org_full export (exportExcludedColumns, PR #2b/Q5); entitlement_level (the portable plan tier) is retained. Only touched on ORG deletion, which is out of scope for this workstream." },
  llm_control_matcher_verdicts: { category: "D", piiRisk: "none", rlsStatus: "enabled", specialHandling: "NEW (verdict cache). Idempotency cache for the LLM control matcher, keyed (organization_id, signal_dedup_hash, control_inventory_digest, prompt_version). RULED 2026-08-18: category D — ALWAYS covered by organization/tenant erasure (ON DELETE CASCADE from organizations), NEVER part of an individual's Art. 15 self-export, untouched by user deletion. That holds unconditionally because the row carries NO personal data: the payload is diagnostics only (failure_class, parse_error_code, response_sha256/response_chars) plus the verdict itself — no prompt, no control names, no response body, no signal summary; the signal is referenced by hash alone. The column set is pinned by a test, so adding a content-bearing column fails the build rather than silently invalidating this classification. Retention is the TDG governed class 'llm_verdict_cache' (storage hygiene; expiry costs a recompute, never a wrong answer). RLS enabled from creation; app_request has SELECT/INSERT/UPDATE (the matcher reads and writes it on the tenant channel) but NOT DELETE." },
  vendor_assurance_extractions: { category: "D", piiRisk: "low", rlsStatus: "enabled" },
  evidence_analysis: { category: "D", piiRisk: "low", rlsStatus: "enabled", specialHandling: "NEW (Sept-15 VA Phase 4). Advisory model verdicts (supports/insufficient/contradicts/unreadable + rationale) about a vendor's evidence document, keyed to the evidence row (CASCADE) — org data with no user ref; derived system output, never authoritative (the effectiveness ladder reads only the human confirmation). RLS enabled from creation (NOT FORCE)." },
  vendor_assurance_extraction_spans: { category: "D", piiRisk: "low", rlsStatus: "enabled" },
  vendor_tested_control_resolutions: { category: "D", piiRisk: "low", rlsStatus: "enabled", specialHandling: "NEW (VA-S4-4C-2, migration 20261073). The RECORD of a vendor tested control having been resolved against the governed canonical crosswalk at approval time: the original extraction and the governed EFFECTIVE value side by side, effective_source naming which produced it, plus the exact crosswalk row consulted and its mapping provenance. Category D — org data with NO user-reference column: the resolution is machine-produced at approval and the human act it may depend on lives in vendor_assurance_field_overrides (category C), which this table references by override_id rather than duplicating the actor. piiRisk low for the same reason as vendor_assurance_extractions — effective_control/original_control mirror the extracted control text from a vendor audit report. Supersession is by superseded_at, never mutation, so the reaper must not rewrite historical rows. Asserts a canonical identity and a governed mapping ONLY: nothing about applicability, evidence sufficiency, control effectiveness or coverage." },
  // VA-S4-4C-3 (migrations 20261075-77). The three-layer assurance outcome model.
  vendor_tested_control_assertions: { category: "D", piiRisk: "low", rlsStatus: "enabled", specialHandling: "NEW (VA-S4-4C-3, migration 20261075). LAYER 1: what the AUDITOR asserted about one vendor tested control, normalized into a closed vocabulary with the verbatim result preserved in source_text. Category D — org data with NO user-reference column, and its absence is deliberate: Layer 1 is machine-produced and carries no human authority, so a reviewer who disagrees says so in Layer 2 (vendor_tested_control_effectiveness, category C). piiRisk low for the same reason as vendor_assurance_extractions — source_text mirrors extracted control text from a vendor audit report. Append-only: superseded by superseded_at, never mutated, so the reaper must not rewrite historical rows. Asserts NOTHING about SecureLogic-governed effectiveness or coverage." },
  vendor_tested_control_effectiveness: { category: "C", userRefColumns: ["accepted_by_user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "NEW (VA-S4-4C-3, migration 20261076). LAYER 2: SecureLogic-GOVERNED effectiveness of one vendor tested control. Category C because accepted_by_user_id names the HUMAN who made the determination and an INSERT trigger makes an unattributed row impossible — the actor is the point of the record, not incidental to it. ON DELETE SET NULL on that column, so tenant erasure and user deletion stay possible; the trigger is INSERT-only for exactly that reason (20261071 precedent). Append-only: superseded, never mutated, so the reaper must not rewrite historical rows — these are human governance decisions and are NOT reproducible. ABSENCE OF A ROW IS ABSENCE OF EFFECTIVENESS." },
  vendor_assurance_exceptions: { category: "C", userRefColumns: ["effect_accepted_by_user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "NEW (VA-S4-4C-3, migration 20261077). LAYER 3: an extracted exception or deviation, WITH AN IDENTITY of its own. Category C because effect_accepted_by_user_id names the human who interpreted it (governed_effect), guarded by a transition trigger; the extracted half of the row is machine-produced. ON DELETE SET NULL on the actor column. piiRisk low — description/auditor_assessment mirror vendor audit report text. Superseded by superseded_at, never mutated; re-materialization is idempotent BY CONTENT precisely so a human interpretation is not silently discarded." },
  vendor_requirement_sufficiency_determinations: { category: "C", userRefColumns: ["determined_by_user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "NEW (VA-S4-4C-4, migration 20261079). The GOVERNED SUFFICIENCY DETERMINATION: whether one vendor assurance candidate actually supports the objective an organisation requirement represents. Category C because determined_by_user_id names the human who decided and an INSERT trigger makes an unattributed row impossible; ON DELETE SET NULL so user deletion and tenant erasure stay possible. Append-only: superseded, never mutated — these are human governance decisions and are NOT reproducible, so the reaper must not rewrite historical rows. basis holds the twelve-veto evaluation BY VALUE and is the input to the fail-closed CHECK: a SUFFICIENT row is refused unless the basis records zero fired and zero not-evaluable vetoes. There is NO override column by design. Establishes NO requirement coverage — every basis records establishes_requirement_coverage:false, enforced by CHECK. ABSENCE OF A ROW IS ABSENCE OF SUFFICIENCY." },
  vendor_assurance_exception_controls: { category: "D", piiRisk: "low", rlsStatus: "enabled", specialHandling: "NEW (VA-S4-4C-3, migration 20261077). The many-to-many link from an exception to the tested control(s) it concerns. Category D — linked_by_user_id is NULL for every extracted link and set only on the 'human' link_source, which no route writes today. Every link records link_source and the verbatim source_value it was read out of, because no heuristic may silently associate an exception with a tested control. CASCADE from vendor_assurance_exceptions." },
  frameworks: { category: "D", piiRisk: "low", rlsStatus: "pending" },
  requirements: { category: "D", piiRisk: "low", rlsStatus: "pending" },
  // VA-Q1 (ADR-0013 R1/R3): the curated vendor question library.
  questions: { category: "D", userRefColumns: ["created_by_user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "Identity of a vendor-facing question; content lives in question_versions. Mutable in status only. question_key is stable and referenced by policy rules, so it is never renamed — retire and create." },
  question_versions: { category: "D", userRefColumns: ["published_by_user_id"], piiRisk: "none", rlsStatus: "enabled", specialHandling: "IMMUTABLE content (BEFORE UPDATE OR DELETE trigger raises; app_request holds no UPDATE/DELETE grant). An issued questionnaire snapshot is addressed by these rows, so they must outlive the library edit that superseded them. Holds no PII: prompt/guidance are authored by the org or SecureLogic, never by a vendor." },
  question_requirement_links: { category: "D", userRefColumns: ["created_by_user_id"], piiRisk: "none", rlsStatus: "enabled", specialHandling: "Many-to-many lineage from a question to the canonical requirement library. Requirements carry no organization_id, so the org check on a link is a framework join in code, asserted by the isolation suite." },
  policies: { category: "D", piiRisk: "medium", rlsStatus: "pending" },
  policy_control_links: { category: "D", piiRisk: "none", rlsStatus: "pending" },
  control_mappings: { category: "D", piiRisk: "none", rlsStatus: "pending" },
  obligation_mappings: { category: "D", piiRisk: "none", rlsStatus: "pending" },
  dependencies: { category: "D", piiRisk: "medium", rlsStatus: "enabled" },
  evidence: { category: "D", piiRisk: "medium", rlsStatus: "enabled", specialHandling: "collected_by is free TEXT (not a user FK) — may embed a name/email; manual-review territory (O-7). ADR-0012 Step 2 (20261080) added valid_from/valid_until/validity_basis (what the ARTIFACT asserts, never uploaded_at + N days), supersedes_evidence_id (version chain; currency is derived at read, there is no superseded_by column to go stale) and assurance_class (the axis the Step 3 validity policy keys on, orthogonal to evidence_type/form and source_type/origin). No backfill was run: every pre-existing row carries validity_basis='not_established' and assurance_class='unclassified' by owner direction, so an unknown history fails closed instead of being inferred. supersedes_evidence_id is ON DELETE RESTRICT and tenant-locality is trigger-enforced (a version chain must not cross an org boundary)." },
  evidence_links: { category: "C", userRefColumns: ["linked_by_user_id", "confirmed_by_user_id", "detached_by_user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "NEW (ADR-0012 Step 2, migration 20261081). WHERE an evidence artifact COUNTS, as distinct from where it came from (evidence.source_type/source_id, which freezes as origin). One artifact, one blob, one evidence_analysis row — N uses. A link counts ONLY when a human confirmed THAT link in THAT context: confirmation is all-or-none (timestamp + user + non-empty note), write-once by trigger, and never leaks between contexts, which is what makes cross-vertical reuse safe. Append-and-detach: app_request holds SELECT, INSERT and a COLUMN-LIMITED UPDATE (confirm/detach columns only) — there is NO DELETE grant, and identity columns are frozen by trigger, so a link cannot be repointed after a decision relied on it. evidence_id is ON DELETE RESTRICT (an artifact in use cannot be deleted out from under the decision that used it) and target_id is polymorphic with no FK (the findings.source_id tradeoff; route-level target verification is the guard the writer package owes). target_requirement_id expresses the engagement x requirement grain the effectiveness ladder counts at, RESTRICT so a requirement cannot vanish and silently widen what its evidence proves. Cross-org linking is refused by trigger, not only by RLS. EMPTY BY CONSTRUCTION on arrival: no route, worker or backfill writes it, and no legacy origin link was fabricated." },
  evidence_lifecycle_events: { category: "E", userRefColumns: ["actor_user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "NEW (ADR-0012 Step 2, migration 20261082). APPEND-ONLY stream of what happened to an evidence artifact and to each of its uses — link / confirm / detach / supersede / validity_established / assurance_class_established / expiry_observed. Category E alongside finding_lifecycle_events and security_audit_log: it records what was DONE, not content a user authored, and it must survive the removal of what it describes. UPDATE/DELETE/TRUNCATE refused by the SHARED worm_guard_mutation (20261017), never a private copy; app_request holds SELECT+INSERT only. evidence_id and link_id are held BY VALUE with no FK on purpose — an event recording that an artifact was destroyed must not be destroyed with it, and a second cascade-blocked WORM table behind evidence would repeat the condition that makes DELETE FROM users fail estate-wide via finding_lifecycle_events. actor_user_id is ON DELETE SET NULL to match the lifecycle family; that SET NULL is an UPDATE the WORM guard refuses, which is latent only because product code tombstones users (D-1). 'expiry_observed' is a NOTICE and flips nothing: posture must not depend on whether a cron fired, and expiry never un-closes a closed finding (ADR-0009). Empty on arrival — no writer, and no historical event was fabricated." },
  evidence_validity_policy: { category: "E", piiRisk: "none", rlsStatus: "none", specialHandling: "NEW (VA-S4 step 3, migration 20261083). The ratified platform evidence-validity policy — global governed reference content like the canonical crosswalk, NOT org-dimensioned, so there is no tenant boundary to enforce and RLS is deliberately NOT enabled (rlsStatus 'none' here means 'no org dimension to scope', not 'owed'). app_request holds SELECT only; the table changes by migration, never by the application, because a duration is a ratified product decision and not a runtime setting. Append-only VERSIONS (superseded_at, one live row per class via a partial unique index) so a determination made under an earlier policy stays replayable — D15's reproducibility requirement applies to the platform layer too. Seeded with D1 ONLY (soc1, soc2_type2 at 12 months from report period end with a 3..15 customer range, and soc2_type1 with NO duration because D1 ratified 'its own rule' and named no number). Classes D2-D14 are unratified and therefore have NO row: absence yields not_established, which is the fail-closed default and deliberately not a catch-all TTL. 'unclassified' is forbidden a policy by CHECK — an artifact nobody classified must never inherit a duration."},
  organization_evidence_validity_settings: { category: "C", userRefColumns: ["set_by_user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "NEW (VA-S4 step 3, migration 20261083). A customer's own validity position per assurance class, per D15 ratified 2026-09-01: tighten FREELY (min_duration_months is the platform's floor for its own default, never a customer bound — a stricter customer needs no permission) and loosen only to the live platform ceiling, which org_evidence_validity_guardrail enforces by trigger because the check needs a lookup a CHECK cannot do. A class with no live platform policy, or one whose policy carries no ratified duration, cannot be configured at all — refused rather than silently defaulted. Append-and-supersede: identity, value, version, reason and created_at are frozen by trigger and app_request's UPDATE grant is column-limited to superseded_at, with NO DELETE grant, so a past determination's basis can never change underneath it. RLS enabled and FORCED, org-scoped USING and WITH CHECK. Both triggers are BEFORE INSERT OR UPDATE only — this is not a WORM table and must not claim DELETE/TRUNCATE, which belong to the shared worm_guard_mutation. Empty on arrival: no route writes it, and D16 ratified that nothing is backfilled."},
  reports: { category: "D", piiRisk: "low", rlsStatus: "pending" },
  posture_snapshots: { category: "D", piiRisk: "none", rlsStatus: "enabled" },
  domain_scores: { category: "D", piiRisk: "none", rlsStatus: "pending" },
  organization_risk_scales: { category: "D", piiRisk: "none", rlsStatus: "pending" },
  webhook_endpoints: { category: "D", piiRisk: "low", rlsStatus: "pending", exportExcludedColumns: ["secret"], specialHandling: "`secret` is the HMAC signing secret for webhook delivery — OMITTED from the org_full export (exportExcludedColumns, PR #2b/Q5); url, event_types, status, description are retained for portability." },
  webhook_deliveries: { category: "D", piiRisk: "low", rlsStatus: "pending" },
  org_sso_configs: { category: "D", piiRisk: "low", rlsStatus: "none", specialHandling: "Org-level SAML IdP config; no user ref." },
  sso_login_codes: { category: "B", userRefColumns: ["user_id"], piiRisk: "medium", rlsStatus: "enabled", specialHandling: "NEW (SSO token-handoff hardening, 20260912). One-time 60s login codes for the SAML ACS -> app session handoff (replaces the session-JWT-in-URL redirect). Stores code_hash (sha256, never the raw code) + email/display_name for the callback. Rows are ephemeral (single-use, swept after 1h); user_id and organization_id are ON DELETE CASCADE, so erasure needs no reaper step. Written/consumed by the UNAUTHENTICATED auth path on the owner pool (org unknown until the code row is read); RLS enabled for defense in depth." },
  api_usage_daily: { category: "D", piiRisk: "none", rlsStatus: "pending" },
  enterprise_data_stores: { category: "D", piiRisk: "none", rlsStatus: "enabled", specialHandling: "NEW (ECL Slice 1). Typed child of a data_store enterprise_entity (CASCADE with parent). No user ref — org data-store metadata (classification/residency/retention/encryption). RLS enabled from creation (NOT FORCE, inert until app_request flip)." },
  assets: { category: "D", piiRisk: "none", rlsStatus: "enabled", specialHandling: "NEW (EAR Phase 1). Tier-0 asset registry spine — identity-only (asset_type + polymorphic backing_kind/backing_id pointer + lifecycle_status; NO name/criticality/owner copy per EAR-AD-2). No user ref, no PII. Reads behind SECURELOGIC_ASSET_REGISTRY_ENABLED; writes only via registerAsset()/backfill (flag-gated) and the 20260803 in-migration backfill. RLS enabled from creation (NOT FORCE, inert until app_request flip)." },
  asset_product_identities: { category: "C", userRefColumns: ["attested_by_user_id"], piiRisk: "none", rlsStatus: "enabled", specialHandling: "NEW (ERG C4 / ADR-0003 D1, migration 20260905). What EVIDENCE says a tenant asset RUNS: asset_id -> canonical_product_id with `provenance` (attestation | sbom | connector | inferred), confidence 0-100 and an evidence_ref for explainability (ERG R2). Tenant data (org-scoped, RLS enabled from creation, NOT FORCE) — distinct from the ORG-NEUTRAL canonical_products* reference tables it points at. It is INPUT to the single ApplicabilityEngineV1 via tenantAssetResolver, never a second matcher (EAR-AD-3). attested_by_user_id is set ONLY for provenance='attestation' (CHECK-enforced) and is a user ref, not PII. Confidence is the R2 evidence gate: evidence (>=85) can support `affected`; a bare name inference (60) is BELOW applicabilityPolicy.matchThresholds.high and can only ever raise `potentially_affected`. Written by the flag-gated C4 ingest path and the attestation route; asset_id has no FK (polymorphic AssetRef, same discipline as asset_assessments)." },
  cloud_resources: { category: "C", userRefColumns: ["owner_user_id"], piiRisk: "none", rlsStatus: "enabled", specialHandling: "NEW (EAR Phase 3a). Tier-1 detail table for cloud_resource assets (provider/account/region/resource_type). owner_user_id ON DELETE SET NULL. Created only via flag-gated paths (POST /api/assets, connector sync) — always registered in `assets` in the same tx. RLS enabled from creation (NOT FORCE)." },
  endpoints: { category: "C", userRefColumns: ["owner_user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "NEW (EAR Phase 3a). Tier-1 detail table for endpoint assets (hostname/os/exposure/last_seen_at — hostnames can embed usernames, hence low not none). owner_user_id ON DELETE SET NULL. Flag-gated creation paths only; always registered in same tx. RLS enabled from creation (NOT FORCE)." },
  apis: { category: "C", userRefColumns: ["owner_user_id"], piiRisk: "none", rlsStatus: "enabled", specialHandling: "NEW (EAR Phase 3a). Tier-1 detail table for api assets (protocol/auth_method/exposure). owner_user_id ON DELETE SET NULL. Flag-gated creation paths only; always registered in same tx. RLS enabled from creation (NOT FORCE)." },
  identity_systems: { category: "C", userRefColumns: ["owner_user_id"], piiRisk: "none", rlsStatus: "enabled", specialHandling: "NEW (EAR Phase 3a). Tier-1 detail table for identity_system assets (idp_vendor/protocol — the IdP system itself, NOT identity accounts). owner_user_id ON DELETE SET NULL. Flag-gated creation paths only; always registered in same tx. RLS enabled from creation (NOT FORCE)." },
  enterprise_connectors: { category: "D", piiRisk: "low", rlsStatus: "enabled", exportExcludedColumns: ["config_encrypted"], specialHandling: "NEW (EAR Phase 3b). Per-org connector configuration. `config_encrypted` holds operator credentials encrypted at the application layer (fieldEncryption AES-256-GCM) — OMITTED from all exports (exportExcludedColumns), never logged, never returned by routes (config field keys only). Routes/worker double-fenced behind SECURELOGIC_ENTERPRISE_CONTEXT_ENABLED + SECURELOGIC_ASSET_REGISTRY_ENABLED. E2.P2 (20260812) adds `sync_cursor` (opaque adapter watermark, no secrets). RLS enabled from creation (NOT FORCE)." },
  connector_asset_observations: { category: "D", userRefColumns: [], piiRisk: "medium", rlsStatus: "enabled", specialHandling: "NEW (ERIP E2.P2, 20260812). Per-org discovery-fact ledger (ERIP-AD-8): which connector observed which external_ref, when, under what name/lane, plus derived stale/confidence and (E2.P4) owner_hint/metadata. `owner_hint` may carry a discovered owner email (PII). Engine-written only (connector sync worker); no public write route. Reconciliation/drift derive from this table — canonical stores are never mutated by it. `metadata` is source-echo only, never compliance-load-bearing (ECL S0 rule). RLS enabled from creation (NOT FORCE)." },
  connector_writeback_intents: { category: "D", userRefColumns: ["requested_by_user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "NEW (ERIP E2a, 20260820). Per-org bidirectional-writeback queue+state (ERIP-AD-12): each row asserts one whitelisted EXTERNAL field value on one external record, with optimistic-concurrency baselines (last_pushed_value / external_prev_value) for deterministic conflict resolution. `desired_value`/`*_value` columns are the org's own asserted/observed field values — NOT credentials (creds stay in enterprise_connectors.config_encrypted). Enqueued via POST /api/connectors/:id/writeback and drained by the writeback worker; both dark behind SECURELOGIC_CONNECTOR_WRITEBACK_ENABLED (on top of ECL + EAR). Outbound writes go through the SSRF-safe connector HTTP client (patchJson). RLS enabled from creation (NOT FORCE)." },
  connector_dead_letters: { category: "D", userRefColumns: ["resolved_by_user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "NEW (ERIP E2b, 20260821). Per-org dead-letter ledger (ERIP-AD-14): a terminally-failed connector operation (sync job or writeback push) captured for operator inspection + re-drive. `error`/`payload` carry failure detail + a re-drive snapshot ({connector_id} or {field, external_ref}) — NEVER credentials. Written passively by the (flag-gated) sync/writeback workers inside their tenant tx; re-drive re-enqueues the op and marks the event 'redriven'. Recovery routes sit behind the connectors chain (ECL + EAR), dark in production. RLS enabled from creation (NOT FORCE)." },
  orchestration_proposals: { category: "C", userRefColumns: ["proposed_by_user_id", "approved_by_user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "NEW (ERIP Epic 6, 20260815). Approval-gated orchestration ledger: proposed operational actions, inert until a DIFFERENT human approves (SoD). Forward-only status (proposed→approved→executed|failed; proposed→rejected). `payload` is executor config (not a domain object). All routes dark behind SECURELOGIC_AUTONOMOUS_OPERATIONS_ENABLED. RLS enabled from creation (NOT FORCE)." },
  risk_history: { category: "D", userRefColumns: [], piiRisk: "none", rlsStatus: "enabled", specialHandling: "NEW (ERIP F2, 20260816). Per-org daily snapshot of the DERIVED dimensional risk rollup (ERIP-AD-15 — recomputable, never a source of truth). One row per (org, snapshot_date, dimension='enterprise'|asset_type). Written only by the risk-history snapshot worker, gated on SECURELOGIC_RISK_INTELLIGENCE_ENABLED + SECURELOGIC_ASSET_REGISTRY_ENABLED. `bands` is a distribution snapshot, not compliance-load-bearing. RLS enabled from creation (NOT FORCE)." },
  risk_forecasts: { category: "D", userRefColumns: [], piiRisk: "none", rlsStatus: "enabled", specialHandling: "NEW (ERIP E5, 20260817). Per-org DERIVED forecasts (OLS/Holt fit over risk_history; ERIP-AD-21 deterministic/explainable/reproducible; recomputable, never a source of truth). One row per (org, dimension, metric, horizon_days). Written only by the predictive inference worker (the re-fit = retraining), gated on SECURELOGIC_PREDICTIVE_INTELLIGENCE_ENABLED + SECURELOGIC_ASSET_REGISTRY_ENABLED. RLS enabled from creation (NOT FORCE)." },
  orchestration_integrations: { category: "D", userRefColumns: [], piiRisk: "low", rlsStatus: "enabled", exportExcludedColumns: ["config_encrypted"], specialHandling: "NEW (ERIP E6a, 20260818). Per-org outbound-channel config (ServiceNow/Jira/Teams/Slack/Email) for the orchestration executors. `config_encrypted` holds credentials/endpoints encrypted at the app layer (fieldEncryption AES-256-GCM) — OMITTED from all exports (exportExcludedColumns), never logged, never returned by routes (config field keys only). Executors run only after a DIFFERENT human approves; outbound calls go through the SSRF-safe connector HTTP client. Dark behind SECURELOGIC_AUTONOMOUS_OPERATIONS_ENABLED + per-integration enabled. RLS enabled from creation (NOT FORCE)." },
  orchestration_playbooks: { category: "C", userRefColumns: ["created_by_user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "NEW (ERIP E6b, 20260819). Per-org playbook definitions (ordered proposal templates + optional schedule). Running a playbook CREATES proposals (status 'proposed') — each still needs a DIFFERENT human to approve before its executor runs (no auto-execution). `steps` is a template array, not a domain object. Dark behind SECURELOGIC_AUTONOMOUS_OPERATIONS_ENABLED. RLS enabled from creation (NOT FORCE)." },

  // ── E — System-wide / operational (leave alone) ────────────────────────────
  signals: { category: "E", piiRisk: "low", rlsStatus: "pending" },
  insights: { category: "E", piiRisk: "low", rlsStatus: "pending" },
  trends: { category: "E", piiRisk: "low", rlsStatus: "pending" },
  trend_signals: { category: "E", piiRisk: "none", rlsStatus: "pending" },
  cyber_signals: { category: "E", piiRisk: "low", rlsStatus: "pending" },
  feed_health: { category: "E", piiRisk: "none", rlsStatus: "none", specialHandling: "GLOBAL operational table — per-source ingestion health (source, timestamps, counts, last_error). Not org-scoped, no PII." },
  sources: { category: "E", piiRisk: "none", rlsStatus: "none", specialHandling: "GLOBAL source-qualification registry (P4/4B/B1). PK `source` == feed_health.source == registry SourceDescriptor.id. SHARED-REF: not org-scoped, no PII, no RLS. Seeds id+kind only; qualification columns populated by a later 4B story." },
  intelligence_events: { category: "E", piiRisk: "none", rlsStatus: "none", specialHandling: "GLOBAL canonical Intelligence Event (Pipeline Hardening / IE.P3). Derived external-intelligence spine — many cyber_signals collapse into one event by canonical_key. Org-agnostic, no organization_id, no RLS. Dark behind SECURELOGIC_INTELLIGENCE_EVENTS_ENABLED." },
  canonical_controls: { category: "E", userRefColumns: ["published_by_user_id"], piiRisk: "none", rlsStatus: "none", specialHandling: "GLOBAL SecureLogic canonical control identity (VA-S4 Step 1, 20261067) — a reusable assurance CONCEPT, never a framework requirement and never tenant data. No organization_id, no RLS: there is structurally nothing here to leak. Same shape as canonical_products, deliberately a different table (a control is not a product). Published content is FROZEN by canonical_controls_publication_guard — a correction is a NEW superseding row, never an in-place edit, so a past assurance decision stays reconstructible. published_by_user_id is a GOVERNANCE ACTOR, not PII, and its FK is ON DELETE RESTRICT on purpose: a published decision must keep naming the human who published it (the publication-authority CHECK would reject a NULL anyway). LEAVE on user delete; RESTRICT never fires under tombstone O-3. Written only through the elevated publication path (scripts/publish-canonical-controls.ts); app_request has SELECT only." },
  canonical_control_aliases: { category: "E", piiRisk: "none", rlsStatus: "none", specialHandling: "GLOBAL child of canonical_controls (VA-S4 Step 1, 20261067). Retains the historical {industry}:control:* slugs from src/templates that templateLoader had been discarding since 20260505, so their meaning survives canonicalization. alias_key is GLOBALLY UNIQUE and a CHECK forbids spelling one in the securelogic:control: namespace — together these keep aliases from becoming a second canonical identity. No organization_id, no RLS, no PII." },
  canonical_framework_versions: { category: "E", piiRisk: "none", rlsStatus: "none", specialHandling: "GLOBAL versioned framework registry (VA-S4 Step 1, 20261068). (framework_key, framework_version) is the FK target for frameworks.framework_key and for the crosswalk — the join key from a TENANT requirement to GLOBAL reference content, which frameworks.name (a mutable display string) could never be. Seeded by the migration and kept in lockstep with canonicalFrameworkIdentity.ts by canonicalFrameworkIdentity.test.ts. No organization_id, no RLS, no PII." },
  canonical_control_crosswalk: { category: "E", userRefColumns: ["approved_by_user_id"], piiRisk: "none", rlsStatus: "none", specialHandling: "GLOBAL governed requirement <-> canonical control crosswalk (VA-S4 Step 1, 20261068), keyed on (framework_key, framework_version, requirement_reference) — NOT requirements.id, which is tenant-scoped and would stop this table being global. Many-to-many both ways; versioned, so a framework version bump adds rows and leaves the old ones addressable for historical reconstruction. THE AI PUBLICATION BOUNDARY lives here as a CHECK: mapping_source may be 'ai_proposed', but no row can leave 'proposed' without a named human approver. approved_by_user_id is a governance actor (ON DELETE RESTRICT, never fires under tombstone O-3), not PII. control_mappings is unchanged and remains the tenant-resolved view. No organization_id, no RLS." },
  control_canonical_identities: { category: "C", userRefColumns: ["attested_by_user_id"], piiRisk: "none", rlsStatus: "enabled", specialHandling: "TENANT control -> GLOBAL canonical control, with provenance (VA-S4 Step 1, 20261069). The control-side twin of asset_product_identities and deliberately the same shape: it records HOW the link was established ('attestation' | 'template' | 'customer_mapped' | 'inferred'), a confidence, and an evidence_ref, and a CHECK makes attestation structurally require a named human while forbidding one on every other provenance. A control with NO row here is a customer-specific control with no canonical identity — a legitimate, representable state, never a gap to be filled. One row per (control, canonical control, provenance): a template load and a human attestation COEXIST and are ranked by CONTROL_CANONICAL_PROVENANCE_AUTHORITY rather than one clobbering the other. Org-scoped, RLS enabled from creation. control_id and canonical_control_id are ON DELETE RESTRICT — an identity used in an assurance decision must not vanish underneath it. Erasure via the organizations CASCADE." },
  canonical_products: { category: "E", piiRisk: "none", rlsStatus: "none", specialHandling: "GLOBAL Canonical Product reference (Enterprise Risk Graph convergence C1b, migration 20260830). Org-neutral intermediate normalization entity (ruling R1) — normalizes external product/version/package/service identities BEFORE tenant-asset resolution; NOT the primary risk object. No organization_id, no RLS, no tenant data (structurally cannot leak). canonical_key UNIQUE = deterministic dedup. DARK — no live caller." },
  canonical_product_aliases: { category: "E", piiRisk: "none", rlsStatus: "none", specialHandling: "GLOBAL child of canonical_products (CASCADE). Alternate raw names + normalized form + provenance (source). No organization_id, no RLS, no PII. DARK." },
  canonical_product_external_ids: { category: "E", piiRisk: "none", rlsStatus: "none", specialHandling: "GLOBAL child of canonical_products (CASCADE). Authoritative identifiers / external mappings (CPE is one OPTIONAL scheme). No organization_id, no RLS, no PII. DARK." },
  canonical_product_versions: { category: "E", piiRisk: "none", rlsStatus: "none", specialHandling: "GLOBAL child of canonical_products (CASCADE). Version semantics + provenance. No organization_id, no RLS, no PII. DARK." },
  intelligence_event_sources: { category: "E", piiRisk: "none", rlsStatus: "none", specialHandling: "GLOBAL corroboration ledger for intelligence_events (source attribution + revisions). Denormalised source/external_id survive signal purge. Not org-scoped, no PII, no RLS." },
  intelligence_event_timeline: { category: "E", piiRisk: "none", rlsStatus: "none", specialHandling: "GLOBAL append-only timeline for intelligence_events (advisories, exploit activity, patches, revisions). Not org-scoped, no PII, no RLS." },
  intelligence_event_notifications: { category: "D", piiRisk: "none", rlsStatus: "enabled", specialHandling: "ORG-scoped notification dedup ledger (Pipeline Hardening / IE.P7) — one row per (org, canonical event, channel) already notified, so the policy never double-sends. RLS enabled NOT FORCE + app_request grant. No PII (references events + channel only)." },
  intelligence_event_workflow_triggers: { category: "E", piiRisk: "none", rlsStatus: "none", specialHandling: "GLOBAL workflow-trigger dedup ledger (Pipeline Hardening item 7) — one row per (event, lifecycle state reached) so workflow follow-through fires once per transition. Not org-scoped, no PII, no RLS." },
  intelligence_briefs: { category: "E", piiRisk: "low", rlsStatus: "pending" },
  intelligence_brief_items: { category: "E", piiRisk: "low", rlsStatus: "pending" },
  intelligence_brief_item_provenance: { category: "E", piiRisk: "none", rlsStatus: "enabled", specialHandling: "P4/4D/D1 lineage edge: brief_item -> contributing cyber_signal (canonical + corroborating), with cluster_key. Org-owned (organization_id NOT NULL); RLS enabled from creation (NOT FORCE, inert until app_request flip). Signal FK ON DELETE SET NULL + denormalised source_slug so lineage survives signal purge. No PII. Inert in D1 — populated in D2." },
  intelligence_brief_sends: { category: "E", piiRisk: "low", rlsStatus: "pending", specialHandling: "Delivery audit trail; subscriber_id FK. Retained for deliverability/audit." },
  intelligence_brief_sources: { category: "E", piiRisk: "none", rlsStatus: "none", specialHandling: "SHARED-REF source catalog (Tier C, SELECT-only)." },
  newsletter_issues: { category: "E", piiRisk: "low", rlsStatus: "pending" },
  newsletter_issue_insights: { category: "E", piiRisk: "none", rlsStatus: "pending" },
  published_artifacts: { category: "E", piiRisk: "none", rlsStatus: "none", specialHandling: "SHARED-REF published-brief store (Tier C, SELECT-only)." },
  worker_runs: { category: "E", piiRisk: "none", rlsStatus: "none", specialHandling: "Owner-only telemetry (Tier D — no app_request grant)." },
  auth_anomaly_alerts: { category: "E", piiRisk: "low", rlsStatus: "none", specialHandling: "Owner-only (Tier D). subject column holds an offending IP." },
  risk_scale_presets: { category: "E", piiRisk: "none", rlsStatus: "none", specialHandling: "SHARED-REF preset catalog (Tier C, SELECT-only); no org column." },
  webhook_events_processed: { category: "E", piiRisk: "none", rlsStatus: "none", specialHandling: "Owner-only webhook idempotency ledger (Tier D)." },
  pen_test_engagements: { category: "E", userRefColumns: ["created_by_user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "ORG-SCOPED provenance for penetration-test findings (SL-PENTEST-IN): which test, by whom, when, and where the report is. findings.source_type='pen_test' points here via source_id. `provider` is FREE TEXT, deliberately not a vendors FK — recording a test must not require onboarding its supplier into third-party risk first — so it may name a third-party firm and is org-confidential. Category E with userRefColumns=[created_by_user_id] (ON DELETE SET NULL; never fires under tombstone O-3). No DELETE grant: an engagement is the provenance of its findings and deleting it would orphan them silently. Erasure via the organizations CASCADE." },
  pen_test_finding_retests: { category: "E", userRefColumns: ["recorded_by_user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "ORG-SCOPED append-only retest record (T2-I): one row per retest act on a pen-test finding — what the tester found on re-examination, when, under which engagement (a NEXT engagement legitimately retests a prior one's findings, so engagement_id is a real FK). A retest result NEVER closes the finding — machines observe, humans decide (third appearance of that ruling). finding_id and engagement_id are ON DELETE RESTRICT: a verification history makes its subjects non-deletable. Tier B by grant (SELECT+INSERT, no UPDATE/DELETE) — an audit trail, not a state column. userRefColumns=[recorded_by_user_id] (ON DELETE SET NULL; never fires under tombstone O-3): the row records WHO performed the verification, so it belongs in that subject's Art. 15 export. Erasure via the organizations CASCADE." },
  vulnerability_scan_runs: { category: "E", piiRisk: "low", rlsStatus: "enabled", specialHandling: "ORG-SCOPED record of one scan from one source (SL-OCC-2). The unit of AUTHORITY for absence: only status='completed' AND scope_declared=TRUE may cause an occurrence to be marked absent, and only for assets listed in vulnerability_scan_run_assets. scope_declared defaults FALSE so a source must opt IN — forgetting it means 'we never auto-close', which is recoverable; the opposite is not. ENGINE-WRITTEN ONLY, no public write route (the connector_asset_observations posture). No user columns. Erasure via the organizations CASCADE." },
  vulnerability_scan_run_assets: { category: "E", piiRisk: "low", rlsStatus: "enabled", specialHandling: "ORG-SCOPED declared SCOPE of a scan run (SL-OCC-2) — which assets it covered. An asset here carrying no reported vulnerability was looked at and found clean; an asset NOT here was not looked at and nothing may be concluded about it. This table is the difference between saying 'no longer present' and guessing. Composite PK (scan_run_id, asset_id); no user columns. Erasure via the organizations CASCADE." },
  vulnerability_observations: { category: "E", piiRisk: "low", rlsStatus: "enabled", specialHandling: "ORG-SCOPED ledger of what ONE source reported about ONE occurrence (SL-OCC-2). Two scanners reporting the same exposure are two observations of one occurrence — not two occurrences and not two pieces of remediation work. Each source keeps its own seen-window and staleness so sources can disagree without overwriting each other. `metadata` is source-echo only, never compliance-load-bearing (ECL S0). ENGINE-WRITTEN ONLY, no public write route. No user columns. Erasure via the organizations CASCADE." },
  finding_asset_occurrences: { category: "E", userRefColumns: ["created_by_user_id", "remediated_by_user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "ORG-SCOPED exposure of one asset to one finding (SL-OCC-1). Identity is (organization_id, finding_id, asset_id) — deliberately NOT (organization_id, cve_id): one CVE on fifty hosts is fifty occurrences of ONE finding. Carries the PRESENCE axis only (present/absent/remediated), independent of findings.decision_state and findings.operational_status; absence is an observation and NEVER closes a finding (ERIP-AD-11). Category E with two userRefColumns (both ON DELETE SET NULL; never fire under tombstone O-3) because the row records WHO recorded the exposure and WHO remediated it, so it belongs in those subjects' Art. 15 export. app_request holds SELECT/INSERT/UPDATE/DELETE — UPDATE because presence legitimately transitions in place. Erasure via the organizations CASCADE." },
  asset_identifiers: { category: "E", piiRisk: "low", rlsStatus: "enabled", specialHandling: "ORG-SCOPED alias index over the canonical `assets` registry (SL-OCC-1): the identifiers OTHER systems use for an asset SecureLogic already knows. NOT an asset inventory — creates no assets, owns no attributes. Uniqueness is (organization_id, asset_id, scheme, value): an identifier does NOT uniquely determine an asset, and the same hostname may legitimately be claimed by two assets. Volatile schemes (ip, mac) are stored as evidence but are never resolution keys — see assetIdentity.ts. May contain internal hostnames/FQDNs/IPs, which are org-confidential infrastructure detail but not personal data. No UPDATE grant: an alias is asserted or withdrawn, never edited. Erasure via the organizations CASCADE." },
  asset_resolution_reviews: { category: "E", userRefColumns: ["accepted_by_user_id", "dismissed_by_user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "ORG-SCOPED human review queue for asset-identity resolution (PLAT-ASSET-1): ambiguous matches, conflicting identities, and strong-scheme claims that fail grammar validation. Machines never guess — a row here is a question only a human may answer (operator ruling 2026-08-22). Modeled on signal_match_suggestions: pending/accepted/dismissed with timestamps-encode-state CHECK; terminal rows immutable at the route layer; partial unique excludes terminal rows. candidate_asset_ids is a UUID[] with NO FK — the accept handler re-verifies the chosen asset against the caller's org. claims_echo is source-echo JSONB only, never compliance-load-bearing (ECL S0). value may contain internal hostnames/FQDNs — org-confidential infrastructure detail, not personal data. userRefColumns = the two decider columns (ON DELETE SET NULL; never fire under tombstone O-3): the row records WHO decided, so it belongs in that subject's Art. 15 export. app_request holds SELECT/INSERT/UPDATE — no DELETE, a review is a record. Erasure via the organizations CASCADE." },
  asset_origins: { category: "E", piiRisk: "low", rlsStatus: "enabled", specialHandling: "ORG-SCOPED provenance sidecar for AUTOMATICALLY created assets (PLAT-ASSET-1): how SecureLogic learned of the asset (created_via + source_key + run), under which identity (scheme + normalized value), and when first observed. One row per auto-created asset (asset_id UNIQUE, CASCADE with the asset); written in the creating transaction; never updated or deleted by a request path (SELECT/INSERT only). Absence means the asset was NOT machine-created by identity resolution — the honest default for everything manual or connector-created. No user columns. Erasure via the organizations CASCADE." },
  finding_risks: { category: "E", userRefColumns: ["created_by_user_id"], piiRisk: "low", rlsStatus: "enabled", specialHandling: "ORG-SCOPED many-to-many between findings and Risk Register entries (SL-RISK-LINK). A finding with no row here is STANDALONE — the default, never set by automation. Carries created_by_user_id (ON DELETE SET NULL; never fires under tombstone O-3) and a free-text note, so it is included in the org export alongside findings and risks. Link/unlink/promotion history lives in security_audit_log and survives the row being deleted. app_request holds SELECT/INSERT/DELETE — no UPDATE, because a relationship is created or removed, never edited into a different pair. Category E with userRefColumns=[created_by_user_id], matching finding_lifecycle_events and finding_risk_acceptances: the row records WHO decided, so it belongs in that subject's Art. 15 export; ON DELETE SET NULL never fires under tombstone O-3." },
  billing_dunning_cycles: { category: "D", piiRisk: "none", rlsStatus: "enabled", specialHandling: "ORG-SCOPED billing lifecycle record: one row per delinquency cycle, identity (organization_id, cycle_started_at = organizations.payment_failed_at). Ids and timestamps ONLY — no amounts, no card data, no customer PII, no user or session id, so there is no individual Art. 15/17 obligation (userRefColumns is empty). WRITTEN by the Stripe webhook on the ELEVATED channel (a provider callback has no tenant scope); RLS + policy exist so any READ surface added later is org-scoped by construction. app_request holds SELECT only — nothing on the request path may forge or destroy a billing record. Erasure is via the organizations CASCADE." },
  jobs: { category: "E", piiRisk: "low", rlsStatus: "enabled", specialHandling: "NEW (this PR). Org-scoped async work queue; requested_by_user_id ON DELETE SET NULL (never fires under tombstone). Worker reads cross-org on the elevated channel." },
  data_export_files: { category: "E", piiRisk: "medium", rlsStatus: "enabled", specialHandling: "NEW (this PR). The R2 bundle it points to CONTAINS a full PII export — purge after 7 days (O-11). download_token_hash lookup precedes org context → use pgElevated. Holds downloaded_from_ip." },

  // ── E (special, audit) ─────────────────────────────────────────────────────
  audit_log: { category: "E", piiRisk: "medium", rlsStatus: "none", specialHandling: "HTTP request log. No user FK; actor_label may embed an email. Tier B (SELECT+INSERT, no UPDATE/DELETE). GDPR retention vs erasure tension — keep, document lawful basis." },
  security_audit_log: { category: "E", piiRisk: "medium", rlsStatus: "none", specialHandling: "APPEND-ONLY (immutability triggers, 20260614). actor_user_id is ON DELETE SET NULL — a hard user delete would trigger a cascade UPDATE the trigger REJECTS, aborting the delete. Tombstone (O-3) avoids this entirely by never deleting the user row. Tier B (SELECT+INSERT)." },
  risk_lifecycle_events: { category: "E", piiRisk: "low", rlsStatus: "enabled", specialHandling: "NEW (Epic R1). APPEND-ONLY per-risk lifecycle event stream (immutability triggers, 20260714). Org-scoped (organization_id NOT NULL); RLS enabled from creation (NOT FORCE, inert until app_request flip). actor_user_id ON DELETE SET NULL (never fires under tombstone O-3); comment is free text. Written in-tenant-tx by riskLifecycle.ts. DARK until SECURELOGIC_RISK_LIFECYCLE_ENABLED. Tier B (SELECT+INSERT)." },
  risk_approvals: { category: "E", piiRisk: "low", rlsStatus: "enabled", specialHandling: "NEW (Epic R1 scaffold; R2 executes). Org-scoped risk-approval workflow (subsumes RR-8); analogous to jobs. requested_by_user_id NOT NULL (RESTRICT never fires under tombstone O-3); approver_user_id ON DELETE SET NULL. Separation of duties enforced by DB CHECK. DARK until SECURELOGIC_RISK_LIFECYCLE_ENABLED." },

  // ── E (special, email-keyed PII — not user-id keyed) ───────────────────────
  subscribers: { category: "E", exportByEmailOnly: true, piiRisk: "high", rlsStatus: "pending", specialHandling: "Email-keyed (UNIQUE email), NOT user_id keyed. Match by the user's current email, not a user FK. Platform-level (no organization_id) — email is the sole key. delete=leave, export=include-by-email (Q6)." },
  intelligence_brief_subscribers: { category: "E", exportByEmailOnly: true, piiRisk: "high", rlsStatus: "pending", specialHandling: "Keyed by (organization_id, email), NOT user_id. A subscriber is an email address, not necessarily a platform user. Match by current email. delete=leave, export=include-by-email (Q6)." },
  newsletter_deliveries: { category: "E", exportByEmailOnly: true, piiRisk: "medium", rlsStatus: "pending", specialHandling: "Holds subscriber_email. Delivery audit trail. Match by current email. delete=leave, export=include-by-email (Q6)." },
  email_suppressions: { category: "E", piiRisk: "medium", rlsStatus: "none", specialHandling: "KEEP on user delete (O-8): deleting a suppression could re-enable mail to a bounced/complained address. Lawful basis = deliverability/compliance obligation. Tier C (SELECT-only). Platform-level, no org column." },

  email_sends: { category: "E", piiRisk: "low", rlsStatus: "none", specialHandling: "EMAIL-OBS-1 send ledger: one row per provider attempt from every send site, keyed by provider message id so webhook events join back to purpose/org/correlation. Holds NO address — recipient_domain + keyed recipient_hash only. Platform-level; organization_id is informational (no FK). LEAVE on user delete (nothing identifies the subject without the HMAC key); excluded from self-export (no per-subject lookup key). Owner-only, written via pgElevated, RLS off." },
  email_provider_events: { category: "E", piiRisk: "medium", rlsStatus: "none", specialHandling: "Raw provider (Resend) webhook event log; platform-level, no org column. LEAVE on user delete — Disposition A per docs/legal/D9-erasure-vs-export-DETERMINATION.md; the reaper writes to no no-org table. INCLUDED in Art. 15 self-export by email, structured fields ONLY — `payload` is excluded because it is the provider's verbatim body and may carry a third party's data. Existed in the production DB with no CREATE TABLE migration until 20260811_email_provider_events_ddl_reconciliation; it was absent on staging/demo, so every webhook there failed. Owner-only grants, RLS off in prod; app_request grant is an open decision for the flip." },

  // ── F — Billing / financial (special legal-retention handling) ─────────────
  api_keys: { category: "F", userRefColumns: ["created_by_user_id"], piiRisk: "medium", rlsStatus: "pending", specialHandling: "Carries legacy Stripe mirror fields (stripe_customer_id, payment_failed_at, stripe_subscription_tier) with legal-retention. Org-scoped, not user-scoped — a single member self-delete does NOT touch billing. Anonymize created_by_user_id only (SET NULL never fires under tombstone)." },
};

/**
 * The exact field rewrites the reaper (PR #6) applies to the users row on
 * tombstone. NOT applied by any code in this PR — encoded here for review and
 * for the reaper to consume.
 *
 * Mirror of docs/DATA_CLASSIFICATION.md §"Tombstone behavior specification".
 *
 * Template tokens (resolved by the reaper at write time):
 *   "{id}"  → the user's own UUID (so the scrubbed email stays globally UNIQUE,
 *             satisfying the users_email_unique constraint).
 *   "{now}" → now() / the reap timestamp.
 *
 * NOTE — totp_backup_codes: the O-3 spec said "→ NULL", but the column is
 * `text[] NOT NULL DEFAULT '{}'`, so NULL would violate NOT NULL. The only
 * valid scrub is an empty array. Encoded as [] accordingly.
 */
export const TOMBSTONE_USER_PATCH = {
  // identity / PII
  email: "deleted-{id}@deleted.invalid",
  name: "Deleted User",
  // credentials & secrets
  password_hash: "",
  totp_secret: null,
  totp_enabled: false,
  totp_backup_codes: [] as string[], // NOT NULL text[] → empty array, not NULL
  // tokens
  email_verified: false,
  email_verification_token: null,
  email_verification_expires_at: null,
  password_reset_token: null,
  password_reset_expires_at: null,
  // behavioral / login telemetry
  failed_login_attempts: 0,
  lockout_until: null,
  last_failed_login_at: null,
  last_login_at: null,
  previous_login_at: null,
  password_changed_at: null,
  // identity provider linkage
  sso_provider: null,
  // per-user UI state (NOT NULL text[]) → empty array, not NULL
  dismissed_banner_keys: [] as string[],
  // lifecycle
  status: "deleted",
  deleted_at: "{now}",
  updated_at: "{now}",
} as const;

/**
 * users columns that are deliberately PRESERVED on tombstone (NOT NULL and/or
 * identity columns whose whole purpose is to survive deletion). Listing them
 * explicitly lets the drift test prove every NOT-NULL/PII column is a conscious
 * scrub-or-preserve decision rather than silently unhandled.
 *
 * Mirror of docs/DATA_CLASSIFICATION.md §"Tombstone behavior specification".
 */
export const TOMBSTONE_PRESERVED_COLUMNS: readonly string[] = [
  "id", // the whole point of tombstone — UUID preserved for audit integrity
  "organization_id", // FK / audit attribution integrity
  "role", // org structure, last-admin accounting
  "seat_type", // seat accounting — not PII; a tombstoned row consumes no seat (status != active)
  "created_at", // audit
  "deletion_scheduled_at", // audit: when the grace window started
  "deletion_requested_by_user_id", // audit: who requested the deletion
  "deletion_reason", // audit: why
  // SEC-JWT-EPOCH: a monotonic session counter, not personal data. Preserved
  // rather than scrubbed on purpose — resetting it to 0 could make a stale
  // token whose `se` is 0 match again. A tombstoned row is status='deleted' and
  // already blocked earlier in both middlewares, so this is defence in depth,
  // but the counter must never travel backwards.
  "session_epoch",
];

/**
 * The four valid users.status lifecycle states and their meaning.
 * Mirror of docs/DATA_CLASSIFICATION.md §"User lifecycle states" and the CHECK
 * constraint in 20260621_gdpr_foundations.sql.
 */
export const USER_LIFECYCLE_STATES = {
  active: "Normal user, can authenticate.",
  inactive:
    "Deactivated by admin or auto-deactivated (e.g. team-member removal). Cannot authenticate. NOT pending deletion. Pre-existing behavior.",
  pending_deletion:
    "Deletion requested; in the 30-day grace window; cannot authenticate; cancellable until the reaper runs.",
  deleted:
    "Tombstoned: PII scrubbed in place, UUID preserved. Terminal state.",
} as const;
