/**
 * frameworkTemplates.ts — Pre-built compliance framework content
 *
 * Static module providing seed content for the four most common frameworks.
 * Used by the frameworkActivation route to bootstrap org framework libraries.
 */

export type FrameworkTemplate = {
  name: string;
  version: string;
  description: string;
  requirements: Array<{ reference_id: string; title: string }>;
};

export const FRAMEWORK_TEMPLATES: Record<string, FrameworkTemplate> = {
  soc2: {
    name: "SOC 2",
    version: "Type II",
    description:
      "AICPA Trust Services Criteria for security, availability, processing integrity, confidentiality, and privacy",
    requirements: [
      { reference_id: "CC1.1", title: "COSO Principle 1: Demonstrates commitment to integrity and ethical values" },
      { reference_id: "CC1.2", title: "COSO Principle 2: Exercises oversight responsibility" },
      { reference_id: "CC1.3", title: "COSO Principle 3: Establishes structure, authority, and responsibility" },
      { reference_id: "CC1.4", title: "COSO Principle 4: Demonstrates commitment to competence" },
      { reference_id: "CC1.5", title: "COSO Principle 5: Enforces accountability" },
      { reference_id: "CC2.1", title: "Uses relevant, quality information" },
      { reference_id: "CC2.2", title: "Communicates internally" },
      { reference_id: "CC2.3", title: "Communicates externally" },
      { reference_id: "CC3.1", title: "Specifies suitable objectives" },
      { reference_id: "CC3.2", title: "Identifies and analyzes risk" },
      { reference_id: "CC3.3", title: "Assesses fraud risk" },
      { reference_id: "CC3.4", title: "Identifies changes" },
      { reference_id: "CC4.1", title: "Conducts ongoing or separate evaluations" },
      { reference_id: "CC4.2", title: "Evaluates and communicates deficiencies" },
      { reference_id: "CC5.1", title: "Selects and develops controls" },
      { reference_id: "CC5.2", title: "Selects and develops technology general controls" },
      { reference_id: "CC5.3", title: "Deploys policies and procedures" },
      { reference_id: "CC6.1", title: "Implements logical access security" },
      { reference_id: "CC6.2", title: "Manages logical access" },
      { reference_id: "CC6.3", title: "Removes logical access" },
      { reference_id: "CC6.4", title: "Restricts physical access" },
      { reference_id: "CC6.5", title: "Disposes of physical media" },
      { reference_id: "CC6.6", title: "Protects against external threats" },
      { reference_id: "CC6.7", title: "Manages transmission of data" },
      { reference_id: "CC6.8", title: "Implements controls to prevent malware" },
      { reference_id: "CC7.1", title: "Detects vulnerabilities" },
      { reference_id: "CC7.2", title: "Monitors infrastructure" },
      { reference_id: "CC7.3", title: "Evaluates security events" },
      { reference_id: "CC7.4", title: "Responds to security incidents" },
      { reference_id: "CC7.5", title: "Recovers from security incidents" },
      { reference_id: "CC8.1", title: "Manages changes" },
      { reference_id: "CC9.1", title: "Identifies and assesses business disruption risk" },
      { reference_id: "CC9.2", title: "Assesses vendor risk" },
      { reference_id: "A1.1", title: "Manages capacity demand" },
      { reference_id: "A1.2", title: "Designs for recovery" },
      { reference_id: "A1.3", title: "Tests recovery" },
    ],
  },

  nist_csf: {
    name: "NIST Cybersecurity Framework",
    version: "1.1",
    description:
      "NIST framework for improving critical infrastructure cybersecurity through Identify, Protect, Detect, Respond, Recover functions",
    requirements: [
      { reference_id: "ID.AM-1", title: "Physical devices and systems are inventoried" },
      { reference_id: "ID.AM-2", title: "Software platforms and applications are inventoried" },
      { reference_id: "ID.AM-3", title: "Organizational communication and data flows are mapped" },
      { reference_id: "ID.AM-4", title: "External information systems are catalogued" },
      { reference_id: "ID.AM-5", title: "Resources are prioritized" },
      { reference_id: "ID.AM-6", title: "Cybersecurity roles are established" },
      { reference_id: "ID.BE-1", title: "Organization's role in supply chain is identified" },
      { reference_id: "ID.BE-2", title: "Organization's criticality is established" },
      { reference_id: "ID.BE-3", title: "Priorities are established" },
      { reference_id: "ID.BE-4", title: "Dependencies are established" },
      { reference_id: "ID.BE-5", title: "Resilience requirements are established" },
      { reference_id: "ID.GV-1", title: "Cybersecurity policy is established" },
      { reference_id: "ID.GV-2", title: "Roles and responsibilities are coordinated" },
      { reference_id: "ID.GV-3", title: "Legal requirements are understood" },
      { reference_id: "ID.GV-4", title: "Governance processes address cybersecurity risks" },
      { reference_id: "ID.RA-1", title: "Asset vulnerabilities are identified" },
      { reference_id: "ID.RA-2", title: "Threat intelligence is received" },
      { reference_id: "ID.RA-3", title: "Threats are identified" },
      { reference_id: "ID.RA-4", title: "Potential impacts are identified" },
      { reference_id: "ID.RA-5", title: "Threats and vulnerabilities are used to determine risk" },
      { reference_id: "ID.RA-6", title: "Risk responses are identified" },
      { reference_id: "PR.AC-1", title: "Identities are managed" },
      { reference_id: "PR.AC-2", title: "Physical access is managed" },
      { reference_id: "PR.AC-3", title: "Remote access is managed" },
      { reference_id: "PR.AC-4", title: "Access permissions are managed" },
      { reference_id: "PR.AC-5", title: "Network integrity is protected" },
      { reference_id: "PR.AT-1", title: "Users are informed and trained" },
      { reference_id: "PR.AT-2", title: "Privileged users understand roles" },
      { reference_id: "PR.DS-1", title: "Data-at-rest is protected" },
      { reference_id: "PR.DS-2", title: "Data-in-transit is protected" },
      { reference_id: "PR.DS-3", title: "Assets are managed through removal and disposal" },
      { reference_id: "PR.DS-4", title: "Adequate capacity is maintained" },
      { reference_id: "PR.DS-5", title: "Protections against data leaks are implemented" },
      { reference_id: "PR.IP-1", title: "Baseline configuration exists" },
      { reference_id: "PR.IP-2", title: "System development lifecycle is managed" },
      { reference_id: "PR.IP-3", title: "Configuration change control processes are in place" },
      { reference_id: "PR.IP-4", title: "Backups are conducted" },
      { reference_id: "DE.AE-1", title: "Network operations baseline is established" },
      { reference_id: "DE.AE-2", title: "Detected events are analyzed" },
      { reference_id: "DE.AE-3", title: "Event data is collected" },
      { reference_id: "DE.CM-1", title: "Network is monitored" },
      { reference_id: "DE.CM-2", title: "Physical environment is monitored" },
      { reference_id: "DE.CM-3", title: "Personnel activity is monitored" },
      { reference_id: "DE.CM-4", title: "Malicious code is detected" },
      { reference_id: "DE.CM-5", title: "Unauthorized code is detected" },
      { reference_id: "DE.CM-6", title: "External service provider activity is monitored" },
      { reference_id: "DE.CM-7", title: "Unauthorized personnel and devices are monitored" },
      { reference_id: "RS.RP-1", title: "Response plan is executed" },
      { reference_id: "RS.CO-1", title: "Personnel know their roles" },
      { reference_id: "RS.CO-2", title: "Events are reported" },
      { reference_id: "RS.AN-1", title: "Notifications from detections are investigated" },
      { reference_id: "RS.MI-1", title: "Incidents are contained" },
      { reference_id: "RS.MI-2", title: "Incidents are mitigated" },
      { reference_id: "RC.RP-1", title: "Recovery plan is executed" },
      { reference_id: "RC.CO-1", title: "Public relations are managed" },
      { reference_id: "RC.CO-2", title: "Reputation is repaired" },
      { reference_id: "RC.CO-3", title: "Recovery activities are communicated" },
    ],
  },

  iso27001: {
    name: "ISO/IEC 27001",
    version: "2022",
    description:
      "International standard for information security management systems",
    requirements: [
      { reference_id: "A.5.1",  title: "Policies for information security" },
      { reference_id: "A.5.2",  title: "Information security roles and responsibilities" },
      { reference_id: "A.5.3",  title: "Segregation of duties" },
      { reference_id: "A.5.4",  title: "Management responsibilities" },
      { reference_id: "A.5.5",  title: "Contact with authorities" },
      { reference_id: "A.5.6",  title: "Contact with special interest groups" },
      { reference_id: "A.5.7",  title: "Threat intelligence" },
      { reference_id: "A.5.8",  title: "Information security in project management" },
      { reference_id: "A.5.9",  title: "Inventory of information and assets" },
      { reference_id: "A.5.10", title: "Acceptable use of information" },
      { reference_id: "A.5.11", title: "Return of assets" },
      { reference_id: "A.5.12", title: "Classification of information" },
      { reference_id: "A.5.13", title: "Labelling of information" },
      { reference_id: "A.5.14", title: "Information transfer" },
      { reference_id: "A.5.15", title: "Access control" },
      { reference_id: "A.5.16", title: "Identity management" },
      { reference_id: "A.5.17", title: "Authentication information" },
      { reference_id: "A.5.18", title: "Access rights" },
      { reference_id: "A.5.19", title: "Information security in supplier relationships" },
      { reference_id: "A.5.20", title: "Addressing security within supplier agreements" },
      { reference_id: "A.5.21", title: "Managing security in ICT supply chain" },
      { reference_id: "A.5.22", title: "Monitoring and review of supplier services" },
      { reference_id: "A.5.23", title: "Information security for cloud services" },
      { reference_id: "A.5.24", title: "Information security incident management planning" },
      { reference_id: "A.5.25", title: "Assessment of information security events" },
      { reference_id: "A.5.26", title: "Response to information security incidents" },
      { reference_id: "A.5.27", title: "Learning from incidents" },
      { reference_id: "A.5.28", title: "Collection of evidence" },
      { reference_id: "A.5.29", title: "Business continuity planning" },
      { reference_id: "A.5.30", title: "ICT readiness for continuity" },
      { reference_id: "A.5.31", title: "Legal requirements" },
      { reference_id: "A.5.32", title: "Intellectual property rights" },
      { reference_id: "A.5.33", title: "Protection of records" },
      { reference_id: "A.5.34", title: "Privacy and PII protection" },
      { reference_id: "A.5.35", title: "Independent review of information security" },
      { reference_id: "A.5.36", title: "Compliance with policies" },
      { reference_id: "A.5.37", title: "Documented operating procedures" },
      { reference_id: "A.6.1",  title: "Screening" },
      { reference_id: "A.6.2",  title: "Terms and conditions of employment" },
      { reference_id: "A.6.3",  title: "Information security awareness" },
      { reference_id: "A.6.4",  title: "Disciplinary process" },
      { reference_id: "A.6.5",  title: "Responsibilities after termination" },
      { reference_id: "A.6.6",  title: "Confidentiality agreements" },
      { reference_id: "A.6.7",  title: "Remote working" },
      { reference_id: "A.6.8",  title: "Information security event reporting" },
      { reference_id: "A.7.1",  title: "Physical security perimeters" },
      { reference_id: "A.7.2",  title: "Physical entry" },
      { reference_id: "A.7.3",  title: "Securing offices and rooms" },
      { reference_id: "A.7.4",  title: "Physical security monitoring" },
      { reference_id: "A.7.5",  title: "Protecting against physical threats" },
      { reference_id: "A.7.6",  title: "Working in secure areas" },
      { reference_id: "A.7.7",  title: "Clear desk and screen" },
      { reference_id: "A.7.8",  title: "Equipment siting and protection" },
      { reference_id: "A.7.9",  title: "Security of assets off-premises" },
      { reference_id: "A.7.10", title: "Storage media" },
      { reference_id: "A.7.11", title: "Supporting utilities" },
      { reference_id: "A.7.12", title: "Cabling security" },
      { reference_id: "A.7.13", title: "Equipment maintenance" },
      { reference_id: "A.7.14", title: "Secure disposal of equipment" },
      { reference_id: "A.8.1",  title: "User endpoint devices" },
      { reference_id: "A.8.2",  title: "Privileged access rights" },
      { reference_id: "A.8.3",  title: "Information access restriction" },
      { reference_id: "A.8.4",  title: "Access to source code" },
      { reference_id: "A.8.5",  title: "Secure authentication" },
      { reference_id: "A.8.6",  title: "Capacity management" },
      { reference_id: "A.8.7",  title: "Protection against malware" },
      { reference_id: "A.8.8",  title: "Management of technical vulnerabilities" },
      { reference_id: "A.8.9",  title: "Configuration management" },
      { reference_id: "A.8.10", title: "Information deletion" },
      { reference_id: "A.8.11", title: "Data masking" },
      { reference_id: "A.8.12", title: "Data leakage prevention" },
      { reference_id: "A.8.13", title: "Information backup" },
      { reference_id: "A.8.14", title: "Redundancy of systems" },
      { reference_id: "A.8.15", title: "Logging" },
      { reference_id: "A.8.16", title: "Monitoring activities" },
      { reference_id: "A.8.17", title: "Clock synchronisation" },
      { reference_id: "A.8.18", title: "Use of privileged utility programs" },
      { reference_id: "A.8.19", title: "Installation of software" },
      { reference_id: "A.8.20", title: "Networks security" },
      { reference_id: "A.8.21", title: "Security of network services" },
      { reference_id: "A.8.22", title: "Segregation of networks" },
      { reference_id: "A.8.23", title: "Web filtering" },
      { reference_id: "A.8.24", title: "Use of cryptography" },
      { reference_id: "A.8.25", title: "Secure development lifecycle" },
      { reference_id: "A.8.26", title: "Application security requirements" },
      { reference_id: "A.8.27", title: "Secure system architecture" },
      { reference_id: "A.8.28", title: "Secure coding" },
      { reference_id: "A.8.29", title: "Security testing in development" },
      { reference_id: "A.8.30", title: "Outsourced development" },
      { reference_id: "A.8.31", title: "Separation of development environments" },
      { reference_id: "A.8.32", title: "Change management" },
      { reference_id: "A.8.33", title: "Test information" },
      { reference_id: "A.8.34", title: "Protection during audit testing" },
    ],
  },

  hipaa: {
    name: "HIPAA Security Rule",
    version: "2024",
    description:
      "HHS regulations for protecting electronic protected health information",
    requirements: [
      { reference_id: "164.308(a)(1)",          title: "Risk analysis" },
      { reference_id: "164.308(a)(1)(ii)(B)",   title: "Risk management" },
      { reference_id: "164.308(a)(1)(ii)(C)",   title: "Sanction policy" },
      { reference_id: "164.308(a)(1)(ii)(D)",   title: "Information system activity review" },
      { reference_id: "164.308(a)(2)",           title: "Assigned security responsibility" },
      { reference_id: "164.308(a)(3)(i)",        title: "Workforce authorization" },
      { reference_id: "164.308(a)(3)(ii)(A)",   title: "Authorization and supervision" },
      { reference_id: "164.308(a)(3)(ii)(B)",   title: "Workforce clearance procedure" },
      { reference_id: "164.308(a)(3)(ii)(C)",   title: "Termination procedures" },
      { reference_id: "164.308(a)(4)(i)",        title: "Information access management" },
      { reference_id: "164.308(a)(4)(ii)(B)",   title: "Access authorization" },
      { reference_id: "164.308(a)(4)(ii)(C)",   title: "Access establishment and modification" },
      { reference_id: "164.308(a)(5)(i)",        title: "Security awareness and training" },
      { reference_id: "164.308(a)(5)(ii)(A)",   title: "Security reminders" },
      { reference_id: "164.308(a)(5)(ii)(B)",   title: "Protection from malicious software" },
      { reference_id: "164.308(a)(5)(ii)(C)",   title: "Log-in monitoring" },
      { reference_id: "164.308(a)(5)(ii)(D)",   title: "Password management" },
      { reference_id: "164.308(a)(6)(i)",        title: "Security incident procedures" },
      { reference_id: "164.308(a)(6)(ii)",       title: "Response and reporting" },
      { reference_id: "164.308(a)(7)(i)",        title: "Contingency plan" },
      { reference_id: "164.308(a)(7)(ii)(A)",   title: "Data backup plan" },
      { reference_id: "164.308(a)(7)(ii)(B)",   title: "Disaster recovery plan" },
      { reference_id: "164.308(a)(7)(ii)(C)",   title: "Emergency mode operation plan" },
      { reference_id: "164.308(a)(7)(ii)(D)",   title: "Testing and revision procedure" },
      { reference_id: "164.308(a)(7)(ii)(E)",   title: "Applications and data criticality analysis" },
      { reference_id: "164.308(a)(8)",           title: "Evaluation" },
      { reference_id: "164.310(a)(1)",           title: "Facility access controls" },
      { reference_id: "164.310(b)",              title: "Workstation use" },
      { reference_id: "164.310(c)",              title: "Workstation security" },
      { reference_id: "164.310(d)(1)",           title: "Device and media controls" },
      { reference_id: "164.312(a)(1)",           title: "Access control" },
      { reference_id: "164.312(a)(2)(i)",        title: "Unique user identification" },
      { reference_id: "164.312(a)(2)(ii)",       title: "Emergency access procedure" },
      { reference_id: "164.312(a)(2)(iii)",      title: "Automatic logoff" },
      { reference_id: "164.312(a)(2)(iv)",       title: "Encryption and decryption" },
      { reference_id: "164.312(b)",              title: "Audit controls" },
      { reference_id: "164.312(c)(1)",           title: "Integrity" },
      { reference_id: "164.312(c)(2)",           title: "Authentication mechanism" },
      { reference_id: "164.312(d)",              title: "Person or entity authentication" },
      { reference_id: "164.312(e)(1)",           title: "Transmission security" },
      { reference_id: "164.312(e)(2)(i)",        title: "Integrity controls" },
      { reference_id: "164.312(e)(2)(ii)",       title: "Encryption" },
    ],
  },
};
