/**
 * productKnowledge.ts — assembles the "Ask SecureLogic" product-knowledge block
 * from generated, validated sources. NOTHING here is hand-written navigation or
 * workflow prose:
 *
 *   - Navigation (menus, dropdowns, labels, routes, page titles, permissions)
 *     is rendered from the Application Knowledge Index
 *     (`applicationKnowledgeIndex.generated.ts`), derived from the live menu +
 *     route tree.
 *   - How-to workflows are rendered from the structured Workflow Registry
 *     (`productKnowledge/workflows.generated.ts`), authored as one YAML file per
 *     workflow under `productKnowledge/workflows/` and validated against the
 *     index (every navigation label, route, and permission must exist).
 *
 * Both sources are regenerated by `npm run generate:knowledge-index` /
 * `npm run generate:workflows` and drift-locked by tests, so Ask's answers can
 * never diverge from the real UI. The only free text in this file is the
 * platform overview and the "what does not exist" honesty list.
 */

import { APPLICATION_KNOWLEDGE_INDEX } from "./applicationKnowledgeIndex.generated.js";
import type { ApplicationKnowledgeIndex, NavAccess } from "./applicationKnowledgeIndex.js";
import { WORKFLOW_REGISTRY } from "../productKnowledge/workflows.generated.js";
import { renderWorkflows } from "./workflowRegistry.js";

/**
 * Platform overview — the one-paragraph "what is this product" grounding so the
 * assistant frames how-to answers correctly (Platform is the product; the
 * Intelligence Brief is one premium output, not the whole system).
 */
export const PLATFORM_OVERVIEW = `
SecureLogic AI is a holistic cyber, GRC, AI-governance, and third-party-risk posture platform. Organizations use it to understand their current security and governance posture, assess vendors / AI systems / controls / regulatory obligations, monitor risk over time, prioritize action, and produce executive reporting. The Intelligence Brief is one premium output of the platform — a curated executive read on external risk signals — not the center of the product.
`.trim();

/** The live Application Knowledge Index this module renders navigation from. */
export const KNOWLEDGE_INDEX: ApplicationKnowledgeIndex = APPLICATION_KNOWLEDGE_INDEX;

function accessNote(access: NavAccess): string {
  switch (access) {
    case "platform":
      return " [Platform tier]";
    case "premium":
      return " [paid tier]";
    case "admin":
      return " [admin only]";
    case "all":
      return "";
  }
}

/**
 * Render the platform navigation entirely from the Application Knowledge Index —
 * top-level links, dropdown groups + their items, destination paths, and the
 * entitlement required to see each. 100% machine-derived from the live menu; no
 * hand-written navigation text.
 */
function renderNavigation(index: ApplicationKnowledgeIndex): string {
  return index.navigation
    .map((item) => {
      if (item.type === "group") {
        const children = item.children
          .map((c) => `    - ${c.label} → ${c.href}`)
          .join("\n");
        return `- ${item.label}${accessNote(item.access)} (dropdown menu):\n${children}`;
      }
      return `- ${item.label} → ${item.href}${accessNote(item.access)}`;
    })
    .join("\n");
}

/**
 * Render the account / settings / billing / onboarding destinations (the
 * secondary navigation reached from the user menu, not the header). 100%
 * machine-derived from SECONDARY_NAV_ITEMS via the index; grouped in source
 * order. Returns "" when the index carries no secondary navigation (older
 * generated artifacts), so the section is simply omitted.
 */
function renderSecondaryNavigation(index: ApplicationKnowledgeIndex): string {
  const items = index.secondaryNavigation ?? [];
  if (items.length === 0) return "";
  const groupsInOrder: string[] = [];
  const byGroup = new Map<string, string[]>();
  for (const item of items) {
    if (!byGroup.has(item.group)) {
      byGroup.set(item.group, []);
      groupsInOrder.push(item.group);
    }
    byGroup.get(item.group)!.push(`    - ${item.label} → ${item.href}${accessNote(item.access)}`);
  }
  return groupsInOrder
    .map((g) => `- ${g}:\n${byGroup.get(g)!.join("\n")}`)
    .join("\n");
}

/**
 * Capabilities the assistant must NOT claim a UI exists for. Keeps it honest
 * about things that are derived/server-side rather than user-authored.
 */
export const NOT_USER_ACTIONS: ReadonlyArray<string> = [
  "Posture scores are computed/derived, not manually entered — there is no 'create posture' action.",
  "Intelligence Briefs are generated server-side on a schedule; customers view them at /briefs but do not author them in-app.",
  "There is no standalone product help center, guided tour, or knowledge base beyond the Getting Started checklist and this assistant.",
  "Evidence and assessments are always created from a parent item (a specific control, obligation, AI system, or vendor) — there is no global 'add evidence' page detached from a parent.",
];

/**
 * Render the curated knowledge into a compact text block for prompt injection.
 * Deterministic (the index + registry are sorted) so prompt caching and tests
 * are stable.
 */
export function renderProductKnowledge(): string {
  const nav = renderNavigation(KNOWLEDGE_INDEX);
  const secondaryNav = renderSecondaryNavigation(KNOWLEDGE_INDEX);
  const flows = renderWorkflows(WORKFLOW_REGISTRY);
  const limits = NOT_USER_ACTIONS.map((s) => `- ${s}`).join("\n");

  const sections = [
    "SECURELOGIC PRODUCT KNOWLEDGE (how the platform works — use this to answer product / how-to / navigation questions)",
    "",
    "What the platform is:",
    PLATFORM_OVERVIEW,
    "",
    "Top navigation, menus, and who can see each (auto-generated from the live app menu — always current):",
    nav,
  ];

  if (secondaryNav) {
    sections.push(
      "",
      "Account & settings (reached from the account/user menu, not the top nav — auto-generated from the live app, always current):",
      secondaryNav
    );
  }

  sections.push(
    "",
    "Common workflows (each is a validated step-by-step; navigation, routes, and permissions are checked against the live UI):",
    flows,
    "",
    "Important limits (do not claim these UIs exist):",
    limits
  );

  return sections.join("\n");
}
