/**
 * classHandlers.ts — the per-class Postgres behaviour behind the TDG registry.
 *
 * The ONLY class-specific SQL in the system. Everything above this file — the
 * resolver, the hold predicate, the planner, the sweeper, the routes, the audit
 * events — is class-agnostic and operates on the registry entry plus this
 * interface. That split is invariant TDG-15: governing `jobs`,
 * `data_export_files` or `email_provider_events` later means adding a handler
 * here and an entry in dataClasses.ts, and changing nothing else.
 *
 * Every statement names `organization_id` explicitly on top of running inside
 * withTenant() (TDG-13).
 */

import { pg } from "../../infra/postgres.js";

/** One governable row, reduced to what the planner and hold predicate need. */
export interface GovernedObject {
  id: string;
  /** The data subject, when the class has one. Null for system ledgers. */
  ownerUserId: string | null;
  /** COALESCE(ageColumn, ageFallbackColumn) — what "old" means for this class. */
  ageAnchor: Date | null;
}

export interface DeletionCounts {
  /** Top-level objects destroyed. */
  objects: number;
  /** Child rows destroyed, by table. Counts only — never content. */
  children: Record<string, number>;
}

export interface ClassHandler {
  readonly key: string;
  /**
   * Objects whose age anchor is at or before `cutoff`, oldest first, bounded by
   * `limit`. Ordering is deterministic (anchor, then id) so a re-plan with the
   * same inputs selects the same batch (TDG-9).
   */
  selectExpired(
    organizationId: string,
    cutoff: Date,
    limit: number
  ): Promise<GovernedObject[]>;
  /**
   * Destroy exactly these ids for this org. Ordered so that no statement can
   * leave a dangling reference, and idempotent: ids already gone match nothing
   * and are not an error.
   */
  deleteObjects(organizationId: string, ids: readonly string[]): Promise<DeletionCounts>;
  /** Total governed objects, for the dry-run denominator. */
  countGoverned(organizationId: string): Promise<number>;
  /**
   * Metadata for the administrator plane: identity, owner and age only. The
   * return type is GovernedObject precisely because it CANNOT carry content —
   * an administrator governs the lifecycle of an object without the right to
   * read it (TDG: metadata plane / action plane, no content plane).
   */
  listObjects(
    organizationId: string,
    limit: number,
    offset: number
  ): Promise<GovernedObject[]>;
  /** One object by id, for owner/administrator deletion. Null when absent. */
  findObject(organizationId: string, id: string): Promise<GovernedObject | null>;
}

/* ─────────────────────────────── ask_conversation ────────────────────────── */

const ASK_AGE = "COALESCE(last_message_at, created_at)";

const askConversationHandler: ClassHandler = {
  key: "ask_conversation",

  async selectExpired(organizationId, cutoff, limit) {
    const { rows } = await pg.query<{ id: string; user_id: string | null; age_anchor: Date }>(
      `SELECT id, user_id, ${ASK_AGE} AS age_anchor
         FROM ask_conversations
        WHERE organization_id = $1
          AND ${ASK_AGE} <= $2
        ORDER BY ${ASK_AGE} ASC, id ASC
        LIMIT $3`,
      [organizationId, cutoff, limit]
    );
    return rows.map((r) => ({ id: r.id, ownerUserId: r.user_id, ageAnchor: r.age_anchor }));
  },

  async findObject(organizationId, id) {
    const { rows } = await pg.query<{ id: string; user_id: string | null; age_anchor: Date }>(
      `SELECT id, user_id, ${ASK_AGE} AS age_anchor
         FROM ask_conversations
        WHERE organization_id = $1 AND id = $2`,
      [organizationId, id]
    );
    const r = rows[0];
    return r ? { id: r.id, ownerUserId: r.user_id, ageAnchor: r.age_anchor } : null;
  },

  async countGoverned(organizationId) {
    const { rows } = await pg.query<{ count: string }>(
      `SELECT COUNT(*)::text AS count FROM ask_conversations WHERE organization_id = $1`,
      [organizationId]
    );
    return Number(rows[0]?.count ?? "0");
  },

  async listObjects(organizationId, limit, offset) {
    // `title` is deliberately not selected: it is generated by the model FROM
    // the conversation, so it is content wearing a metadata name.
    const { rows } = await pg.query<{ id: string; user_id: string | null; age_anchor: Date }>(
      `SELECT id, user_id, ${ASK_AGE} AS age_anchor
         FROM ask_conversations
        WHERE organization_id = $1
        ORDER BY ${ASK_AGE} DESC, id DESC
        LIMIT $2 OFFSET $3`,
      [organizationId, limit, offset]
    );
    return rows.map((r) => ({ id: r.id, ownerUserId: r.user_id, ageAnchor: r.age_anchor }));
  },

  /**
   * DELETION ORDER — deliberate, and the reason each step exists:
   *
   *   1. ask_provenance_contexts. They would cascade from ask_messages anyway,
   *      but they are the one place FULL authorized tool payloads are ever
   *      written, so they are destroyed FIRST and counted explicitly rather
   *      than disappearing as a side effect nobody measured.
   *   2. ask_proposed_actions. They cascade from the conversation, so before
   *      this they vanished UNCOUNTED — a governance record that under-reports
   *      what it destroyed is the failure mode TDG-14 exists to prevent.
   *      Deleted explicitly and counted. (Agentic proposals are dark today;
   *      counting them now costs one statement and stops the audit trail from
   *      quietly becoming wrong the day the flag flips.)
   *   3. ask_messages. Deleting these SET NULLs ask_tool_invocations.message_id
   *      (20261014) instead of cascading it away, so the audit ledger — the
   *      denials included — outlives the content it describes. Those orphaned
   *      ledger rows then age out under their OWN class policy.
   *   4. ask_conversations. Last, so no step ever runs against a thread whose
   *      parent row is already gone.
   *
   * All three statements run in the caller's transaction. There is no partial
   * outcome: the batch commits whole or not at all (TDG-12).
   */
  async deleteObjects(organizationId, ids): Promise<DeletionCounts> {
    if (ids.length === 0) return { objects: 0, children: {} };
    const idList = [...ids];

    const contexts = await pg.query(
      `DELETE FROM ask_provenance_contexts
        WHERE organization_id = $1
          AND message_id IN (
            SELECT id FROM ask_messages
             WHERE organization_id = $1 AND conversation_id = ANY($2::uuid[])
          )`,
      [organizationId, idList]
    );

    const proposals = await pg.query(
      `DELETE FROM ask_proposed_actions
        WHERE organization_id = $1 AND conversation_id = ANY($2::uuid[])`,
      [organizationId, idList]
    );

    const messages = await pg.query(
      `DELETE FROM ask_messages
        WHERE organization_id = $1 AND conversation_id = ANY($2::uuid[])`,
      [organizationId, idList]
    );

    const conversations = await pg.query(
      `DELETE FROM ask_conversations
        WHERE organization_id = $1 AND id = ANY($2::uuid[])`,
      [organizationId, idList]
    );

    return {
      objects: conversations.rowCount ?? 0,
      children: {
        ask_messages: messages.rowCount ?? 0,
        ask_provenance_contexts: contexts.rowCount ?? 0,
        ask_proposed_actions: proposals.rowCount ?? 0
      }
    };
  }
};

/* ───────────────────────────── ask_tool_invocation ───────────────────────── */

/**
 * The ledger. Its eligibility predicate carries the other half of TDG-5:
 * `message_id IS NULL` means "the turn this describes is already gone", so a
 * LIVE answer can never have its evidence swept out from under it. This is a
 * structural guarantee, not a query convention — there is no code path that
 * selects a ledger row still attached to a message.
 *
 * It has no user column, so `ownerUserId` is always null and subject-scoped
 * holds correctly do not cover it: a ledger row records what the SYSTEM did.
 */
const askToolInvocationHandler: ClassHandler = {
  key: "ask_tool_invocation",

  async selectExpired(organizationId, cutoff, limit) {
    const { rows } = await pg.query<{ id: string; created_at: Date }>(
      `SELECT id, created_at
         FROM ask_tool_invocations
        WHERE organization_id = $1
          AND message_id IS NULL
          AND created_at <= $2
        ORDER BY created_at ASC, id ASC
        LIMIT $3`,
      [organizationId, cutoff, limit]
    );
    return rows.map((r) => ({ id: r.id, ownerUserId: null, ageAnchor: r.created_at }));
  },

  async findObject(organizationId, id) {
    const { rows } = await pg.query<{ id: string; created_at: Date }>(
      `SELECT id, created_at FROM ask_tool_invocations
        WHERE organization_id = $1 AND id = $2 AND message_id IS NULL`,
      [organizationId, id]
    );
    const r = rows[0];
    return r ? { id: r.id, ownerUserId: null, ageAnchor: r.created_at } : null;
  },

  async countGoverned(organizationId) {
    const { rows } = await pg.query<{ count: string }>(
      `SELECT COUNT(*)::text AS count FROM ask_tool_invocations WHERE organization_id = $1`,
      [organizationId]
    );
    return Number(rows[0]?.count ?? "0");
  },

  async listObjects(organizationId, limit, offset) {
    const { rows } = await pg.query<{ id: string; created_at: Date }>(
      `SELECT id, created_at
         FROM ask_tool_invocations
        WHERE organization_id = $1
        ORDER BY created_at DESC, id DESC
        LIMIT $2 OFFSET $3`,
      [organizationId, limit, offset]
    );
    return rows.map((r) => ({ id: r.id, ownerUserId: null, ageAnchor: r.created_at }));
  },

  async deleteObjects(organizationId, ids): Promise<DeletionCounts> {
    if (ids.length === 0) return { objects: 0, children: {} };
    // Belt and braces: the id list came from a message_id IS NULL selection,
    // and the DELETE re-asserts it. A ledger row that was re-attached between
    // plan and execute (impossible today) must not be destroyed.
    const result = await pg.query(
      `DELETE FROM ask_tool_invocations
        WHERE organization_id = $1 AND id = ANY($2::uuid[]) AND message_id IS NULL`,
      [organizationId, [...ids]]
    );
    return { objects: result.rowCount ?? 0, children: {} };
  }
};

const HANDLERS = new Map<string, ClassHandler>([
  [askConversationHandler.key, askConversationHandler],
  [askToolInvocationHandler.key, askToolInvocationHandler]
]);

/** Null for an unregistered class — the caller refuses rather than guessing. */
export function getClassHandler(key: string): ClassHandler | null {
  return HANDLERS.get(key) ?? null;
}

/** Test seam: register an extra class without touching production code (TDG-15). */
export function registerClassHandler(handler: ClassHandler): void {
  HANDLERS.set(handler.key, handler);
}

export function unregisterClassHandler(key: string): void {
  HANDLERS.delete(key);
}
